### ISSUE TITLE
Swagger documentation breaks when Blueprint has subdomain

### ISSUE THREAD

**Issue by sharan-karanth** [noirbizarre/flask-restplus#103]
I am currently on version 0.8.2 of your wonderful API.

When I register my API blueprint with a subdomain like in the code below

```
api_bp = Blueprint('api', __name__, subdomain="api",  url_prefix='/api')
flask_api = Api(api_bp,
                  version='1.0-Beta',
                  title='My API',
                  description='Some description',
                  default='General',
                  default_label='General Operations')

```
The generated swagger.json has an invalid host url.
The culprit code is in swagger.py, line 185
```
   'host': current_app.config.get('SERVER_NAME', None) or None,
```

It does not take into consideration the subdomain. Leaving it as None works 

One option is to leave it as none if api.blueprint.subdomain is not None.
Another option would be to allow setting of host url in Api init and use that if provided.

**Comment by sharan-karanth** [comment]
Thank you

**Comment by noirbizarre** [comment]
You're welcome ;)
