### ISSUE TITLE
Getting swagger-ui.js and not swagger-ui.min.js

### ISSUE THREAD

**Issue by laverick** [noirbizarre/flask-restplus#106]
Thanks for maintaining / developing a nice library. I've gotten some very useful docs up in a short time for my flask app with the help of flask-restplus.

We just deployed an early version of our software to a not-quite-production server and noticed that swagger load times are very slow. We are running on werkzeug (not in debug mode), so surely there will be some gains switching to nginx, but after some digging I noticed that we're also getting the non-minified version of `swagger-ui.js`, which is costing about 2MB extra.

Is there a config / setting / piece of magic to switch the lib to minified, or do I need to do it manually by using my own `swagger-ui-libs.html` to load `swagger-ui.js` or similar?

Cheers,
Dustin

**Comment by laverick** [comment]
Thanks for the enhancement!

**Comment by noirbizarre** [comment]
You're welcome !

That's all I can do with the given pattern. If you want better compression, you will have to do your own documentation page.
