### ISSUE TITLE
Swagger-ui does not handle properly json arguments

### ISSUE THREAD

**Issue by sque** [noirbizarre/flask-restplus#11]
I am building an api where a PUT operation should accept a json object with some well-defined properties. As far as I understood from the flask-restful documentation you can do something like
```python
node_put_parser = api.parser()
node_put_parser.add_argument(
    'timestamp',
    type=int, required=True, help='The time statistics were generated',
    location='json')
node_put_parser.add_argument(
    'interfaces',
    type=dict, required=True,
    help='Statistics per interface, indexed by the ip of the interface',
    location='json')
node_put_parser.add_argument(
    'babel_dump',
    type=str, required=True,
    help='The state of the babeld daemon as generated by the service itself',
    location='json')
```

The `RequestParser` seems to work OK (I didn't testing extensively though) but the swagger-ui generates an obscure form that is unusable.

![flask-restplus-json-post](https://cloud.githubusercontent.com/assets/3830635/5592806/ce68fe9c-91ec-11e4-8e8f-d50fabbf57ac.png)

Trying to use this form is impossible. For all json parameters, it just gets the latest and use this as the request body. 

The firefox debug interface reports the following if I press `Try it out`

```
PUT http://localhost:5000/api/map/node/1/statistics
```
Headers:
```
Host: localhost:5000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:34.0) Gecko/20100101 Firefox/34.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json; charset=UTF-8
Referer: http://localhost:5000/api/
Content-Length: 23
Cookie: __utma=111872281.398094953.1364220452.1364220452.1364220452.1; ui_language=en_US; splunkweb_csrf_token_8000=13650718194689432226; session=eyJfaWQiOnsiIGIiOiJObVkwWVRoak5qRTJZalk1WWpjek1qRTBNR0ppTlRRME9XUXdPR1ZqTnpjPSJ9fQ.B4cVLQ.uXmbw59ggilVLP_pxy5dKS-PqOo
Connection: keep-alive
```
Request Body:
```
{'127.0.0.1': [1,2,3] }
```

Is this a swagger-ui limitation or an issue of flask-restplus?

**Comment by noirbizarre** [comment]
Hi!

This is a known Swagger UI limitation.
There is a pending pull-request on the subject: https://github.com/swagger-api/swagger-ui/pull/398

I hope it will be merged soon!

**Comment by frol** [comment]
Just for your info, there is a newer PR in Swagger-UI, which seems to be waiting for review - https://github.com/swagger-api/swagger-ui/pull/1589

**Comment by frol** [comment]
Here is my RESTful API example server using Flask-RESTplus with marshmallow, webargs, and JSON Editor and Password Flow patches to Swagger-UI: https://github.com/frol/flask-restplus-server-example

Notice that I have patched Flask-RESTplus (find `flask_restplus_patched` folder).
