### ISSUE TITLE
Static files served from module directory are very slow

### ISSUE THREAD

**Issue by laverick** [noirbizarre/flask-restplus#112]
Hi, 

This is more of an enquiry than an issue, but after lots of debugging I'm at a loss so I thought I'd see if anyone has any ideas.

I'm using `flask-restplus` on a digitalocean box, and for some reason the static swagger-related files take incredibly long (10s of seconds for some files) to serve the default way, i.e.: from the python module directory. If I move the static files into the flask directory everything works fine.

This issue also happens in a docker container on the digitalocean box. It doesn't happen to me at all running locally on Os X, or in a docker container + VM on Os X.

This probably isn't an issue with flask-restplus, but I thought I'd ask in case there's any thoughts on what might be going wrong.

Thanks

**Comment by noirbizarre** [comment]
Hi, 

Sorry for the late response.
It seems to me this not `flask-restplus` related but specific to digitalocean or you app configuration (docker volumes, revese proxy...)
My guess, they or you use different storages for installed modules and static dir.

My advice, in production, static assets should not be served by flask but your reverse proxy.

**Comment by laverick** [comment]
No worries and thanks for the advice.
