### ISSUE TITLE
Add ability to document response headers

### ISSUE THREAD

**Issue by awiddersheim** [noirbizarre/flask-restplus#119]
The library has the ability to quickly document the expected [request headers](https://flask-restplus.readthedocs.org/en/stable/documenting.html#headers) but currently there is not greay way to document the response headers. There was some stuff added in https://github.com/noirbizarre/flask-restplus/commit/a2b73da8d3023cf9450ecc320a6eb1c8f79bb9d6 to be able to do it but only with error handlers.

I was thinking the best place to do it would be in [`response()`](https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/namespace.py#L253). 

Seems like it might be better to convert responses to a `dict` rather than a `tuple` which has to get unpacked and makes this a bit difficult.

Perhaps this is part of the _todo_ planned:

https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/swagger.py#L384

**Comment by noirbizarre** [comment]
Hum, you're right.

Seems to be the`@api.header` is redundant with adding a `RequestParser` header argument.
So maybe I should use `@api.header` for documenting response header instead a let `RequestParser` expose expected headers ?

**Comment by awiddersheim** [comment]
Yeah, that makes sense to me as well. Pretty large breaking change though obviously.

**Comment by noirbizarre** [comment]
Yes, but not so big, `@api.response` was added late (0.8) and it's sole purpose is documenting, so it does not break the API behavoir, only the header documentation.

**Comment by defat** [comment]
I'd suggest extending api.response with headers definition instead of using separate api.header decorator thus it gives possibility for returning different headers for different response statuses.
