### ISSUE TITLE
Cannot use fields.String enum properly

### ISSUE THREAD

**Issue by liiight** [noirbizarre/flask-restplus#124]
I try to use req parser with a fields.String enum to display a nice dropdown in swagger:

```python
seen_search_parser = api.parser()
seen_search_parser.add_argument('page', type=int, default=1, help='Page number')
seen_search_parser.add_argument('max', type=int, default=100, help='Seen entries per page')
seen_search_parser.add_argument('local_seen', type=fields.String(enum=['true', 'false', 'all'], default='all'),
                                help='Filter list by local status.')
```

I the use the `expect` wrapper and I do see this nicely in swagger. But when I try to send the request I get a validation error. When debugging I get a `error: String object is not callable` raised from the `reqparse.convert` method.

Why is that? I am sending a string value obviously under the parameter. What am I doing wrong?

**Comment by noirbizarre** [comment]
Hi!

`RequestParser` expect types from `flask_restplus.inputs` module. (See https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/inputs.py#L372-L393 for example)

You can write your own, in you case:
```python
def local_seen(value):
    if value not in ('true', 'false', 'all'):
        raise ValueError('Unexpected value {0}'.format(value))

seen_search_parser = api.parser()
seen_search_parser.add_argument('page', type=int, default=1, help='Page number')
seen_search_parser.add_argument('max', type=int, default=100, help='Seen entries per page')
seen_search_parser.add_argument('local_seen', type=local_seen, default='all',
                                help='Filter list by local status.')


class MyResource(Resource):
    @api.expect(seen_search)
    def get(self):
         args = seen_search..parse_args()
         local_seen = args['local_seen']
         if local_seen == 'true':
             # true case
         elif local_seen == 'false':
             # false case
         elif local_seen == 'all':
             # all case
```

My advice, use boolean and assume 'all' when not specified:
```python
from flask_restplus.inputs import boolean
seen_search_parser = api.parser()
seen_search_parser.add_argument('page', type=int, default=1, help='Page number')
seen_search_parser.add_argument('max', type=int, default=100, help='Seen entries per page')
seen_search_parser.add_argument('local_seen', type=boolean, help='Filter list by local status.')

class MyResource(Resource):
    @api.expect(seen_search)
    def get(self):
         args = seen_search..parse_args()
         local_seen = args['local_seen']
         if local_seen is True:
             # true case
         elif local_seen is False:
             # false case
         elif local_seen is None:
             # all case
```

**Comment by liiight** [comment]
Thank you for your suggestion, custom enum is in fact what I have been successfully using until now. 
However, when using the fields.String with enum as type, swagger ui shows a drop down input as opposed to a textual one, which is a lot nicer. If a default value is set it pre selects it as well. I was wondering if and how that swagger ui element is currently available with restplus. 

I do not have access to my machine ATM but when I'll do, I'll provide some screen shots to demonstrate my point more clearly.

**Comment by noirbizarre** [comment]
I know what you mean for the dropdown but SwaggerUI also display boolean as a dropdown (because there is 3 states: `true`, `false` and `undefined/empty`) with default on empty if no default value is specified.
It's exactly your case and will be easier for your API user because they can pass True, TRUE, 1 as truthy values...

I forgot but `RequestParser` can also handle string enumerations
```python
seen_search_parser = api.parser()
seen_search_parser.add_argument('page', type=int, default=1, help='Page number')
seen_search_parser.add_argument('max', type=int, default=100, help='Seen entries per page')
seen_search_parser.add_argument('local_seen', type=str, default='all',
                                choices=('true', 'false', 'all'),
                                help='Filter list by local status.')


class MyResource(Resource):
    @api.expect(seen_search)
    def get(self):
        args = seen_search..parse_args()
        local_seen = args['local_seen']
        if local_seen == 'true':
            # true case
        elif local_seen == 'false':
            # false case
        elif local_seen == 'all':
            # all case
```

**Comment by liiight** [comment]
`choices` is EXACTLY what i was looking for, thanks!
