### ISSUE TITLE
AttributeError: 'function' object has no attribute 'as_view'

### ISSUE THREAD

**Issue by harishkashyap** [noirbizarre/flask-restplus#125]
Unable to run this on python 3.5:

 res = super(Function, self).__call__(*new_args, **new_kwargs)
packages/flask_restplus/api.py", line 233, in add_resource
    return self.default_namespace.add_resource(resource, *urls, **kwargs)
 packages/flask_restful/__init__.py", line 441, in _register_view
    resource_func = self.output(resource.as_view(endpoint, *resource_class_args,
AttributeError: 'function' object has no attribute 'as_view'

**Comment by noirbizarre** [comment]
Hi !

I'll need a little bit more context but It seem to me your are trying to use a simple function as resource.

**Comment by harishkashyap** [comment]
You are right @noirbizarre . I will close this.

**Comment by shrivijaya** [comment]
I am getting below error when trying to call the app file

Traceback (most recent call last):

  File "C:\Users\Vijaya\code_poc\nlp\master\runserver_app1.py", line 90, in <module>
    api.add_resource(Default, '/')

  File "C:\Users\Vijaya\anaconda\lib\site-packages\flask_restful\__init__.py", line 392, in add_resource
    self._register_view(self.app, resource, *urls, **kwargs)

  File "C:\Users\Vijaya\anaconda\lib\site-packages\flask_restful\__init__.py", line 432, in _register_view
    resource_func = self.output(resource.as_view(endpoint, *resource_class_args,

AttributeError: module 'App.Default' has no attribute 'as_view'

**Comment by shrivijaya** [comment]
Please help me on this

**Comment by c7h** [comment]
@shrivijaya the function `api.add_resource` wants a type(Resource). It looks like you are passing a whole module.
From the information you provided, I can only guess `api.add_resource(Default.Default, '/')` might help?

https://flask-restful.readthedocs.io/en/latest/api.html#flask_restful.Api.add_resource
