### ISSUE TITLE
file upload example

### ISSUE THREAD

**Issue by harishkashyap** [noirbizarre/flask-restplus#127]
I am unable to find an example to upload a file. The request parser didnt work for me. Is there a way to specify this type in 

resource_fields = api.model('Resource', {
    'name': fields.String(required=True, description='name'),
    'type': fields.String(required=True, description='type'),
    'file' :....?
})

Here is the error for using:

parser = api.parser()
parser.add_argument('param', type=int, help='Some param', location='form')
parser.add_argument('in_files', type=FileStorage, location='files')

Error:
 parser.add_argument('in_files', type=FileStorage, location='files')
NameError: name 'FileStorage' is not defined

**Comment by harishkashyap** [comment]
FileStorage needs to be imported. this is resolved.
from werkzeug.datastructures import FileStorage

**Comment by idchlife** [comment]
There is no yet example of File field for swagger documentation :(

**Comment by matthewatabet** [comment]
It would be helpful to have a `field.File` -- I'd like to document the result of a `get` route which returns a file object.
