### ISSUE TITLE
change example based on form fields

### ISSUE THREAD

**Issue by harishkashyap** [noirbizarre/flask-restplus#129]
Is it possible to change the example displayed based on the input "y" in the param?

for example it woudl be nice to format the example on the form entry.
@api.route('/test', methods=['POST'])
@api.doc(params={'y': 'test'})
class predict(Resource):
    @expect(fields) 
    def post(self):

**Comment by harishkashyap** [comment]
@noirbizarre is there anyway multiple examples can be associated with different mime-type inputs? I see in swagger it is possible for example to specify for json and xml in the same query. I am finding it not easy to do so in restplus.

**Comment by noirbizarre** [comment]
Hi !

Sorry for the late response.

It seems to me there is 2 separate issue here.
- **How can you add an example for a field value ?** Sadly the current specification does not allow field level example, only schema level: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject
- **Can we provide different example based on the mime type ?** Right now, no. The specifications only allow one example by schema.

These are interesting ideas so I advice you to suggest them on the [OpenAPI specification bug tracker](https://github.com/OAI/OpenAPI-Specification/issues).
