### ISSUE TITLE
Model schema is missing from swagger-ui in a special case.

### ISSUE THREAD

**Issue by sque** [noirbizarre/flask-restplus#13]
I am describing the response model of an endpoint using the `api.marshal_with` and `api.model` functions.

The desired model is:
```python
speed_statistics_sample = api.model('SpeedSample', {
    'timestamp': fields.DateTime(),
    'rate': fields.Float()
})

speed_statistics_period = fields.List(fields.Nested(speed_statistics_sample))

speed_statistics_link = api.model('LinkSpeed', {
    'rx': speed_statistics_period,
    'tx': speed_statistics_period
})
```

However on the swagger-ui it cannot decode the nested models. On `Model Schema` page thefields `rx` and `tx` says `null`, while on `Model` page it understands that depends on `SpeedSample` model, it does not provide its information:
![model_missing](https://cloud.githubusercontent.com/assets/3830635/5615303/c1c676b0-9502-11e4-8005-992f1ef01c63.png)
![model_schema_missing](https://cloud.githubusercontent.com/assets/3830635/5615300/b99edf2c-9502-11e4-9d02-2976a91abc88.png)

---
The wierd thing is that if I change a bit the api and remove the `List` field for one member, everything is fixed, though this is not the desired model that I want to describe.

```python
speed_statistics_sample = api.model('SpeedSample', {
    'timestamp': fields.DateTime(),
    'rate': fields.Float()
})

speed_statistics_period = fields.List(fields.Nested(speed_statistics_sample))

speed_statistics_link = api.model('LinkSpeed', {
    'rx': fields.Nested(speed_statistics_sample),
    'tx': speed_statistics_period
})
```

Then the swagger-ui is working as expected:
![model](https://cloud.githubusercontent.com/assets/3830635/5615403/9f408184-9503-11e4-8731-d9d3e1069920.png)
![model_schema](https://cloud.githubusercontent.com/assets/3830635/5615404/a0aa7692-9503-11e4-9c9c-7dd7cdbd9004.png)

Notice, that marshaling was perfect on all cases, it is only an issue of documentation.

**Comment by noirbizarre** [comment]
Should be fixed by 09a6c64
