### ISSUE TITLE
how to customize the UI?

### ISSUE THREAD

**Issue by harishkashyap** [noirbizarre/flask-restplus#130]
whats the best way to customize the existing swagger ui? Is there a way to do so easily? like adding a custom drop down or a button?

**Comment by noirbizarre** [comment]
It depends.

Right now Swagger-UI is not very customizable and I won't provide any customization not available in Swagger-UI.

But, you can customize the documentation page. See: https://flask-restplus.readthedocs.org/en/stable/swagger.html#swagger-ui

**Comment by jhallard** [comment]
I think  what he is asking is, how do we use (supported) custom CSS files like these: https://github.com/ostranme/swagger-ui-themes

They are all themes on the official swagger.html file, so this isn't doing anything custom or outside of swagger, we just need a way to specify CSS for the swagger.html that is rendered from the doc page.

thanks!

**Comment by jhallard** [comment]
Hey everyone, I think I figured out how to do this. I wrote this script a while ago, so, to be honest, I'm not quite 100% how it works, but anyway

let's say I'm in a directory `~/my_project`

then I go

```bash
$ cd ~/my_project
$ virtalenv venv
$ source venv/bin/activate
$ pip install flask-restplus
$ # flast-restplus is installed into venv/lib/python2.7/site-packages/flask_restplus
$ git clone https://github.com/ostranme/swagger-ui-themes
```

okay, so now in your project directory you have a `venv` with `flask-restplus` installed and you also have cloned the `swagger-ui-themes` project from github. Then the script below applies


```bash
#!/usr/bin/env bash

# make some new directories to hold the custom swagger theme files
mkdir -p venv/lib/python2.7/site-packages/flask_restplus/static/custom/
mkdir -p venv/lib/python2.7/site-packages/flask_restplus/static/custom3/

# copy the custom swagger theme files into the flask_restplus static directory
cp swagger-ui-themes/themes/2.x/theme-* venv/lib/python2.7/site-packages/flask_restplus/static/custom/
cp swagger-ui-themes/themes/3.x/theme-* venv/lib/python2.7/site-packages/flask_restplus/static/custom3/

# go ahead and tell flask_restplus to import the custom css files by using one of the following lines

# if you want to use the theme-monokai.css from swagger-ui-themes/themes/2.x, use
cat << EOF >> venv/lib/python2.7/site-packages/flask_restplus/templates/swagger-ui-css.html
<link href="{{ swagger_static('custom/theme-monokai.css') }}" media="screen" rel="stylesheet" type="text/css"/>
EOF

# if you want to use the theme theme-outline.css from swagger-ui-themes/themes/2.x, use
cat << EOF >> venv/lib/python2.7/site-packages/flask_restplus/templates/swagger-ui-css.html
<link href="{{ swagger_static('custom3/theme-outline.css') }}" media="screen" rel="stylesheet" type="text/css"/>
EOF

# from here you can change either of the top two lines to import any of the custom css files that you wish
```

these themes are now imported from the flask-restplus swagger css file and your documentation will be updated accordingly.

To show this works, this is what my flask-restplus documentation looked like before I ran the above script

![image](https://user-images.githubusercontent.com/7551586/54226146-688a2300-44ba-11e9-8605-f3b869739f90.png)


and this is what it looks like when I put the import line for the 'theme-outline.css` file into the swagger-ui-css.html file

![image](https://user-images.githubusercontent.com/7551586/54226195-86f01e80-44ba-11e9-82f2-17f68c1f1c99.png)

**Comment by jhallard** [comment]
@5kyc0d3r @AnsgarSchmidt @zannkukai @K3UL I've updated this issue with instructions on how to do this in case you were still wondering

**Comment by atomrigs** [comment]
If you want to add a custom css, do these two steps;
(1)Add swagger_custom.css in /static/ folder of your own project.
(2)Make a shell script and run it.

```shell
LINE='<link media="screen" rel="stylesheet" type="text/css" href="/static/swagger_custom.css" />'
export FILE=$VIRTUAL_ENV/lib/python3.6/site-packages/flask_restplus/templates/swagger-ui-css.html
grep -qxF "$LINE" "$FILE" || echo "$LINE" >> "$FILE"
```

**Comment by abhishekmhjn** [comment]
One simple way is to host your custom css at the same url of this library, just add a route function and serve static css via flask send_file

```
@app.route('/swaggerui/swagger-ui.css')
def custom_css_theme():
      return send_file('YOUR CUSTOM CSS FILE PATH')
```
