### ISSUE TITLE
hosting behind nginx proxy error

### ISSUE THREAD

**Issue by harishkashyap** [noirbizarre/flask-restplus#132]
I have the Api docs working perfectly locally but when I host with nginx I get this error:
Can't read from server. It may not have the appropriate access-control-origin settings.

I have enabled CORS on /doc/ in nginx. Any ideas? Is there a way to set the url? For prod environment, @noirbizarre is there a way to specify the url? It seems like behind nginx, the swagger.json url doesn't get set properly which can prevent hosting this in prod.

**Comment by mtrofimm** [comment]
+1

**Comment by ziirish** [comment]
I think your answer is [here](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups).
It is a Flask related thing, not a flask-restplus one.

**Comment by noirbizarre** [comment]
Thanks @ziirish for the response.

@harishkashyap and @mtrofimm, have you tried the ProxyFix solution ? Is it working ?

**Comment by heaje** [comment]
I realize this is closed, but here's another way to fix this same problem via code.

```python
from flask_restplus import Api as rpapi

@property
def specs_url(self):
    """Fixes issue where swagger-ui makes a call to swagger.json over HTTP.
       This can ONLY be used on servers that actually use HTTPS.  On servers that use HTTP,
       this code should not be used at all.
    """
    return flask.url_for(self.endpoint('specs'), _external=True, _scheme='https')
```

Then in your application factory, add something like this (I use a config value called "FORCE_SWAGGER_JSON_HTTPS" to indicate when I want this:
```python
if app.config['FORCE_SWAGGER_JSON_HTTPS']:
    rpapi.specs_url = specs_url
```

**Comment by webee** [comment]
[ProxyFix](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups)
ensure nginx config set `X-Forwarded-Proto` header
```
{
    ...
    proxy_set_header X-Forwarded-Proto $scheme;
    ...
}
```

**Comment by Jdubedition** [comment]
> I think your answer is [here](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups).
> It is a Flask related thing, not a flask-restplus one.

If using gunicorn, you need to set the following in a config file:
`secure_scheme_headers = {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}`

**Comment by arvsr1988** [comment]
anyone able to get one of these solutions to work for flask 1.0? I tried the following options and i tried to send a request to my localhost, not able to get the swagger ui to load the doc from https://...

this is the request i'm trying 
curl -H 'X-Forwarded-Proto: https' -H 'X-Forwarded-Ssl: on' -H 'Host: myactualhost.com' -H 'scheme: https'   http://localhost:6000/doc/

> I realize this is closed, but here's another way to fix this same problem via code.
> 
> ```python
> from flask_restplus import Api as rpapi
> 
> @property
> def specs_url(self):
>     """Fixes issue where swagger-ui makes a call to swagger.json over HTTP.
>        This can ONLY be used on servers that actually use HTTPS.  On servers that use HTTP,
>        this code should not be used at all.
>     """
>     return flask.url_for(self.endpoint('specs'), _external=True, _scheme='https')
> ```
> 
> Then in your application factory, add something like this (I use a config value called "FORCE_SWAGGER_JSON_HTTPS" to indicate when I want this:
> 
> ```python
> if app.config['FORCE_SWAGGER_JSON_HTTPS']:
>     rpapi.specs_url = specs_url
> ```

i put this in my api initialization block, i get an error saying that the api object is not assignable. 

> > I think your answer is [here](http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups).
> > It is a Flask related thing, not a flask-restplus one.
> 
> If using gunicorn, you need to set the following in a config file:
> `secure_scheme_headers = {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}`

didn't work for me although i'm using gunicorn. 

also tried proxyfix for flask 1. didn't seem to work. 
http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/

Not sure what i'm doing wrong ...

**Comment by ziirish** [comment]
The ProxyFix has been reworked in Werkzeug 0.15, it is now much more flexible (and much less easy to use).

Documentation [here](https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/#module-werkzeug.middleware.proxy_fix).

**Comment by arvsr1988** [comment]
@ziirish thanks for making me re-read the proxyfix documentation. I got it working now. 

Here's what i did.
`
app = Flask(__name__)
from werkzeug.middleware.proxy_fix import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)
`

and the curl request i sent was 

curl -X GET \
  http://localhost:6000/doc/ \
  -H 'X-Forwarded-Host: my.actual.host.com' \
  -H 'X-Forwarded-Proto: https'

**Comment by icinsight** [comment]
I had the same issue with serving swagger docs by flask rest_plus behind a nginx proxy and https.

Here was the solution:

**Add these in your app.py:**
`from werkzeug.middleware.proxy_fix import ProxyFix`
`app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)`

**Add these lines in you nginx server config:**
`    location / {`
`        proxy_pass http://127.0.0.1:5000;`
        **proxy_set_header Host $host;**
        **proxy_set_header X-Real-IP $remote_addr;**
        **proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;**
        **proxy_set_header X-Forwarded-Proto $scheme;**
`    }`

Remember to restart nginx! Works like a charm now.

**Comment by fsalazarh** [comment]
> I had the same issue with serving swagger docs by restplus behind a nginx proxy and https.
> Here was the solution:
> 
> **Add these in your app.py:**
> `from werkzeug.middleware.proxy_fix import ProxyFix`
> `app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)`
> 
> **Add these lines in you nginx server config:**
> ` location / {`
> ` proxy_pass http://127.0.0.1:5000;`
> _proxy_set_header Host $host;_
> _proxy_set_header X-Real-IP $remote_addr;_
> _proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;_
> _proxy_set_header X-Forwarded-Proto $scheme;_
> ` }`
> 
> Remember to restart nginx! Works like a charm now.

This solution works for me.
