### ISSUE TITLE
Import Namespace throws an error

### ISSUE THREAD

**Issue by kavink** [noirbizarre/flask-restplus#133]
Docs and example say this should work

```
https://github.com/noirbizarre/flask-restplus/blob/master/examples/zoo/cat.py#L1-L3
```

But this keeps throwing error.

**Comment by noirbizarre** [comment]
Hi !

I just ran the example you mentionned (`python example/complex.py`) and it works fine here.
I'll need more details to help you: what is the error, the stacktrace...

**Comment by noirbizarre** [comment]
I forgot to say, the release allowing to do that is not yet released.
It will very soon.

**Comment by frol** [comment]
0.9.0 is already released, so the examples should work fine.
