### ISSUE TITLE
Group Namespaces like petstore example?

### ISSUE THREAD

**Issue by Jonovono** [noirbizarre/flask-restplus#134]
Hi. I am wondering how you can group your endpoints like the petstore example has pets, store, etc

    http://petstore.swagger.io/#/pet

I have tried creating namespaces for the different groups but that doesn't seem to do. Is there another way to do this?

Thanks.

**Comment by noirbizarre** [comment]
Hi !

Namespaces are definitively the way to go. I think you looked at the sample on the master.
This syntax/feature is not yet released, but it will very soon !

**Comment by Jonovono** [comment]
@noirbizarre thanks!

I came across this project that seems to use restplus and achieves it. I tried something similar to theirs but didn't seem to work. But seems they have their own restplus?

https://github.com/frol/flask-restplus-server-example

**Comment by frol** [comment]
@Jonovono I use namespaces to achieve endpoints grouping in https://github.com/frol/flask-restplus-server-example/blob/master/app/modules/users/resources.py#L22.

**Comment by noirbizarre** [comment]
Hi !

I think this issue is resolved since 0.9 has been released so I close it.
