### ISSUE TITLE
Error handlers on namespaces causes error

### ISSUE THREAD

**Issue by 3art** [noirbizarre/flask-restplus#141]
Flask-restplus=0.9.0

When error handlers are registered on a namespace and afterwards are transfered to api an error occurs. I got it working on my side by adding ".items()" on api.py:398:
`for exception, handler in ns.error_handlers.items():`

Due to the lack of time I cannot go through the contribution process myself.

More info:
For example when registering my error handler for a specific exception
```
namespace = Namespace('endpoint')

@namespace.errorhandler(ConflictExceptionClass)
def handle_conflict_exception(error):
...
```
When starting the program you will get:
```...
    api.add_namespace(ns_engine)
  File "/home/bevandeba/tools/python/local/lib/python2.7/site-packages/flask_restplus/api.py", line 398, in add_namespace
    for exception, handler in ns.error_handlers:
TypeError: 'type' object is not iterable
```

This issue is located at
api.py:397-399:
```
        # Register error handlers
        for exception, handler in ns.error_handlers:
            self.error_handlers[exception] = handler
```

Fixed by changing to:
```
        # Register error handlers
        for exception, handler in ns.error_handlers.items():
            self.error_handlers[exception] = handler
```

**Comment by dmulter** [comment]
I've got the same issue, and I've verified the fix above solves the problem.

**Comment by mikechris** [comment]
I can confirm this issue.
With patch ns.error_handlers.items() error handlers in namespaces working fine for me.
