### ISSUE TITLE
Describing arguments in URL path

### ISSUE THREAD

**Issue by postrational** [noirbizarre/flask-restplus#146]
Swagger allows arguments located in the URL path to be described in a similar fashion to query string arguments. I was hoping that I could use the `@api.expect(parser)` decorator to set restrictions on path parameters like so:

```python
parser = reqparse.RequestParser()
parser.add_argument('test', choices=('one', 'two'), location='path')

@api.route('/<test>')
class TestResource(Resource):

    @api.expect(parser, validate=True)
    def get(self):
        args = parser.parse_args(request)
        return args
```

Unfortunately this does not do what I expected, and instead it generates Swagger documentation for 2 `test` arguments, one in the `path` and one in the `query` section.

Am I missing something, is there another way to do this? 
If this is not yet possible, it would be a great additional feature.

**Comment by noirbizarre** [comment]
Sorry for the late response.

`RequestParser` does not handle path parameters, only querystrings, cookies, files...
Path parameters are directly handled by Flask itself (internally by Werkzeug). See theses documentations to add some path parameters validation logic (by creating a custom converter):
- http://flask.pocoo.org/docs/0.10/api/#url-route-registrations
- http://werkzeug.pocoo.org/docs/0.11/routing/

If you want to document the test parameter, you can write:
```python
@api.route('/<test>')
@api.param('test', 'Some description)
class TestResource(Resource):
    def get(self, test):
        pass
```

**Comment by ziirish** [comment]
Well, there is still something wrong here with 0.9.0:

```python
@ns.route('/server-restore/<name>',
          '/<server>/server-restore/<name>',
          methods=['GET'],
          endpoint='is_server_restore')
class ServerRestore(Resource):
    @ns.marshal_with(restoration_fields, code=200, description='Success')
    @ns.doc(
        responses={
            201: 'Success',
            400: 'Missing parameter',
            403: 'Insufficient permissions',
            500: 'Internal failure',
        },
    )
    @ns.param('server', 'Which server to collect data from when in multi-agent mode')
    @ns.param('name', 'Client name')
    def get(self, server=None, name=None):
```

I expect the `server` parameter not to be shown for the `/restore/server-restore/{name}` URL. Besides, why is the `name` parameter shown twice?

![selection_017](https://cloud.githubusercontent.com/assets/449711/14716167/0cc06ed4-07ec-11e6-9483-b332cbb41977.png)

**Comment by noirbizarre** [comment]
To me it's not the same issue. Your case is way more complex (multiple URL in one declaration, `methods` specified...)
Can you open a new issue and provide in addition of what's already provided:
- the full class declaration (is the `methods=['GET']` necessary ?). You can empty the methods but I'll need the signatures and the docstrings
- the generated swagger.json (at least the pathes declaration corresponding to this class)
