### ISSUE TITLE
Add Notice file attributing sources 

### ISSUE THREAD

**Issue by justanr** [noirbizarre/flask-restplus#149]
I was poking through the code base and noticed some very familiar looking code. And compared it to a contribution I made to Flask-Restful.

Compare the representation.py here to flask_restful/representations/json.py.

It's bad form to lift source code whole sale without attribution. While I'm not a core contributor, nor do I claim to speak on Twilio or the Restful team's behalf, it'd be nice too see a NOTICE file stating code has been reproduced in this library.

**Comment by noirbizarre** [comment]
Sorry, I didn't mean to steal some code.
Just so you, I had contacted them to ask if I can merge back their project into mine before doing it. It's not a savage copy-paste.

**Comment by justanr** [comment]
Sorry if it came off as an attack, I just happened to notice it and one of the requirements of the MIT license is to reproduce that notice.

**Comment by noirbizarre** [comment]
Don't worry, no offense taken.
You were right to report it :+1:
