### ISSUE TITLE
Is there any way to have different endpoints serve different default mimetypes ?

### ISSUE THREAD

**Issue by edouardklein** [noirbizarre/flask-restplus#161]
I wish to have a endpoint /img/ that answers a json-serialized list of URI, e.g.
GET /img/ 

/img/one.json
/img/two.json
...

Then, I want of these endpoint to serve a json-serialized dictionary of metadata about the resource, e.g.:

GET /img/one.json

 "events": [
    {
      "fetch_time": "2016-04-20 16:19:33.453926",
      "title": "something"
    }
  ],
  "image_path": "/img/001865c6e29b7cda947e956a15b8012f.jpg",

Finally, I want the image path to answer the JPEG data, (mimetype image/jpeg), not some json.
GET /img/001865c6e29b7cda947e956a15b8012f.jpg

<An actual image/jpeg payload>

I have tried playing with api.representations, but as far as I understand, it works for all endpoints. I have not found a way to specify a per-endpoint default representation.

Because of this, either everything defaults to application/json, and I can't see my JPG in the browser when I try to open the image url, or everything defaults to image/jpeg, and the swagger UI stops working.

Any help would be appreciated/

**Comment by noirbizarre** [comment]
Hi !

There is still some work to do on mime-types and content negociation. Right no, Flask-RESTPlus is primarily design to handle JSON.

But, in you case, I think the problem is trying to serve files from your API. Instead, I advise you to let your reverse proxy serve the file directly. It's way more efficient, you will have cache...

**Comment by edouardklein** [comment]
Thanks for the advice, I'll do that.

**Comment by ziirish** [comment]
Hi,

You can also return a `Flask` `Response` object through the `send_file` method:

```
from flask_restplus import Resource
from flask import send_file

@api.route('/img/<filename>')
class SomeClass(Resource):
    def get(self, filename):
        return send_file(filename, as_attachement=True, attachement_filename=filename, mimetype='image/png')
```

**Comment by edouardklein** [comment]
This works exactly like I wanted it to ! I can now see the image from within the swagger UI :) !

Thank you very much. 

P.S. for future readers, s/attachement/attachment/g in ziirish's code.

**Comment by ziirish** [comment]
Thanks, I edited my answer accordingly to fix the typo ;)

**Comment by dis123456789** [comment]
Hi,
is it possible to return both a json and an image?
In my case the user uploads an image, and the system should reply with a json and the uploaded image?

For now I have defined the string fields of the json, but I don't know how to return the image.

from flask_restplus import fields
resource_fields = api.model('Resource', {
    'field1': fields.String,
    'field2': fields.String,
    'field3': fields.String,
})

Thanks
