### ISSUE TITLE
Embedded Swagger UI + restful prefix = 404 Not Found

### ISSUE THREAD

**Issue by sduthil** [noirbizarre/flask-restplus#17]
Given I have a flask_restful Api with ```prefix='1.0/'```
Given I have a flask_restplus route under ```1.0/test```
When I do a ```GET /1.0/test``` from the embedded Swagger UI (which is under ```/```, instead of ```/1.0```)
Then the Swagger UI does a ```GET /test/``` and Flask answers ```404 Not Found```

There's a bit of code reproducing the issue here : https://gist.github.com/sduthil/74cf23da60c761f082bd

Tested with flask_restful 0.3.1 and flask_restplus 0.4.0.
This feature worked with flask_restful 0.2.12 and flask_restplus 0.2.4.

Any idea where this comes from ?

**Comment by noirbizarre** [comment]
Hi !

Sorry for the late response.

In version 0.4, I tried to stick as close as possible to flask-restful (mainly to ease the upgrades).
So prefix has been removed in flavor of standard blueprint usage (see exemple in #6 ).

In your case, you should write:
```python
blueprint = Blueprint('api', __name__, url_prefix='/1.0')
api = Api(blueprint)
app.register_blueprint(blueprint)
```
You can now register and call your endpoint like that:
```python
@api.route('/test', endpoint='endpoint')
class MyEndpoint(Resource):
    def get(self):
          return {}

url_for('api.endpoint')
>> http://localhost:5000/1.0/test
```

The doc has been upgraded. Sorry for the inconveniance.
