### ISSUE TITLE
Input payload verification of a custom field

### ISSUE THREAD

**Issue by aviaryan** [noirbizarre/flask-restplus#176]
I have created a custom field called `EmailField`. Also I am validating the input payload with api.expect . 
It looks to me that restplus validates the fields only by their data types. Is there away to run a method (eg validate()) for a custom field at input payload verification.

In resource -> validate_payload, I see the comment "# TODO: handle third party handlers" which suggests that this may not be supported. But I am in urgent need of this feature so asked this anyway. 

I can always create a custom function to validate the payload and call it at the start of each `post` method to do the job.

**Comment by noirbizarre** [comment]
Fixed by #178
