### ISSUE TITLE
Issue using fields.List

### ISSUE THREAD

**Issue by ascripka** [noirbizarre/flask-restplus#18]
I am having trouble understanding how to use fields.List in the context of a model. I am trying to create a model that is a list of objects. Each of those objects contains a field that is also a list. For example:

    [ {'name': 'some_name',
       'pets': ['cat','dog]
      },
     {'name': 'some_other_name',
      'pets': ['fish', 'chicken', 'dog']
     } ]

When I try to create a list using api.model, like so:

    mymodel = api.model('myModel', {
            'name': fields.String(description='name'),
            'pets': fields.List(description='pets', required=True),
        })

I get the following traceback:

Traceback (most recent call last):
File "/somefile.py", line 120, in Options
     'pets': fields.List(description='pets', required=True),
File "/usr/local/lib/python2.7/dist-packages/flask_restplus/fields.py", line 16, in __init__
    super(DetailsMixin, self).__init__(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/flask_restplus/fields.py", line 10, in __init__
    super(DescriptionMixin, self).__init__(*args, **kwargs)
TypeError: __init__() takes exactly 2 arguments (1 given)

Please advise.

**Comment by noirbizarre** [comment]
Hi !

The List field expect the inner field type as parameter:
```python
mymodel = api.model('myModel', {
    'name': fields.String(description='name'),
    'pets': fields.List(fields.String, description='pets', required=True),
})
```

**Comment by ascripka** [comment]
Hi there,

Thanks for the explanation. Could you also show me how to create a list of
custom Objects? My POST request sends a list of Objects, not contained
within an outer Object. For example:

**Comment by ascripka** [comment]
Hi there,

Thanks for the explanation. Could you also show me how to create a list of
custom Objects? My POST request sends a list of Objects, not contained
within an outer Object. For example:

[ {'name': 'some_name',
   'pets': ['cat','dog]
  },
 {'name': 'some_other_name',
  'pets': ['fish', 'chicken', 'dog']
 } ]

Thanks!

**Comment by emilecaron** [comment]
Having the same issue here. Is there any way to do this ?

**Comment by noirbizarre** [comment]
I added the @api.expect() decorator as a shortcut for @api.doc(body=).
Both supports specifying a type wrapped in an array.

In your case, you can write:
```python
@api.route('/somewhere')
class MyAPI(Resource):
    @api.expect([mymodel])
    def post(self):
        pass
```
or
In your case, you can write:
```python
@api.route('/somewhere')
class MyAPI(Resource):
    @api.doc(body=[mymodel])
    def post(self):
        pass
```

**Comment by emilecaron** [comment]
The problem in my case is that the list isn't at the top level. I have something like that:
````
{ 
    'data': { 
        'dimensions': [ 
            { 'foo': 1 },
            { 'foo': 2 }
        ]
    }
}
```

**Comment by limbosongs** [comment]
Hello, was this ever resolved? I also need to create a model with similar to 

`{ 
    'data': { 
        'dimensions': [1, 2, 3, 4]
    }
}`

Thanks for any help!

**Comment by EmanueleLillo** [comment]
```python```

**Comment by clarkhillm** [comment]
@emilecaron you can use  Nested with List :

> 
user_fields = api.model('User', {
    'id': fields.Integer,
    'name': fields.String,
})

user_list_fields = api.model('UserList', {
    'users': fields.List(fields.Nested(user_fields)),
})

**Comment by zannkukai** [comment]
Hello,
I used these models :
```python
modification_rule = api.model(u'ModificationRule', {
    'method': fields.String(num=['replace', 'add', 'delete'], required=True),
    'xpath': fields.String(required=True),
    'value': fields.String(description='the value to add/modify')
})
namespaces = api.model(u'Namespace', {
    'prefix': fields.String(example="marc", required=True),
    'uri': fields.String(required=True)
})
modification_rules = api.model(u'ModicationRules', {
    'actions': fields.List(
        fields.Nested(modification_rule, description="actions to apply on the object"),
        min_items=1,
        required=True
    ),
    'namespaces': fields.List(
        fields.Nested(namespaces, description="additional namespaces required to parse data"),
    )
})
```
An example of the expected JSON payload data :
```json
{
  "namespaces": [{"prefix": "marc", "uri": "http://www.loc.gov/MARC21/slim" }],
  "actions": [
    { "xpath": "//marc:record/marc:datafield[@tag='973']/marc:subfield[@code='a']",
      "method": "replace",
      "value": "string"
    }
  ]
}
```

Finaly I use this resource 

```python
@api.route('/somewhere')
class Objects(Resource):
    @api.doc(modification_rules)
    def post(self):
        data = api.payload
```  

Despite iI set "required" and "min_items=1" params for "actions", no payload validation exception raised if I send a POST request with no "actions" part in JSON nor with an empty "actions" list :'(
Did I miss something ?

**Comment by brunlid** [comment]
Hi,

How would one write a model for accepting Mixed-Type Arrays as shown in this example https://swagger.io/docs/specification/data-models/data-types/#array

Thanks!

**Comment by mjschock** [comment]
> Hi,
> 
> How would one write a model for accepting Mixed-Type Arrays as shown in this example https://swagger.io/docs/specification/data-models/data-types/#array
> 
> Thanks!

https://stackoverflow.com/a/49809282/3026801

**Comment by SwethaPrem25** [comment]
Hi,

I need a model for the below - 

"retention_period": {
                "anyOf": [
                    {"type": "number"},
                    {"type": "string"}
                ]
            }
Thanks for any help!
