### ISSUE TITLE
templates/swagger-ui-libs.html includes incorrect javascript file for handlebars

### ISSUE THREAD

**Issue by croshchupkin** [noirbizarre/flask-restplus#19]
First, I want to say that I have only a vague understanding of how the javascript dependencies are installed for restplus, so right now I can't say why this is happening.
But.
In my virtualenv, in lib/python2.7/site-packages/flask_restplus/static/bower/swagger-ui/dist/lib directory, there's the handlebars-2.0.0.js file, while swagger-ui-libs.html tries to include handlebars-1.0.0.js.

**Comment by croshchupkin** [comment]
Also, I tried overloading the template with my own that includes the correct JS file. Now I get a javascript error in Firebug: "ReferenceError: marked is not defined" for swagger-ui.js (line 370, col 13).
The line itself is:
return $(this).html(marked($(this).html()));

**Comment by mdesetty** [comment]
I have a fix and planning to submit a pull request. Here is the fix if you need it. It solved the issues for me

In swagger-ui-libs.html 
swagger-ui-libs.html under Virtual env \env\Lib\site-packages\flask_restplus\templates\swagger-ui-libs.html

1. Change handlebars-1 to handlebars-2:
<script src="{{ swagger_static('lib/handlebars-1.0.0.js') }}" type="text/javascript"></script>
to 
<script src="{{ swagger_static('lib/handlebars-2.0.0.js') }}" type="text/javascript"></script>

2. and Add 
<script src="{{ swagger_static('lib/marked.js') }}" type="text/javascript"></script>
at end to the swagger-ui-libs.html. 

That should fix it.

**Comment by croshchupkin** [comment]
yes, I changed the handlebar version in my custom template. As for marked, it seems that the Swagger UI for my REST API is still generated even without it.

**Comment by mdesetty** [comment]
You have to manually add it into your virtual env for now. I submitted a pull request and once its merged the Swagger UI for your REST API will get it when you create a new virtualenv. Until then you have to change the template manually in your virtualenv.

**Comment by noirbizarre** [comment]
Fixed by #20

**Comment by mdesetty** [comment]
Any timeline when the flask-restfplus package (probably a new version 0.4.3?) will be published to PyPi so that when pip is used it will install these changes from the PyPI?

**Comment by croshchupkin** [comment]
+1
I also think it would be great if this fix was tagged with a new version to make referencing it in requirements.txt easier.

**Comment by ldgeo** [comment]
:+1:
