### ISSUE TITLE
AttributeError: Api does not have __schema__ attribute

### ISSUE THREAD

**Issue by 984958198** [noirbizarre/flask-restplus#194]
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

Flask (0.11.1)
flask-restplus (0.9.2)
Flask-Script (2.0.5)

[2016-08-17 15:07:57,503] ERROR in app: Exception on /mailang/api/v1/swagger.json [GET]
Traceback (most recent call last):
  File "E:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Python27\lib\site-packages\flask_restplus\api.py", line 310, in wrapper
    resp = resource(_args, *_kwargs)
  File "E:\Python27\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "E:\Python27\lib\site-packages\flask_restplus\resource.py", line 44, in dispatch_request
    resp = meth(_args, *_kwargs)
  File "E:\Python27\lib\site-packages\flask_restplus\api.py", line 751, in get
    return self.api.**schema**
  File "E:\Python27\lib\site-packages\flask_restplus\api.py", line 206, in **getattr**
    raise AttributeError('Api does not have {0} attribute'.format(name))
AttributeError: Api does not have **schema** attribute
127.0.0.1 - - [17/Aug/2016 15:07:57] "GET /mailang/api/v1/swagger.json HTTP/1.1" 500 -

**Comment by matveevtam** [comment]
Hi, @noirbizarre !
I have hit this issue yesterday and have some feedback.
The above exception occurs when I try to use a complex model with `@marshal_with()` decorator using a namespace.
This is how I reproduce it.
I took one of your examples `examples/todo/complex.py` with the module `examples/todo/zoo` and modified the file `examples/todo/zoo/cat.py`, lines 5-12:

```
cat = Model('Cat', {
    'id': fields.String(required=True, description='The cat identifier'),
    'name': fields.String(required=True, description='The cat name'),
    'colors': {
        'head': fields.String(),
        'body': fields.String(),
        'paws': fields.String()
    }
})
api.add_model('Cat', cat)

CATS = [
    {'id': 'felix', 'name': 'Felix', 'head': 'red', 'body': 'black', 'paws': 'white'},
]
```

I added a complex field `colors` just like in your docs: http://flask-restplus.readthedocs.io/en/stable/marshalling.html#complex-structures
Then I run the example. Requests to the `/cats/` resource work as expected, and return
```
[
    {
        "colors": {
            "body": "black",
            "head": "red",
            "paws": "white"
        },
        "id": "felix",
        "name": "Felix"
    }
]
```
But when I try to access swagger.json, I receive the following error:
```
--------------------------------------------------------------------------------
ERROR in app [/usr/local/lib/python3.5/dist-packages/flask/app.py:1587]:
Exception on /swagger.json [GET]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/api.py", line 203, in __getattr__
    return getattr(self.default_namespace, name)
AttributeError: 'Namespace' object has no attribute '__schema__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/api.py", line 309, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/api.py", line 750, in get
    return self.api.__schema__
  File "/usr/local/lib/python3.5/dist-packages/flask_restplus/api.py", line 205, in __getattr__
    raise AttributeError('Api does not have {0} attribute'.format(name))
AttributeError: Api does not have __schema__ attribute
127.0.0.1 - - [18/Nov/2016 14:08:53] "GET /swagger.json HTTP/1.1" 500 -
```
It reproduces with python 2.7, 3.4 and 3.5, here is my `pip freeze` output in python-3.4 environment (excluded some secret corporative packages):
```
alembic==0.8.8
aniso8601==1.2.0
click==6.6
Flask==0.11.1
Flask-Admin==1.4.2
Flask-Migrate==2.0.0
flask-restplus==0.9.2
Flask-Script==2.0.5
Flask-SQLAlchemy==2.1
itsdangerous==0.24
Jinja2==2.8
jsonschema==2.5.1
Mako==1.0.4
MarkupSafe==0.23
promise==0.4.2
psycopg2==2.6.2
py==1.4.31
pytest==3.0.2
pytest-flask==0.10.0
python-dateutil==2.6.0
python-editor==1.0.1
pytz==2016.7
six==1.10.0
SQLAlchemy==1.0.15
uWSGI==2.0.13.1
Werkzeug==0.11.11
WTForms==2.1
```
Everything works fine if I don't use `@marshal_with` or a complex model.

**Comment by 984958198** [comment]
Thank you, I have found the problem

`Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win32`
`@api.route('/config')
class SettingResource(Resource):
    def get(self):
        pass`
to
`@api.route('/config')
class SettingResource(Resource):
    def get(self):
        '''

        '''
        pass`

**Comment by matveevtam** [comment]
This does not work for me, I already have docstrings for all methods

**Comment by 984958198** [comment]
Sorry, English is not good, I mean must be defined within the get empty instructions (' ' ' ' ' ') is not an error

**Comment by cailro** [comment]
Hi! I have the same issue with complex model.

**Comment by zhensun** [comment]
Hi, I got the same error with complex model.

**Comment by liiight** [comment]
experiencing this too after upgrading to 0.10.0. Anyone having any progress with this?

**Comment by googley** [comment]
Same problem in 0.9.2

**Comment by atulatri** [comment]
+1

**Comment by matthewhopkins** [comment]
+1

**Comment by noirbizarre** [comment]
The `AttributeError` exception is hiding the real error so each time it can be a different issue.
This won't be the case anymore and you will be able to either fix it if this is possible or report the real issue if necessary.

**Comment by vvasuki** [comment]
I have the same problem - how do I install 0.11?
A pip upgrade only yielded:
```
pip2 show flask_restplus | grep Vers
Version: 0.10.1
```

**Comment by liiight** [comment]
You can try to install from git:
`pip install git+https://github.com/noirbizarre/flask-restplus@master`

when i do this though my swagger view does not load up at all though, not even crashes

**Comment by vvasuki** [comment]
When I try `pip install git+https://github.com/noirbizarre/flask-restplus@master`:  I don't see 0.11 being installed at all:

```
Installing collected packages: flask-restplus
  Found existing installation: flask-restplus 0.10.1
    Uninstalling flask-restplus-0.10.1:
      Successfully uninstalled flask-restplus-0.10.1
  Running setup.py install for flask-restplus ... done
Successfully installed flask-restplus-0.10.1.dev0
```

**Comment by liiight** [comment]
That's because there is no 0.11 yet, it doesn't exist. 
That will let you pull everything in master though, which is what you want. 

Also I was wrong about the crash, it reproduced and the error wasn't swallowed this time as expected, so I can confirm this worked for me

**Comment by vvasuki** [comment]
> when i do this though my swagger view does not load up at all though, not even crashes

Ah - now I too see this behavior! Observe the difference with no code change - 

With the github db version:
```
INFO: 2017-06-01 13:26:31,611 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery-1.8.0.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,613 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/css/typography.css HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,615 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/css/reset.css HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,616 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/css/screen.css HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,618 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/object-assign-pollyfill.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,620 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.slideto.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,621 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.wiggle.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,623 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.ba-bbq.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,624 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/handlebars-4.0.5.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,626 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/lodash.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,627 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/backbone-min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,628 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/swagger-ui.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,630 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/highlight.9.1.0.pack.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,633 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/highlight.9.1.0.pack_extended.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,634 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/jsoneditor.min.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,635 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/marked.js HTTP/1.1" 404 - 
INFO: 2017-06-01 13:26:31,637 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:26:31] "GET /swaggerui/bower/swagger-ui/dist/lib/swagger-oauth.js HTTP/1.1" 404 - 
```

With the prior default version:
```
INFO: 2017-06-01 13:29:15,492 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/css/typography.css HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,494 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/css/reset.css HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,495 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/css/screen.css HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,497 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/highlight.9.1.0.pack.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,499 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/object-assign-pollyfill.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,501 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery-1.8.0.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,502 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.slideto.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,534 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.wiggle.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,538 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/jquery.ba-bbq.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,539 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/handlebars-4.0.5.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,541 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/lodash.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,542 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/backbone-min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,544 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/swagger-ui.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,599 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/highlight.9.1.0.pack_extended.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,600 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/jsoneditor.min.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,606 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/marked.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,608 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/lib/swagger-oauth.js HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:15,929 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:15] "GET /swaggerui/bower/swagger-ui/dist/fonts/DroidSans.ttf HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:16,023 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:16] "GET /textract/swagger.json HTTP/1.1" 200 - 
INFO: 2017-06-01 13:29:16,397 {_internal.py:87}: 127.0.0.1 - - [01/Jun/2017 13:29:16] "GET /swaggerui/bower/swagger-ui/dist/fonts/DroidSans-Bold.ttf HTTP/1.1" 200 - 
```

**Comment by vcolano** [comment]
+1 on Flask 0.12, what's the status on this?

**Comment by mhong19414** [comment]
Still doesn't work with models like this:

`cat = Model('Cat', {
    'id': fields.String(required=True, description='The cat identifier'),
    'name': fields.String(required=True, description='The cat name'),
    'colors': {
        'head': fields.String(),
        'body': fields.String(),
        'paws': fields.String()
    }
})`

Installed `pip install git+https://github.com/noirbizarre/flask-restplus@master`, getting a new error:

500 : { "error": "Unable to render schema" } http://localhost:5000/api/swagger.json

**Comment by elipavlov** [comment]
Had same problem.

Take a close look at your models, if one of provided dict values is not a fields.Raw child class, then exception will raised.

In my case (0.10.1) exception was raised in flask_restplus/swagger.py:465:
```python
# ...

    def serialize_definitions(self):
        return dict(
            (name, model.__schema__)
            for name, model in iteritems(self._registered_models)
        )
```

One of my model raised exception when model._schema() was called on attempt to access model.__schema__.

My wrong model:
```python
Message = Model('Message', {
    'message': fields.String(required=True, description='Message of response')
}, desciption='qweqwe')
```
Model's KW attribute **description** was interpreted as model field, because of Model is a child class of _dict_, and this behaviour is a part of _dict_ constructor behaviour.

**Comment by dokzlo13** [comment]
Same thing with 0.10.1

**Comment by elipavlov** [comment]
@goodloop, i think your problem in `desciption` argument, which you try to provide into model constructor, because model wait that all arguments it is a Field subclasses. Top level model can't have description or any other arguments excluding Fields subclasses. However, duplicated model names can cause error too.

@dokzlo13, typically this error occurring when one or more models has error in theirs definition.

**Comment by goodloop** [comment]
@elipavlov the problem I faced  is **duplicated model names**.

**Comment by Raghu-Kanchiraju** [comment]
I ran into the same problem. I resolved it by using *marshal* instead of *marshal_with*. (pip install git....master did not work for me because of missing assets).

**Comment by rohitcmu** [comment]
I was able to solve this problem by using **marshal_list_with** vs **marshal_with** and using **{schema: fields.Nested(another_schema)}** vs **{schema: another_schema}**
