### ISSUE TITLE
AWS API gateway integration using x-amazon-apigateway-integration

### ISSUE THREAD

**Issue by bedge** [noirbizarre/flask-restplus#202]
Not sure if this is a bug, missing feature, or simply a lack of understanding ion my part.
Amazon API GW docs state that one can specify 

> Specifies details of the back-end integration used for this method. This extension is an extended property of the Swagger Operation object. The result is an API Gateway integration object. 

AWS docs here: http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html#api-gateway-swagger-extensions-integration

which refers to the swagger spec here:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject

Anyone have any examples of how to setup the AWS API Gateway integrations using flask_restplus?

**Comment by noirbizarre** [comment]
I don't have an example as I don't use Amazon API gateway but this is a vendor extension, they are now supported and will be released into the next 0.11 version

**Comment by noirbizarre** [comment]
I close this issue as fixed by bd9ca08cd0c7585a47792997d25b13095ca16949
