### ISSUE TITLE
Cannot add additional documentation to method using namespace.doc

### ISSUE THREAD

**Issue by dusktreader** [noirbizarre/flask-restplus#215]
The documentation for the namespace.doc() method is really lacking. It would be helpful to have some example of how it is intended to be used. Perhaps, it is not suited to providing the functionality I'm trying to get out of it.

I am overriding a post method inherited from a common base. I would like to add a sentense of documentation. The base class method has a docstring that is presented in the swagger UI. I would like to add on to that for the base class.

Unfortunately, just calling namespace.doc does nothing. Here is what I'm trying to do:

```
class GenericResource(Resource):

    def post(self):
        """
        Handles POST request

        Creates a new instance from the supplied json payload of the request.
        """
        pass # implementation removed

users_ns = api.namespace('users', description='User operations', path='/api/users')
@users_ns.route('', endpoint='users_generic')
class UserGenericResource(GenericResource):
    @users_ns.expect(users_api_model)
    @users_ns.response(201, 'Object successfully created.')
    @users_ns.doc("A password may be supplied at this endpoint. It will be hashed")
    def post(self):
        return super().post()
```

Unfortunately, this doesn't work at all. Is there a way to do this correctly? I found a way to monkey patch things more or less to get what I want:

```
@users_ns.route('', endpoint='users_generic')
class UserGenericResource(GenericResource):
    @users_ns.expect(users_api_model)
    @users_ns.response(201, 'Object successfully created.')
    @users_ns.doc("A password may be supplied at this endpoint. It will be hashed")
    def post(self):
        return super().post()
    post.__doc__ = GenericResource.post.__doc__ + "A password may be supplied at this endpoint. It will be hashed"
```

However, this is less than satisfactory.

Thanks

**Comment by aqisnotliquid** [comment]
I've been able to do this with the following:

`@users_ns.doc(description="A password may be supplied at this endpoint. It will be hashed")`

It appears at the top of the endpoint in SwaggerUI with the title "Implementation Notes".

**Comment by noirbizarre** [comment]
Yes, the `doc` decorator is a generic one and you can set the description field (and yes thay appears as "Implementation notes" into swagger UI.
You can also simply override the docstring in your child class.

The `doc` signature is `doc('swagger-operation-identifier', **kwargs) but most of the time you can use dedicated decorator so a classic API endpoint will look like:
```python
@users_ns.route('', endpoint='users_generic')
class UserGenericResource(GenericResource):
    @users_ns.doc('create_user')
    @users_ns.expect(users_api_model)
    @users_ns.response(201, 'Object successfully created.')
    def post(self):
        '''A password may be supplied at this endpoint. It will be hashed'''
        return super().post()
```
