### ISSUE TITLE
Exception is raised when init_app() is called more than once

### ISSUE THREAD

**Issue by croshchupkin** [noirbizarre/flask-restplus#22]
The culprit is this line of code in init_app():
```
self.add_resource(self.swagger_view(), '/swagger.json', endpoint='specs', doc=False)
```
The self.swagger_view() method returns a new class each time. And, because of that, the code in the following if-block gets executed: https://github.com/flask-restful/flask-restful/blob/0.3.1/flask_restful/__init__.py#L391

This is very inconvenient for me, as because of this issue I can't create more than one class for my functional tests: for each such class, I must call my application factory, which, in turn, imports my Api instance and calls init_app() on it.

The fastest solution that I see right now is to just make the addition of the specs optional via a new kwarg. I can create a pull request for this.

**Comment by croshchupkin** [comment]
I've added 2 tests for the new feature to the pull request.

**Comment by noirbizarre** [comment]
Fixed by #23

**Comment by croshchupkin** [comment]
Could you please create a new version that contains these changes?

**Comment by noirbizarre** [comment]
I will very soon. (Today or tomorrow)
