### ISSUE TITLE
Validation in expect does not work for lists

### ISSUE THREAD

**Issue by tzabal** [noirbizarre/flask-restplus#230]
*Flask-RESTPlus Version: 0.9.2*

The `Namespace.expect` method which acts as a decorator, provides validation [[1]](http://flask-restplus.readthedocs.io/en/0.9.2/swagger.html#the-api-expect-decorator). However validation does not work when the expected input is a list (JSON array for input payload) instead of a dictionary (JSON object for input payload).

For example, consider the following minimal Flask application:

```python
from flask import Flask
from flask_restplus import Api, Resource, fields

app = Flask(__name__)
api = Api(app)

user = api.model('User', {
    'username': fields.String(required=True),
    'password': fields.String(required=True)
})

@api.route('/users')
class Users(Resource):
    @api.expect([user], validate=True)
    def post(self):
        return

if __name__ == '__main__':
    app.run()
```
If we perform the following request with `curl`:
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '[
  {
    "username": 1,
    "password": "string"
  }
]' 'http://127.0.0.1:5000/users'
```

It goes through without an input validation error.

**Comment by noirbizarre** [comment]
Fixed by #231
