### ISSUE TITLE
Swagger document cascading causes duplicate parameters

### ISSUE THREAD

**Issue by john-bodley** [noirbizarre/flask-restplus#234]
According to the documentation, cascading of documentation is supported, http://flask-restplus.readthedocs.io/en/stable/swagger.html#cascading, however when applying this logic, 

```python
from flask import Flask
from flask_restplus import Api, Resource


app = Flask(__name__)
api = Api(app)


@api.route('/my-resource/<id>')
@api.param('id', 'Class-wide description')
class MyResource(Resource):
    @api.param('id', 'An ID')
    def get(self, id):
        return id


if __name__ == '__main__':
    app.run(debug=True)

```

the `id` parameter is duplicated (see attachment). 

![screen shot 2017-02-06 at 9 43 44 am](https://cloud.githubusercontent.com/assets/4567245/22658979/d9c010c6-ec50-11e6-887f-375f46ed937c.png)

Note this may be related to the following issues: https://github.com/noirbizarre/flask-restplus/issues/164, https://github.com/noirbizarre/flask-restplus/issues/146

**Comment by johnbodley** [comment]
Note I also noticed that duplicate parameters existed even without cascading. I'm uncertain whether this is a bug or merely an issue with my configuration.

**Comment by maxkoryukov** [comment]
Bug still there :broken_heart: 

Flask:
Flask RESTPlus:

namespace:

```python
# -*- coding: utf-8 -*-

from flask import request
from flask import send_file
from flask_restplus import Resource
from flask_restplus import Namespace
examples_ns = Namespace(
	'examples',
	path='/examples',
	description='Miscellaneous examples'
)
@examples_ns.route('/account-file/<fm>/')
class AccountFileResource(Resource):
	@examples_ns.response(200, 'Success')
	@examples_ns.param('fm', 'asdf')
	def get(self, fm=None):
		"""
		Returns an example of the account-file

		_Returns an example_ of the `account-file` used for bulk-registering new accounts
		"""

		return 'hello'
```

In swagger:

![flask_rest_params](https://user-images.githubusercontent.com/8887971/29048728-924b34ac-7beb-11e7-80f7-77ddcfbf8aaf.jpg)

**Comment by maxkoryukov** [comment]
Sorry, in my case it was easy to fix:

```python
# -*- coding: utf-8 -*-

from flask import request
from flask import send_file
from flask_restplus import Resource
from flask_restplus import Namespace
examples_ns = Namespace(
	'examples',
	path='/examples',
	description='Miscellaneous examples'
)
@examples_ns.route('/account-file/<fm>/')
@examples_ns.param('fm', 'asdf')
class AccountFileResource(Resource):
	@examples_ns.response(200, 'Success')
	def get(self, fm=None):
		"""
		Returns an example of the account-file

		_Returns an example_ of the `account-file` used for bulk-registering new accounts
		"""

		return 'hello'
```

**In two words**: I have moved `@examples_ns.param('fm', 'asdf')` from `method` to `class` definition (and it is logical  and intuitively clear _but not for me tonight thougth..._ :man_facepalming: )

**Comment by aparamon** [comment]
Reproducible on official example
https://github.com/noirbizarre/flask-restplus/blob/master/examples/xml_representation.py

**Comment by JorgeRaimundo** [comment]
@maxkoryukov, that was, in fact, my first development approach.
But then, when I tried to import the `swagger.json` into the AWS API Gateway, I noticed that the `param` must be defined above the method declaration, therefore I really have to put it above the "`get`" method (if I consider the example you provided).
This causes the duplicate parameter on the documentation as stated above...
