### ISSUE TITLE
Erro in new version flask_restplus-0.10.0

### ISSUE THREAD

**Issue by rafsAcorsi** [noirbizarre/flask-restplus#236]
Try to import in new version 0.10.0 using python 3.5

`from flask_restplus import *`

`AttributeError: module 'flask_restplus' has no attribute 'SchemaModelabort'`

**Comment by AAorris** [comment]
I've submitted a quick PR that adds the missing comma between `SchemaModel` and `abort` if that helps at all.

**Comment by ziirish** [comment]
@noirbizarre can we have a 0.10.1 anytime soon?

This is kind of critical IMHO
