### ISSUE TITLE
fields.Nested failure?

### ISSUE THREAD

**Issue by jbakermk** [noirbizarre/flask-restplus#254]
Please consider:

```
    @api.expect(api.model('Register client', {
        'data': fields.Nested({
            'name': fields.String(required= True),
            'value': fields.String(required= True)
        })      
    }))
```

When I start the Flask service and access the Swagger doc,  I see this error:

  File "/flask_restplus-0.10.1-py2.7.egg/flask_restplus/swagger.py", line 470, in register_field
    self.register_model(field.nested)
  File "flask_restplus-0.10.1-py2.7.egg/flask_restplus/swagger.py", line 453, in register_model
    if name not in self.api.models:
TypeError: unhashable type: 'dict'

I think the error may be that register_model is called to register a nested field, and that appears to want a complete model not an instance of Nested.

Any thoughts? Thanks

**Comment by j-m-baker** [comment]
https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/swagger.py

Line 508. 


        elif isinstance(field, fields.Nested):
            self.register_model(field.nested)

Is that correct? Doesn't seem to be.

**Comment by jbakermk** [comment]
I've figured it out. fields.Nested requires a model, not a dictionary of values (as I've seen in the documentation), ie.

```
        'data': fields.Nested(api.model('blah', {
            'name': fields.String(required= True),
            'value': fields.String(required= True)
        }))      
```

I'm not convinced that is a great solution. It should probably allow both a model and a dictionary.

**Comment by dylandee** [comment]
jbakermk is right, it is okay to use  fields.Nested with a model.
