### ISSUE TITLE
upgrade swagger to 3.0

### ISSUE THREAD

**Issue by tkisme** [noirbizarre/flask-restplus#267]
https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html
need a little fix on css

![image](https://cloud.githubusercontent.com/assets/5886048/24454857/0e27b3fe-14c0-11e7-867c-525609791bfb.png)

**Comment by frol** [comment]
I have succeeded in getting Swagger UI 3.0.18 running on my [flask-restplus-server-example](https://github.com/frol/flask-restplus-server-example) using the official [NPM package (swagger-ui-dist)](https://www.npmjs.com/package/swagger-ui-dist) as a source of JS and CSS bundles and index.html. It was quite straightforward to get it working, however, the ["Known Issues"](https://github.com/swagger-api/swagger-ui#known-issues) section makes me think that it might be too early to jump on 3.x just yet:

> To help with the migration, here are the currently known issues with 3.X. This list will update regularly, and will not include features that were not implemented in previous versions.
> 
> * Only part of the parameters previously supported are available.
> * The JSON Form Editor is not implemented.
> * Shebang URL support for operations is missing.
> * Support for collectionFormat is partial.
> * l10n (translations) is not implemented.
> * Relative path support for external files is not implemented.

**Comment by dhofstetter** [comment]
Is there some progress in this topic or are the plans gone?

BR Daniel
