### ISSUE TITLE
Support for python 2.6 is needed

### ISSUE THREAD

**Issue by croshchupkin** [noirbizarre/flask-restplus#27]
It turns out that I need python 2.6 support for the project I'm working on. It seems that not too many changes are needed for this, so I will create a pull request shortly.

**Comment by croshchupkin** [comment]
Unfortunately, I don't know how to change the relevant configuration for Travis and tox. Could you help me out with that, please?

**Comment by noirbizarre** [comment]
Closed by #28

**Comment by croshchupkin** [comment]
Thanks. Please note that for py26, you'll need ordereddict and unittest2 dependencies for tests to run correctly.

**Comment by noirbizarre** [comment]
Yes, it's already taken in account.
ordereddict is needed as an install requirement.
