### ISSUE TITLE
get REST specification via GET request

### ISSUE THREAD

**Issue by andreassteffen** [noirbizarre/flask-restplus#270]
HI,
i need to get the information what parameters and the types thereof a given get method accepts. Can I get that information via a get request? Does flask-restplus provide functionality?
Many thanks, A

**Comment by postrational** [comment]
If you go to your Flask-RESTPlus generated API's Swagger UI docs, you can type in `swagger.json` at the end of the URL to get the [OpenAPI specification](https://github.com/OAI/OpenAPI-Specification) of your API.

For example, if your swagger UI is at `http://localhost:8888/api/`, go to `http://localhost:8888/api/swagger.json`

**Comment by andreassteffen** [comment]
great. that worx!!!
