### ISSUE TITLE
[RFC] marshal_with - filtering out non-required fields?

### ISSUE THREAD

**Issue by radoslawroszkowiak** [noirbizarre/flask-restplus#290]
Hi all,
I've just started trying out this package (and I really like it - kudos!), but there are two things that I stumble upon when using `marshal_with` decorator.

**I wonder if there is a way to do the following**:
1. Filter out any non-required fields if they are missing in the marshal input data (instead of showing null values).
2. Raise `MarshallingError` (or any other) when required field is missing in the response data.

**Rationale and use cases**:

Ad 1: Sometimes there's a lot of optional response fields in the API and it simply makes the reponse unnecessarily big (and subjectively ugly) by displaying "nulls".
Ad 2: It might happen that once upon a time, due to some issue, external source data missing fields, etc - the end user might get the response and the issue will be completely silent.

Both of those cases are handled very well by i.e. Django Rest Framework serializers. It skips non-existing fields (as long as they are not required) and it raises an exception otherwise. I think it's a pretty intuitive and common pattern. Besides, the `required` parameter of the model fields is a bit misleading in this case as it does not do anything while serializing the response (and i.e. I use those models mainly to serialize the responses...)

Anyway, would you consider accepting small PR for the
**potential solution**?:
1. Introduce `check_required` and `skip_missing` parameters to `marshal_with` and `marshal_list_with` decorators.
2. Skip non-required fields when they are missing in the data when `skip_missing` is true.
3. Raise exception when required field is missing and when `check_required` is true.

Not to break any backwards compatibility the defaults would be `check_required=False` and `skip_missing=False`.

It looks to me that implementing call to some fields filtering function right after applying the masks here https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/marshalling.py#L50 would be relatively straightforward and convenient. Unfortunately, I don't know this package very well yet, so there might be better ways to go (without deep refactoring).

Thanks for your thoughts and the feedback.

**Comment by franfabrizio** [comment]
I saw that you just closed this without comment.  Wanted to mention for you and others that might come across this that I recently had the need to skip null values, and learned that the development version of flask-restplus (0.10.1dev0) introduces the skip_none flag.

**Comment by radoslawroszkowiak** [comment]
Thanks, indeed. You're right, I missed that option, but that's just one of the things I had liked to have. The priority for me was raising the error on missing required fields. Anyway, since I switched to flask-restful + flask-apispec, it's unlikely that I'll do anything about the topic of this issue, hence closing. Cheers.

**Comment by andilabs** [comment]
@franfabrizio already on `flask-restplus==0.13.0` and using of `skip_none` seems to have no effect.
https://flask-restplus.readthedocs.io/en/stable/marshalling.html#skip-fields-which-value-is-none
at leas for polymorph... `fields.Polymorph(mapping, skip_none=True)` but this should work, because Polymorph overrides Nested (for which according to docs it should work... https://flask-restplus.readthedocs.io/en/stable/marshalling.html#skip-none-in-nested-fields)

**Comment by franfabrizio** [comment]
Yeah, I have no idea if the developer ever further addressed the skip_none issue, but in any case, this project appears to be deprecated. According to its README, you should use https://github.com/python-restx/flask-restx instead. Hope that helps!
