### ISSUE TITLE
Swagger UI cannot display NaN for my specified float output

### ISSUE THREAD

**Issue by kuo000** [noirbizarre/flask-restplus#304]
I use `api.model` and the decorator `marshal_with` to define the JSON output structure for a POST method. The output contains floats, but Swagger UI has problems displaying the values if the values contain `nan`. The code below gives a minimal example for the problem:

```python
test_output = api.model("Test nan", {"value": fields.Float})

@namespace.route("/test")
class TestResource(Resource):
    """Test resource.
    """
    @api.marshal_with(test_output)
    def post(self):
        return {"value": float("nan")}, 200
```

I checked the documentation for `fields.Float`; the example values include both `nan` and `inf`, and my API actually returns correct `nan` values when I use `curl` or any other REST client to query the API. However, Swagger UI just won't handle it correctly and instead will return a status code of 0 and a response header `{"error": "no response from server"}`.

In addition, `fields.Float` does not seem to take any optional arguments like `allow_null` or `nullable`... Anyone know how I might fix the problem? This is not too much a problem for people actually using my API since it won't be through the Swagger page, but I still want to get rid of the problem.

Thanks a lot.

**Comment by frol** [comment]
Neither `NaN`/`nan`/... nor `Inf` are defined in JSON spec. Thus, even though Python serializes that into JSON, that JSON is, in fact, invalid. I recommend you deal with this on your end replacing those values with `null`, for example.

**Comment by kuo000** [comment]
Thanks @frol . I guess I'll deal with the `NaN` values on my API end then.
