### ISSUE TITLE
Swagger Authorization Issue

### ISSUE THREAD

**Issue by yantisj** [noirbizarre/flask-restplus#315]
Hey,

I implemented JWT authentication on my API, and everything works great in testing (of course). When I put my API into production, request an API token, and then pass it to 'Authorize' in swagger, I get an error from JWT that Bearer is not found. I'm adding Bearer in front of the token, and it's obviously finding the Authorization Header (otherwise it would throw a missing header error), but for some reason it can't parse the string in production.

What's odd is the curl command generated from sagger works just fine, so it has to be some sort of swagger issue.

Code:
```
authorizations = {
    'apikey': {
        'type': 'apiKey',
        'in': 'header',
        'name': 'Authorization'
    }
}
```

This works fine, generated strait from swagger:
curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer __truncated__' 'https://server.domain.com:9000/api/v2/search/test'

Hitting try it out:
```
{
  "msg": "Bad Authorization header. Expected value 'Bearer <JWT>'"
}
```

Any idea about how to go about troubleshooting this? Again, works fine in development, this only happens when I deploy via wsgi in production. Otherwise the API works fine.

Thanks!

**Comment by yantisj** [comment]
Sorry for opening this, but I found my issue. Somehow my browser (Safari) was caching some bad information moving from dev to production using the same browser. Clearing everything out fixed it if anyone else runs into this.

**Comment by hoenie-ams** [comment]
Yep, I ran into the same issue. Thanks for mentioning your resolution!
