### ISSUE TITLE
Failed to load resource: net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by alexisrolland** [noirbizarre/flask-restplus#321]
Hello Flask gurus!
This is not an actual issue with flask-restplus but I'm a little bit desperate about this issue. I've posted it on Stackoverflow and I'm resharing it here as I hope to get some help / advices on how to troubleshoot this.

https://stackoverflow.com/questions/46174299/failed-to-load-resource-neterr-timed-out

We've built an API using Flask Restplus and it's usually running fine. It's using Flask internal webserver (Werkzeug). We have a web application built with Angular.js which is making http requests to our API. In some occasions, the web application fails to load its page and the following error message appears in Chrome console:

> Failed to load resource: net::ERR_TIMED_OUT

To be completely honest, I am not sure if this is related to:

 - The web application itself making an invalid call to the API
 - The API itself which is not responding in a timely manner (it still appears up and running when we get that error message)

I don't know how to troubleshoot this and I'm looking for some guidance to narrow downs the investigation to the faulty component. Any suggestion?

***Update:*** I've been able to reproduce the error by chance. Chrome Network tab did not show any information about the resource which timed out. It only showed info about resources loaded successfully. 

However the Console tab did show several endpoints which timed out. Example:

[![Error Message][1]][1]

Because there was several endpoints failing, my guess is the problem is on the back-end (not the web app making the http requests), and the API did not respond fast enough. What I don't know is which back-end component is responsible for the issue (the database, the server, the network, another API that we are calling in the backend, etc...)

  [1]: https://i.stack.imgur.com/7zont.png

**Comment by naeioan** [comment]
Do you see the requests reaching the server ? If not check your network.
If the request reaches your server, check the return code or do some debugging ( print the request headers,  etc)

**Comment by alexisrolland** [comment]
Ok, I'll do that! Thank you for your answer.

**Comment by Hayotbek-Turgunov** [comment]
Thanks
