### ISSUE TITLE
Multiple namespaces: cannot import name 'api'

### ISSUE THREAD

**Issue by n4rk0o** [noirbizarre/flask-restplus#349]
Hello,

I'm trying to test the multiple namespaces by executing the example in http://flask-restplus.readthedocs.io/en/stable/scaling.html

When I start the app.py I have this error:

Traceback (most recent call last):
  File "app.py", line 11, in <module>
    from apis import api
  File "c:\inetpub\wwwroot\apis\__init__.py", line 3, in <module>
    from .cat import api as ns1
  File "c:\inetpub\wwwroot\app.py", line 11, in <module>
    from apis import api
ImportError: cannot import name 'api'

I don't understand why I have this kind of error. I work on Windows server so maybe is there a bug relating the folder structure?

**Comment by TotempaaltJ** [comment]
This looks like a [circular import error](https://stackoverflow.com/a/744403/238310), which is not related to RestPlus or the OS, but to the module structure of your app.

**Comment by n4rk0o** [comment]
Thanks @TotempaaltJ.

I solved this and it was related to basic python development and module import.
