### ISSUE TITLE
Swagger UI endpoints not expanding when clicked?

### ISSUE THREAD

**Issue by ccolecsa** [noirbizarre/flask-restplus#374]
Flask-RESTPlus version:  0.10.1
Python version: 3.6.1
Platform:  Windows 10 Pro, latest updates

Following [this](http://flask-restplus.readthedocs.io/en/latest/quickstart.html) guide a simple, minimal Flask-RESTPlus API looks something like [this](https://github.com/ccolecsa/flask-restplus-swagger-ui-endpoint-expansion-fail/blob/Swagger-Endpoint-Expansion-Working/app.py).

However, once I split the namespaces into individual modules, the endpoints no longer toggle when clicked in the Swagger UI.  The code [here](https://github.com/ccolecsa/flask-restplus-swagger-ui-endpoint-expansion-fail/tree/master) is an example of this happening.

I was following the advice and examples provided [here](https://github.com/noirbizarre/flask-restplus/issues/29).

How do I achieve what I am trying to do while still retaining the nice Swagger UI?

**Comment by cerealcable** [comment]
I just noticed this behavior and seems to be due to the namespace containing a slash in it. Causes an javascript error.

**Comment by philiphoyos** [comment]
I had the same problem. If you remove the slash from the namespace it will work.

**Comment by ccolecsa** [comment]
@cerealcable, @philiphoyos thank you!

People in the future who have a similar issue, [here's](https://github.com/ccolecsa/flask-restplus-swagger-ui-endpoint-expansion-fail/commit/1c8c321f58aeb5526aa7a67b66867d7a9de8d5a8) how your namespaces should look in each module.
