### ISSUE TITLE
Namespace `decorators` are not applied to Resources?

### ISSUE THREAD

**Issue by rudasoftware** [noirbizarre/flask-restplus#375]
I have a decorator designed to wrap arbitrary Flask view functions, and I want to apply it to every resource in an `Api` or `Namespace`.

The `decorators` kwarg in `Api.__init__` works as expected. All methods of all `Resource` objects are decorated and return correct output.

However, using the analogous kwarg in `Namespace` has no effect. I've tried every way to wire namespaces to apis to apps in the documentation, and none of them work. In all the wiring strategies, if I use the `decorators` kwarg on the outer `Api`, everything works. However, sometimes I may want to apply the decorator only to a sub-tree of the `Api`, which makes a `Namespace`-level decorator look like the obvious solution.

I dug through the source code, and I can clearly see where `Api` decorators get applied to the `Resource` methods. However, I don't see where the `Namespace` decorators factor into the picture. There appear to be no uses of the `decorators` instance attribute outside of `Namespace.init`

**Comment by rudasoftware** [comment]
For now, I am just using multiple `Api`s instead of `Namespace`s. This works fine for my present usage.

However, I just thought I'd bring this up, in case this scenario isn't covered by tests or something.

**Comment by rudasoftware** [comment]
OOPS MY BAD

Somehow, the call chain roped `flask.jsonify` into the mix, and the resulting error was indistinguishable (on the surface) from the decorator not applying.

**Comment by sque** [comment]
@rudasoftware How did you exactly fixed this problem? I am trying to use the `decorators` argument of `Namespace` and has zero-effect. Only when I use the `decorators` of `Api` it is actually applied to views.

How did you overcome this?

**Comment by rudasoftware** [comment]
@sque Honestly, I'm not sure. I'm not 100% positive that it was actually the `Namespace` decorator argument or something else that I did while trying to fix it. 

I'm not using `flask_restplus` anymore. It was simpler (for my use case) to roll with `flask-sqlalchemy` and `flask-marshmallow`.
