### ISSUE TITLE
marshal_with envelope does not affect Swagger documentation

### ISSUE THREAD

**Issue by marrrcin** [noirbizarre/flask-restplus#390]
Consider the following code:
```python
from flask_restplus import Api, fields
from flask import Blueprint, request

api_example = Blueprint("api_example", __name__)
api = Api(api_example, description="Example API")

input_fields = api.model('InputFieldsModel', {
    'file': fields.String(description='File name', required=True),
    'number': fields.Integer(min=1, default=1),
})

input_model = api.model("InputModel", {
    "files": fields.List(fields.Nested(input_fields), required=True)
})

output_model_fields = api.model("OutputModelFields", {
    "file": fields.String(required=True),
    "data": fields.Float(required=True)
})

@api.route("/example")
class Example(Resource):
    @api.expect(input_model, validate=True)
    @api.marshal_with(output_model_fields, envelope="results")
    def post(self):
        return [{"file": "abc", "data": 0.1}, {"file": "xyz", "data": 0.9}]
```

I think that expected value in Swagger Documentation for the `POST` endpoint should have the following form:
*Model Example Value*:
```json
{"result": [{"file": "string", "data": 0}, {"file": "string", "data": 0}]}
```

But it actually is:
```json
{"file": "string", "data": 0}
```

which means that automated documentation generation **does not consider** `envelope` parameter, which is misleading when looking at Swagger UI.
Is it a bug or is there another way of generating proper documentation based on my requirements.

**Comment by benyitzhaki** [comment]
I'm having the same issue. @marrrcin have you overcome this one?

another issue is that we can't really define lists that will be reflected in swagger as part of the marshal decoration

**Comment by marrrcin** [comment]
No

**Comment by nick4u** [comment]
This is sad .. automatic Swagger documentation was one of the main reasons to use this framework for me. This is rather important and it's not even marked as bug since February

**Comment by nick4u** [comment]
workaround
~~~python
tag_schema = api.model('tag_schema', {
     'id': fields.String(),
     'tclass': fields.String(),
})

tag_schema_list = api.model('tags', {
     'tags': fields.List(fields.Nested(tag_schema)),
})

@api.marshal_with(tag_schema_list, description="list of tag's inside tags object")
def get(self)
       tag_list = load_data():
        if tag_list:
            return {'tags': tag_list}
        else:
            return None, 204
~~~

Swagger doc looks ok

**Comment by j5awry** [comment]
Sorry everyone for the lay off on things. As we're working to bring flask-restplus up to date, we're slowly working through the backlog. @tnt-dev has opened a PR that looks like it may address this issue. I've put it on my task board for the week to review.
