### ISSUE TITLE
Swagger HashMap

### ISSUE THREAD

**Issue by grhawk** [noirbizarre/flask-restplus#401]
To start, thank you very much for your work... I am using it extensively and both, the code and the documentation are precious. 

I was wondering if swagger [HashMaps](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties) are already implemented.
If they are not... is there some plan to do that? or, in the worst case for me (:)) where should I start to implement them?

Thank you very much.

**Comment by grhawk** [comment]
up :)

**Comment by TotempaaltJ** [comment]
This isn't currently supported. You'd have to add this to the parser module, but it's deprecated. You can probably implement it yourself as a subclass of `Model`.

**Comment by grhawk** [comment]
Thank you very much for the info!
