### ISSUE TITLE
No merges to master for over 2 months

### ISSUE THREAD

**Issue by crouffer** [noirbizarre/flask-restplus#420]
There are currently 19 open pull requests, and have been no merges to master in over 2 months.  Also, there have been no releases for over a year.  

Is this project dead, or is there still plans to maintain it @noirbizarre

**Comment by noirbizarre** [comment]
This project is not dead and I still have plans to maintain it. But plans are not the problem, time is.

**Comment by crouffer** [comment]
Thanks Axel.
