### ISSUE TITLE
Refactor for accepting Marshmallow and other marshaling libraries

### ISSUE THREAD

**Issue by TotempaaltJ** [noirbizarre/flask-restplus#438]
This is less of an issue and more of an **intent to implement** :shipit: 

## Result

The result of this work should be these two main things:

- It should be possible to build alternative request parsing implementations.
- It should be possible to use Marshmallow as easily as the current request parsing implementation.

I intend to try doing this without losing backward compatibility of public APIs, so that most applications can update without having to rewrite their marshaling implementations. No promises of course about the internal API.

## Planning

My plan of attack is as follows (may later be filled out with "subtasks"):

- [ ] **Design initial additions/changes to the public API through a simple "sample app"**
  
  I'm simultaneously building a real world product with RestPlus and Marshmallow (hacked in) for my employer @l1ndanl. This should help a ton, since I can my experiences and "wish list" from that to design the public API.

  This implementation might be useful later for testing the implementation, but it shouldn't be set in stone. Implementation details may have to  change the actual public API.

- [ ] **Locate and split out all touch points of the internal APIs with request parsing**

  Before I design the abstraction layer I'd like to make sure I know exactly what the internal API needs to be able to do and where it's used. This will require some more extensive knowledge of RestPlus internals and since these uses will have to be split out anyway eventually, doing this before designing the abstraction should make it a lot easier for me.

- [ ] **Design the abstraction layer**
- [ ] **Implement the abstraction layer for the "legacy" request parsing**
- [ ] **Implement an abstraction layer for Marshmallow and/or [webargs](http://webargs.readthedocs.io/en/latest/)**

## Methodology

I'll obviously be developing in my own fork of RestPlus in a special branch, that can then eventually be merged through a PR.

**I'm also very interested in suggestions/ideas/insider info/similar projects + shows of support 🎉 .**

## Related reading...

- https://github.com/noirbizarre/flask-restplus/issues/410
- https://github.com/noirbizarre/flask-restplus/issues/317
- https://github.com/noirbizarre/flask-restplus/issues/9
- The warning on this page: http://flask-restplus.readthedocs.io/en/stable/parsing.html

**Comment by TotempaaltJ** [comment]
Quick update: I'm working on the sample app, and finding out that it might be more useful to split out the validation & marshaling entirely, creating "extensions" that plug in to the RestPlus apidoc functionality.

That would mean that all I have to do is split out the current reqparse functionality, and build a small compatibility layer for webargs.

**Comment by aparamon** [comment]
@TotempaaltJ The problem with current interface `api.expect` is that it does only half of the expected job: it updates the doc-string and validates the input, but doesn't transform http request arguments into Python function arguments. One needs to keep the parser instance around and call `parser.parse_args()` inside the handler, which is a boiler-plate. Decorator `use_kwargs` from webargs is a very convenient way to handle the latter, and is universal enough to be compatible with traditional Flask-RESTplus `api.expect()` as seen from my code snipped.

**Comment by aparamon** [comment]
@TotempaaltJ and no, it *is* compatible with Flask URL path parameters:
```python
@api.route('/<path:path>/spec')
class Spec(Resource):

    parser = api.parser()
    parser.add_argument('scan', type=int)
    parser.add_argument('fromscan', type=int)
    parser.add_argument('toscan', type=int)
    parser.add_argument('minspec', type=float)
    parser.add_argument('maxspec', type=float)

    @use_kwargs(api, parser)
    def get(self, path, scan=None, fromscan=None, toscan=None, minspec=None, maxspec=None):
        ...
```

**Comment by TotempaaltJ** [comment]
Compatible, yes. But it doesn't exactly fit the "Flask way": path arguments are passed through the method/function args and essentially all other request information is passed through the `request` object.

Another possibility could be passing it all in a single keyword argument, instead of spreading out all the properties over different kwargs?

Also CC'ing @noirbizarre: what do you think?

**Comment by TotempaaltJ** [comment]
The idea I had before this would be something like:

```python
from flask import Flask
from flask_restplus import Api, Resource, reqparse

app = Flask(__name__)
api = Api(app)

parser = reqparse.RequestParser()
parser.add_argument(
    'rate', required=True, type=int, help='Rate cannot be converted')
parser.add_argument('bar', type=str, location='json')
parser.add_argument('User-Agent', location='headers')
parser.add_argument('session_id', location='cookies')


@api.route('/json')
# Note that this is a method of the parser object, since there's no Api state
# involved, only modifying the apidoc property:
@parser.expect()
class JSONResource(Resource):
    def get(self):
        args = parser.parse_args()  # or parser.args with a @property getter
        ...
```

And a similar API for webargs (with some sort of `@webargs.expect()` decorator)

**Comment by aparamon** [comment]
@TotempaaltJ

> But it doesn't exactly fit the "Flask way": path arguments are passed through the method/function args and essentially all other request information is passed through the request object.

It works well because `request` is a magick object available in every handler. And parser objects are not: one needs to keep a reference to each one, which tends to pollute the namespace really quickly.

Also, we might delve into Flask way vs Python way philosophy really deep ;-)

> Explicit is better than implicit

which reads for me

> Explicit handler method arguments are better than implicit request object

(but that's opinion/philosophy)

**Comment by aparamon** [comment]
@TotempaaltJ 
> Another possibility could be passing it all in a single keyword argument, instead of spreading out all the properties over different kwargs?

Yes:

````python
@api.route('/<path:path>/spec')
class Spec(Resource):

    parser = api.parser()
    parser.add_argument('scan', type=int)
    parser.add_argument('fromscan', type=int)
    parser.add_argument('toscan', type=int)
    parser.add_argument('minspec', type=float)
    parser.add_argument('maxspec', type=float)

    @use_kwargs(api, parser)
    def get(self, path, **kwargs):
        ...

**Comment by TotempaaltJ** [comment]
Sure, we could register something on the request context though, that's not a problem per se.

**Comment by erlendcognite** [comment]
What is the status on this? Will it be implemented any time soon?

**Comment by tedzhu** [comment]
Any update on this?  I see some libraries do the integration between flask and marshmallow, but afaik only restplus integrates with swagger, so really looking foward to this being implemented.

**Comment by madstacks** [comment]
I just discovered `flask-apispec` which does produce swagger as well, but I have not tested it. Unfortunately it does not look very active.

https://github.com/jmcarp/flask-apispec

**Comment by hygorxaraujo** [comment]
> I just discovered `flask-apispec` which does produce swagger as well, but I have not tested it. Unfortunately it does not look very active.

The maintainer of `flask-apispec` isn't working on it anymore: https://github.com/getredash/redash/issues/2981#issuecomment-443860884.

**Comment by madstacks** [comment]
Bummer! Thanks for the update @hygorxaraujo

**Comment by erlendcognite** [comment]
Using just regular old [apispec](https://github.com/marshmallow-code/apispec)'s OpenAPIConverter works well for me. You can convert your marshmallow schemas to json schemas and use those in your restplus Resource definitions.

Something along the lines of
```
from apispec.ext.marshmallow import OpenAPIConverter
from marshmallow import Schema
from flask_restplus import Resource
from app import api

class MySchema(Schema):
    my_str = fields.String()

json_schema = OpenAPIConverter(OpenAPIVersion(openapi_version="2.0")).schema2jsonschema(
                    schema=MySchema
                )

@api.route("/")
class Models(Resource):
    @api.response(200, "OK", json_schema)
    def get(self):
        response: Model = {"myStr": "something"}
        return MySchema().dump(response), HTTPStatus.OK
```

**Comment by tedzhu** [comment]
@erlendcognite thanks for the snippet. I tried it out it works, but ran into another marshaling issue (https://github.com/noirbizarre/flask-restplus/issues/293). 

I guess the other way (marshmallow.Schema -> restplus.Model) could be an option. Ideally having the feature requested in this issue implemented feels the right solution. Until then I'll live with manually creating 2 schemas :joy:

**Comment by trustchk** [comment]
> The maintainer of `flask-apispec` isn't working on it anymore: [getredash/redash#2981 (comment)](https://github.com/getredash/redash/issues/2981#issuecomment-443860884).

While there were just about 30 commits in the last two months of 2018 (which in itself isn't a real indicator, but the comment you're referring to is from early December), development seems to have picked up speed with >100 commits since Jan 01 and it looks like they're heading for the 1.0.0 release. Maybe @sloria or @lafrech could chime in with a comment on their plans?

**Comment by lafrech** [comment]
@trustchk, we've been working on apispec lately and a v1.0.0 is about to be released. Hopefully in a few days.

**Comment by sloria** [comment]
@hygorxaraujo @trustchk 

To clarify: my comment on Redash was about flask-apispec, not apispec. We're not actively working on flask-apispec at the moment (though this may change, since the original author might be using it again for work).

apispec--on the the other hand--is under very active development. As Jérôme said, a 1.0 is coming very soon.

**Comment by aparamon** [comment]
Sorry, but what is the resolution to original problem?
(and to `webargs` integration discussed here)

**Comment by TotempaaltJ** [comment]
Ah, right. This is no resolution but more of a retraction. The original issue was about discussion on my intent to PR changes to RestPlus:

> This is less of an issue and more of an **intent to implement** :shipit:

That was a while ago, and I did start working on this. After building a product with the project for several months though, I no longer believe that this project has a real future, as @noirbizarre either isn't motivated or doesn't have the time for the significant amount of "upkeep" required to manage a project like this.

Which is fine and completely understandable from the maintainer's side--I very explicitly don't mean to pass any judgement on him. It happens.

I suggest you continue the thread in a more specific issue (like #9) or look into something like [this patch](https://github.com/Jaza/flask-restplus-patched) instead.

**Comment by flayman** [comment]
Hi,

I've had some success with the [method described above](https://github.com/noirbizarre/flask-restplus/issues/438#issuecomment-460350182) by @erlendcognite. 

The api for apispec.ext.marshmallow.OpenAPIConverter has changed (in fact it has moved) and the docs give that as an internal class not meant to be used directly. There is a class  apispec.ext.marshmallow.MarshmallowPlugin that is the intended use case. Some of the example code above needs to be rewritten:

```
from http import HTTPStatus

from apispec.ext.marshmallow.openapi import OpenAPIConverter
from apispec.ext.marshmallow import MarshmallowPlugin
from flask import Flask
from flask_restplus import Api, Resource
from marshmallow import Schema, fields

app = Flask(__name__)
api = Api(app)


class MySchema(Schema):
    myStr = fields.String()

def resolver(schema):
    return None

spec = APISpec(
    title=api.title,
    version=api.version,
    openapi_version="2.0",
    plugins=[MarshmallowPlugin(schema_name_resolver=resolver)],
    info=dict(description=api.description)
)

schema2jsonschema = spec.plugins.pop().openapi.schema2jsonschema

json_schema = schema2jsonschema(schema=MySchema)
schema_model = api.schema_model(MySchema.__name__, json_schema)


@api.route("/myResource")
class Models(Resource):
    @api.response(200, "OK", schema_model)
    def get(self):
        response = {"myStr": "something"}
        return MySchema().dump(response), HTTPStatus.OK


app.run()
```

That should get you where you want to go. The openapi_version param can be different. I used the same one given. It's important to use a schema_name_resolver function that always returns False in a boolean context because otherwise it won't serialize nested marshmallow schemas correctly.

**Comment by adnanmuttaleb** [comment]
Or we can try the opposite (integrating `marshmallow` with `restplus`), check this [library](https://github.com/fuhrysteve/marshmallow-jsonschema) which convert marshmallow `Schema` in to` JSON Schema`.
