### ISSUE TITLE
Any support for Fixed fields such as Host / Tags and Vendor fields?

### ISSUE THREAD

**Issue by Kelvinm** [noirbizarre/flask-restplus#44]
Hi,

I started implementing a project with your library, and so far its great.  I found it intuitive and relatively easy to use.  A few things that aren't available are top level tags like Host and additional tags on the path (which for now is only used by the namespace).

I've made modifications locally, but wasn't sure if this was functionality that was going to be forthcoming.

Thanks!
Kelvin

**Comment by noirbizarre** [comment]
Hi !

Thanks for your support.

If you have some feature to add, don't hesitate and submit a pull-request.
Ensure you have test for it and it runs on all Python version (you can use tox to test against different Python version).

It reminds me I should write the CONTRIBUTING.rst :)
