### ISSUE TITLE
Namespace not exported?

### ISSUE THREAD

**Issue by chenasraf** [noirbizarre/flask-restplus#445]
https://github.com/noirbizarre/flask-restplus/blob/00d79c1fd081c44429f6162eb29f5f322e6c04e1/flask_restplus/__init__.py#L26

__all__ doesn't include `Namespace` which seems to throw warnings for most IDEs. I don't believe it's by design but I could be wrong. Could someone shed some light on this?

Using the latest flask-restplus version on Python 3.6

**Comment by manbeing** [comment]
I am using python 2.7, and the namespace is able to be exported to swagger file.
I tried both ways:
1. api.namespace = xxxxxxxx
2. set up the default  and default_label in api=Api(app, default=xxxx, default_label=xxxx)

**Comment by TotempaaltJ** [comment]
@manbeing I think you misunderstood the issue. It's simply that the `__all__` property in `flask-restplus/flask_restplus/__init__.py` doesn't include the `Namespace` object, preventing IDEs from discovering it.
