### ISSUE TITLE
Non URL Encoded input field support request

### ISSUE THREAD

**Issue by wmaness** [noirbizarre/flask-restplus#45]
I have a particular situation where I want to allow the swager user to be able to type an arbitrarily formatted query string and have it work in the "try it".  The problem right now is that the string is urlencoded and thus breaks when it's run.  Basically, I want the same input that I put into the query string to make it through to the 'try me' because I don't know all of the possible query keys in advance:

![screen shot 2015-05-07 at 3 07 00 pm](https://cloud.githubusercontent.com/assets/3254937/7523633/d92301fc-f4ca-11e4-9142-3710460eaa41.png)

Note the query string input, and the URLEncoded result in 'try me.'  I need a clean way to tell it not to urlencode.

**Comment by noirbizarre** [comment]
Hi !

This is an upstream Swagger-UI feature request.
You should submit your issue here: https://github.com/swagger-api/swagger-ui

flask-restplus simply embed the Swagger-UI.
