### ISSUE TITLE
Request in XML body

### ISSUE THREAD

**Issue by manbeing** [noirbizarre/flask-restplus#451]
Does flask-restplus support **_request_** with a XML encoded body? I found an example about how to implement **_response_** with a XML body in help doc, but no information about request? I googled a lot but no lucks. If somebody here knows how to implement **_request_** in XML, could you give me an example? Thanks.

**_Response_** in XML example from help doc:
```python
   @api.representation('application/xml')
   def xml(data, code, headers):
      resp = make_response(convert_data_to_xml(data), code)
      resp.headers.extend(headers)
      return resp
```

**Comment by TotempaaltJ** [comment]
This isn't currently supported, I'm afraid.

**Comment by manbeing** [comment]
I have made it happen, but I just don't know how I can let restplus extract 'application/xml' to file.

consumes:
  - application/json
  - application/xml   <--------( I manually added this line in exported swagger file)

**Comment by manbeing** [comment]
I found a solution:
Go to source code swagger.py
Change line#192 to 'consumes': ['application/json','application/xml']  from 'consumes': ['application/json']
Then the application/xml is exported to swagger file.
Does anybody know a way to change it in the scripts rather than in the source code?

**Comment by TotempaaltJ** [comment]
You'd be able to do this more with the solution is suggested here: https://github.com/noirbizarre/flask-restplus/issues/441#issuecomment-390935767

**Comment by manbeing** [comment]
@TotempaaltJ 
 Thanks for  your help! I followed your example in #441, but got the error:

 * Running on http://localhost:5000/ (Press CTRL+C to quit)
C:\Users\xxxxx\Envs\restfulplus\lib\site-packages\flask\sessions.py:208: UserWarning: "localhost" is not a valid cookie domain, it must contain a ".". Add an entry to your hosts file, for example "localhost.localdomain", and use that instead.
  ' "{rv}.localdomain", and use that instead.'.format(rv=rv)
127.0.0.1 - - [31/May/2018 13:28:13] "GET / HTTP/1.1" 200 -
**No handlers could be found for logger "apicustom"**
127.0.0.1 - - [31/May/2018 13:28:14] "GET /swagger.json HTTP/1.1" 500 -

My code:
`import apicustom `
`api = apicustom.CustomApi(app)`
`app.run(debug=True)`

**Comment by TotempaaltJ** [comment]
Looks like a logging problem. Do you have any `logging` handlers set up?

**Comment by manbeing** [comment]
No, i don't have. can you give me a quick example how to set it up?

**Comment by manbeing** [comment]
I think my error is here:

![image](https://user-images.githubusercontent.com/39745132/40854883-d1e9bff8-65a0-11e8-85de-d4bf47c748f0.png)

my code is exactly the same as your except one line:
```python
import logging

from flask_restplus import Api, Swagger
from werkzeug import cached_property

logger = logging.getLogger(__name__)


class CustomSwagger(Swagger):
    """Override RESTplus Swagger class to add custom properties."""

    def as_dict(self):
        """Add custom properties to top-level Swagger specs."""
        specs = super().as_dict()
        specs['consumes'] = ['application/json','application/xml']
        return specs


class CustomApi(Api):
    @cached_property
    def __schema__(self):
        """
        The Swagger specifications/schema for this API

        Override this to refer to our fixed Swagger class.

        :returns dict: the schema as a serializable dict
        """
        if not self._schema:
            try:
                self._schema = CustomSwagger(self).as_dict()
            except Exception:
                # Log the source exception for debugging purpose
                # and return an error message
                msg = 'Unable to render schema'
                logger.exception(msg)  # This will provide a full traceback
                return {'error': msg}
        return self._schema
```

**Comment by manbeing** [comment]
I think i have fixed it. I think you use python 3. it is a legal syntax super().xxxx in python 3, but not in python 2

**Comment by GAURAV-DEV-ZT** [comment]
Hello @manbeing , I try as above you mentioned to 
Change line#192 to 'consumes': ['application/json','application/xml'] from 'consumes': ['application/json']
in swagger.py file but when I try to hit the API it shows me an error.

{
  "message": "Did not attempt to load JSON data because the request Content-Type was not 'application/json'."
}
