### ISSUE TITLE
Remove default namespace?

### ISSUE THREAD

**Issue by manbeing** [noirbizarre/flask-restplus#460]
This issue has confused me for several days, and I still cannot find a solution to resolve it. Just wanted to see if somebody here has some bright ideas.
For example, I make a namespace called 'test' for my app, but somehow, the default namespace is shown:
![image](https://user-images.githubusercontent.com/39745132/40891599-78534b78-6756-11e8-9a38-2993ce987474.png)

To get rid of this redundant default namespace, what I have done is to set the default namespace value when initializing the Api:
```python
api = Api(app, default ='test', default_label='this is namespace test')
```
Unfortunately, this is not an ideal solution because I found there were two duplicate namespaces extracted to swagger file.
![image](https://user-images.githubusercontent.com/39745132/40891798-10c5e232-675a-11e8-9471-0bc3b66c5d76.png)

**Comment by TotempaaltJ** [comment]
Looks like a bug to me :+1:

**Comment by narfman0** [comment]
`default=None` or not having a default if any ns is defined would be great. I don't want a default in any nontrivial project.

**Comment by reiroldan** [comment]
Well, I just added:  api.namespaces.clear() before adding my namespaces ;)

**Comment by Divingpig** [comment]
Add api.namespaces.pop(0) to remove the default namespace.

**Comment by lloy** [comment]
Add api.namespaces = [] to remove the default namespace.
