### ISSUE TITLE
CORS headers not being added to the response despite endpoint being decorated

### ISSUE THREAD

**Issue by kritchie** [noirbizarre/flask-restplus#467]
# Version
flask-restplus==0.10.1

# My issue
I have an issue with the CORS header not being added to the response. I'm using the 'cors' method from the package (not flask-cors). I've opened a question on StackOverflow (https://stackoverflow.com/questions/50708821/flask-restplus-cors-request-not-adding-headers-into-the-response). 

Basically, I'm doing this : 

    from flask_restplus import cors

    @api_ns.route('/some/endpoint')
    @api_ns.response(code=400, description='Bad Request.')
    class AEndpointResource(Resource):

        @api_ns.param(**api_req_fields.POST_DOC)
        @api_ns.expect(POST_REQUIRED_BODY)
        @api_ns.marshal_with(code=201,
                     fields=my_api_models.MyEndpointResponse.get_serializer(),
                     description=my_api_models.MyEndpointResponse.description)
        @cors.crossdomain(origin='*')
        def post(self) -> Tuple[my_api_models.MyEndpointResponse, int]:
            """
            The post body
            """
            # Some logic here
            return response, 200`

And I still have the same result as without applying the CORS decorator. No CORS headers are added to the Response of the OPTIONS query to my endpoint.

Anyone else having/had that issue ?

**Comment by TotempaaltJ** [comment]
I'd recommend using Flask-CORS instead.

**Comment by TommyLike** [comment]
👍 Also has this issue.

**Comment by kritchie** [comment]
Hi guys, sorry for the long delay. My problem have been fixed. My issue was due to a lack of understanding of the our system which was deployed with a Web Server handling CORS header preemptively. 
It's not an issue for me anymore.

**Comment by tiagobarreto** [comment]
The same problem.

**Comment by vdboor** [comment]
It seems that the problem is that no method handles the `OPTIONS` request. So, a `GET` request could tell the browser that CORS is allowed, but once the browser makes an `OPTIONS` request, this gets reverted. Hence, each soft browser refresh causes a flickering cors on/off behavior.

Workaround is adding the `options` method to the `Resource`:

```
@api.route("/your-endpoint")
class SomeEndpoint(Resource):
    @cors.crossdomain(origin='*')
    def options(self):
        # Make sure the OPTIONS request is also handled for CORS
        # The "automatic_options" will handle this, no need to define a return here:
        return

    @api.expect(my_schema)
    @api.response(200, "Success")
    @cors.crossdomain(origin='*')
    def get(self):
        return {"json-fields": 123}, 200
```

I've also added that workaround here: https://stackoverflow.com/a/58096183/146289

**Comment by kritchie** [comment]
**Note on issue closing** : See my other comment above.

I've closed this issue to prevent wrong assumptions from being made because of my initial issue. If someone else encounters the same thing, it's most likely a different problem, therefore I don't see my previous situation being relevant to anyone else. 

If you think this issue should be re-opened, feel free to do so but as I mentioned, the problem was coming from a configuration with other parts of my overall stack. Therefore, it's irrelevant to maintainers of this package.
