### ISSUE TITLE
Support for multiple payload types in api.expect

### ISSUE THREAD

**Issue by craigwong** [noirbizarre/flask-restplus#473]
Hi,

If I wanted to have a single endpoint support both `{}` (object) and `[{}, {}, ...]` (list of objects) POST JSON payloads--how would I accomplish this?

I haven't been able to use api.expect to support both types of payloads.
Something like this (doesn't actually work):

```
api.expect(single_object_payload)
api.expect([single_object_payload])
```

**Comment by Colin-b** [comment]
I usually have a single endpoint handling a list of objects, then if a
client want to send a single object he can still send a list with a single
element.

Assuming your question was about having the same object definition between
your list and the object.

In such a case your code would be easier to read as you only expect a
single kind of data.

Hope this helps
