### ISSUE TITLE
How to add Bearer <JWT> in swagger-ui request

### ISSUE THREAD

**Issue by jreg2k** [noirbizarre/flask-restplus#481]
Hello,
I have the same issue like : https://github.com/noirbizarre/flask-restplus/issues/315, but I can't find a solution. I a using the flask_restplus 0.11

I've been searching for a long time but I didn't found how to make query with jwt.
My authorisations looks like : 

    authorizations = {
        'apikey': {
            'type' : 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    }
the resulting query is : 

    curl -X GET "http://localhost:5000/api/request/" -H "accept: application/json" -H "Authorization: 12345"

The api answer : 

    {
      "msg": "Bad Authorization header. Expected value 'Bearer <JWT>'"
    }

If I add Bearer in 'authorizations like :  

    authorizations = {
        'apikey': {
            'type' : 'apiKey',
            'in': 'header',
            'name': 'Authorization Bearer'
        }
    }

the query is : 

    curl -X GET "http://localhost:5000/api/request/" -H "accept: application/json" -H "Authorization Bearer: 12345"

And I want a query like  this : 

    curl -X GET "http://localhost:5000/api/request/" -H "accept: application/json" -H "Authorization: Bearer 12345"

Can somebody give me some help ?

Regards.

James

**Comment by jreg2k** [comment]
I have found a solution, and I think this is the best solution.
In the dialog box, the token is : 

Bearer: XXXXXXX

instead of just

XXXXX

James

**Comment by MbuguaCaleb** [comment]
wow

**Comment by d2gex** [comment]
Just to add a bit on this. You can actually add a 'description' to the authorisation dictionary as follows:

```
authorizations = {
    'apikey': {
        'type': 'apiKey',
        'in': 'header',
        'name': 'Authorization',
        'description': "Type in the *'Value'* input box below: **'Bearer &lt;JWT&gt;'**, where JWT is the token"
    }
}
```

Then you'll get a screen as follows:

![Screen Shot 2019-05-14 at 10 16 15](https://user-images.githubusercontent.com/34709566/57686378-6adf3980-7631-11e9-983b-e5f14afb9e5b.png)

HIH

**Comment by RESHNAM** [comment]
Thanks @jreg2k
