### ISSUE TITLE
api.inherit() not working as intended Swagger allOf Feature

### ISSUE THREAD

**Issue by srilman** [noirbizarre/flask-restplus#482]
It seems like the api.inherit() / model.inherit() function does not seem perform the same affect on the Rest API as the Swagger allOf feature, which I believe is the intended functionality of the inherit function. 
Specifically, I don't think the discriminator value works as Swagger docs intend it to.

Looking at swagger's documentation (https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof), we see that when you specify allOf in a certain model that references a parent model, then the name of the child model is used as a reference for the discriminator value. In my flask-restplus implementation, the value of the discriminator field doesn't have any affect on the allowed fields. For example, if I had:
```
pet = api.model('Pet', {
  'type': field.String(required=True, discriminator=True)
})

dog = api.inherit('Dog', pet, {
  'dogType': field.String(required=True)
})
```
then the API would accept a request body like so: `{'type': 'Dog'}` even though it should respond that the `dogType` field is missing.

Also, it seems that in the example in the swagger dos, the discriminator value can only be either Cat or Dog and nothing else. However, in flask-restplus, I can set it equal to anything with no effect. For example, using the models above, the API would also accept something like `{'type': 'Toaster'}`. Is this supposed to be the intended functionality?

Flask-Restplus is really helpful for designing Swagger API's dynamically for Python, but the allOf description and the discriminator field are both really important features that I would like to make sure is working correct. If you can, could you please describe what you think about this? Thanks!

**Comment by PietroPasotti** [comment]
Yes, I am encountering unexpected behaviour there as well.
```
x = api.model('a', {'b':'c'})
y = api.inherit('d', x, {'e':'f'})
```

and then somehow printing y only results in: `{'e':'f'}`

Also seems not to match the docs description.
