### ISSUE TITLE
Using models from another namespace? Designed my project for models to be in separate folder, to be reused one with another - end up with "no spec provided" 500 swagger.json

### ISSUE THREAD

**Issue by idchlife** [noirbizarre/flask-restplus#489]
Often defining models right there with the views becomes a total mess, especially when models are reused in another namespaces.
First, **resource_model_a** becomes **resource_model_a_dict**, then, if there was another nested model inside this dict, it too becomes a dict, and then there are a whole bunch of helper functions and project files are filled with helpers to overcome "no spec provided".

What's the best way to solve this problem?

Examples:

I want to have this

models/products.py

```python
from flask_restplus import Namespace, fields

api = Namespace("ProductsNamespace")

resource_product = api.model("Product",  {
  'id': fields.Integer,
  'name': fields.String
})

```

models/owners.py

```python
from flask_restplus import Namespace, fields
from .products import resource_product

api = Namespace("OwnersNamespace")

resource_owner = api.model("Owner", {
  'id': fields.Integer,
  'name': fields.String,
  'products': fields.List(fields.Nested(resource_product))
})
```

views/owners.py

```python
from flask_restplus import Namespace, fields, Resource
from ..models.owners import resource_owner

api = Namespace("OwnersApi", path="/owners")

@api.route("")
class List(Resource):
  @api.marshal_with(resource_owner)
  def get(self):
    pass
```

**Comment by idchlife** [comment]
Resolved.
For those who will come with such question:

use

```python
from flask_restplus import Api

root_api = Api()

resource_product = root_api.model(...
```

Just use Api object for global models

**Comment by bigfoot31** [comment]
How to use the root_api in the other namespace? Direct usage is resulting in ValueError: Model _model_name_ is not registered

**Comment by idchlife** [comment]
@bigfoot31 could you please provide example of usage with error? I could show you how I done this.

**Comment by bigfoot31** [comment]
_app.py_
```
from namespace1 import api as ns1
from namespace2 import api as ns2

api = API()
api.add_namespace(ns1)
api.add_namespace(ns2)

validation_error_model = api.model('validation_error_model', {....})
```

_namespace1.py_
```
class Route1(Resource):
    @api.response(...., **validation_model**)
    def get(self):
```

_namespace2.py_
```
class Route2(Resource):
    @api.response(...., **validation_model**)
    def get(self):
```

I would like to have validation_model defined once and used in all namespaces. Just could not make it work to the extend that I generated a swagger.yaml from swagger hub and loading the swagger ui through a custom endpoint in my project.

**Comment by idchlife** [comment]
@bigfoot31 I'm not experienced with validation_model in @api.response so I cannot give any advice on this. Did you try using it with @api.marshal_with ?

I'm often using root_api for using with another_api.Nested or another_api.inherit

**Comment by bigfoot31** [comment]
@idchlife 
Can you show an example more elaborate than the one above? Perhaps even a pull request to add an example

**Comment by idchlife** [comment]
@bigfoot31 

Ah! Actually I made small mistake in my response. For resources, all resources, I'm using root_api.
They just defined in different modules, but use same root_api

And Namespaces I use for class List(Resource), ns.marshal_with, ns.expect, etc


I don't define resources in different namespaces since I don't see the benefit of it, since I separate resources dfined with api.model() or api.inherit() in different modules, making "separate api.model for separate namespaces" unneeded for me.

Like this:

root_api = Namespace("AllModels")

Then I use them everywhere. The thing is this is actually the solution to my topic problem in this issue.

Just use one namespace for all of the models/resources.

And different namespaces for actually classes - views
