### ISSUE TITLE
Support ORM (MongoKit) models?

### ISSUE THREAD

**Issue by mikeroll** [noirbizarre/flask-restplus#50]
I've been trying to generate `ApiModel`s from from MongoKit models:

Consider the following MongoKit model:
```python
@api.model() # this would be awesome
class User(Document):
    structure = {
        'name': unicode,
        'email': unicode,
    }
    use_dot_notation=True
```
Currently I've tried this
```python
user_model = api.model('User', fields=User.structure)
```
Kind of expected this to work automagically, but looks like I'm missing something. 

```python
File "/home/mike/.virtualenvs/cmdb/lib/python2.7/site-packages/flask_restplus/swagger.py", line 357, in serialize_schema
    raise ValueError('Model {0} not registered'.format(model))
ValueError: Model <function wrapper at 0x7fb5a6cb1578> not registered
```

Not sure how the whole model mapping process works, could you please provide some details?

Thanks!

**Comment by noirbizarre** [comment]
Hi !

Sorry for the (very) late response.

Given your example it seems natural/logical to reuse your models.
As MongoKit is specific to your usage and I'm not using it, I won't implement myself this feature. I try to stick on the HTTP processing level only.

I suggest you to implement your MongoKit2Restplus model factory so you could write:
```python
user_model = from_mongokit(User)
```

If you're doing that, don't hesitate to submit a pull-request to integrate this factory and the associated tests in a contrib package.
You can also publish your own package only containing this factory.

If you need help, just come on gitter and ask, I will.
