### ISSUE TITLE
Custom Header documention

### ISSUE THREAD

**Issue by mad0house** [noirbizarre/flask-restplus#51]
Currently I do not see any way to say that custom  headers are required ( for api keys and such)

maybe something like 
`@doc(headers={'API_KEY':'your api key'})`

**Comment by jon-walton** [comment]
I've started decorating methods similar to this:

```
custom_header1 = {'X-cust1': {'name': 'X-cust1',
                              'in': 'header',
                              'type': 'string',
                              'description': 'custom header 1'}}

custom_header2 = {'X-cust2': {'name': 'X-cust2',
                              'in': 'header',
                              'type': 'string',
                              'description': 'custom header 2'}}


@sessions.route('/')
class SessionsAPI(Resource):
    @api.doc(params=custom_header1)
    @api.doc(params=custom_header2)
    def get(self):
        """Do things"""
        pass
```

Seems to work, but isn't pretty

**Comment by noirbizarre** [comment]
Hi !

I just added the ``@api.header`` shortcut to make it easier to document headers: http://flask-restplus.readthedocs.org/en/latest/documenting.html#headers

But there already is some alternative ways:
- You can use the request parser to expect an header, it will be automatically documented.
  ```python
parser = api.parser()
parser.add_argument('API_KEY', type=str, location='headers')

@api.route('/headers/')
class HeadersResource(restplus.Resource):
       @api.doc(parser=parser)
       def get(self):
           args = parser.parse_args()
           print args['API_KEY']
```
- In you specific case, authorization headers, Swagger expect an authorization object to describe it. See http://flask-restplus.readthedocs.org/en/latest/documenting.html#documenting-autorizations

**Comment by jroyal** [comment]
I realize this is closed, but I was trying to use the header decorator like it was described in the docs and you can't right now. I think mainly because the last version released was a couple of months ago and this change is more recent. Are you planning on pushing out a new release sometime soon?
