### ISSUE TITLE
How to pass headers with jwt tokens in swagger ui

### ISSUE THREAD

**Issue by larryTheGeek** [noirbizarre/flask-restplus#524]
hello guys I'm using flask_restplus with swagger documentation  i cant find away to pass the token generated after login in swagger UI.  As a result Im unable to view the protected routes.  what I would like to know is what to do so i can get an input field where i can input the Bear <JWT> and be able to view the protected routes. Thank you

**Comment by mmanhertz** [comment]
Try something along the lines of:

```
authorizations = {
    'apikey': {
        'type': 'apiKey',
        'in': 'header',
        'name': 'authorization'
    }
}

api = Api(
    ...
    authorizations=authorizations,
    security='apikey',
)
```

You can also add the `security='apikey'` to each endpoint individually using `@api.doc(security='apikey')`, in case you only have some endpoints that are protected.

**Comment by larryTheGeek** [comment]
It worked thanks
