### ISSUE TITLE
How to get response from Flask-RESTPlus in csv

### ISSUE THREAD

**Issue by lijose** [noirbizarre/flask-restplus#525]
I have created and REST API using Flask-RESTPlus. I am getting response in json and its fine. Now I have a new requirement to specify Response content type as csv or json.

I checked API doc there is nothing mentioned !!

Is it possible to get reponse in csv using Flask-RESTPlus ??

**Comment by lijose** [comment]
I was able to get output in csv . It took some time though

```
@api.representation('text/csv')
def data_csv(data, code, headers):
    '''Get result in csv '''
    resp = make_response(convert_data(data), code)
    resp.headers.extend(headers)
    return resp
```

**Comment by gabi939** [comment]
@lijose what is convert_data? convert JSON to CSV file or DataFrame?

**Comment by lijose** [comment]
I used convert_data to convert json to csv format.

**Comment by gabi939** [comment]
Any chance you can publish the code for  convert_data ?
