### ISSUE TITLE
Namespace 'name' argument part of api route

### ISSUE THREAD

**Issue by MainaKamau92** [noirbizarre/flask-restplus#529]
````
from flask_restplus import Namespace, Resource, fields

api = Namespace('Cats', description='Cat related operations')

cat = api.model('Cat', {
    'id': fields.String(required=True, description='The cat identifier'),
    'name': fields.String(required=True, description='the cat name'),
})

CATS = [
    {'id': 'felix', 'name': 'Felix'}
]


class CatList(Resource):
    @api.doc('list-cats')
    @api.marshal_list_with(cat)
    def get(self):
        """
        Lists all cats
        """
        return CATS

api.add_resource(CatList, '/cat')
````

Using the above namespace excerpt(the same example in the docs) which utilizes namespace with blueprints, i find that the api route for accessing the `/cat` route mandates it to be preceded by the Namespace ('name') argument, excluding the Namespace 'name' argument which in this case is 'Cats' leads to the route throwing a 404.
Thus if i want to access the list[CATS] from an api route from a localhost server url prefixed by `/api/v2`, using
`localhost:5000/api/v2/cat` throws a 404 whereas, `localhost:5000/api/v2/Cats/cat` provides the intended result, is this supposed to be the case or am i missing something crucial?

NB: Forgive the repetition i tried to be as explicit as i could.

**Comment by noirbizarre** [comment]
You can simply use the [Namespace constructor](https://flask-restplus.readthedocs.io/en/stable/api.html#flask_restplus.Namespace) `path`parameter to set its prefix to any path or unset it.

But,given you example, I think the right approach would be to actualy makeuse of the default prefix:

```python
from flask_restplus import Namespace, Resource, fields

ns = Namespace('cats', description='Cat related operations')

cat = ns.model('Cat', {
    'id': fields.String(required=True, description='The cat identifier'),
    'name': fields.String(required=True, description='the cat name'),
})

CATS = [
    {'id': 'felix', 'name': 'Felix'}
]

@ns.route('/')
class CatList(Resource):
    @ns.doc('list-cats')
    @ns.marshal_list_with(cat)
    def get(self):
        """
        Lists all cats
        """
        return CATS
```
This will make your API available to `localhost:5000/api/v2/cats/` (This is an example just so you understand why there is an automatic prefix)

**Comment by MainaKamau92** [comment]
Thank you for the response.
