### ISSUE TITLE
Ability to enter schema via dict

### ISSUE THREAD

**Issue by stevezau** [noirbizarre/flask-restplus#53]
Hi,

Is it possible to enter schema via dict rathern the using api.Model??

Most of our config uses jsonschema which we want an api to be able to modify the config for the application. There is quite alot of jsonschema and would prefer to use our existing rather then duplicate to api.Model

IE:
```
sch = {
    'type': 'object',
    'properties': {
        'force': {'type': 'boolean'},
    }
}


@server_api.route('/someapi/')
class SomeAPI(Resource):

    @api.expect('SomeAPI', sch)
    def post(self)
```

Thanks!

**Comment by gazpachoking** [comment]
[This](https://github.com/Flexget/Flexget/blob/ec25b7263c430bab3f7df221884c2c97b6cbc195/flexget/api.py#L27-L41) is something I came up with, anyone with more restplus experience know if it's a good idea?

Allows registering jsonschemas with `api.schema(name, schema)` (an analogue for api.model, but for json schemas.) The returned model can then be used with `api.expect` (at least in theory, I have still not done very much testing)

(same project @stevezau is working on btw)

**Comment by noirbizarre** [comment]
Interesting !

Will look closer to it and maybe integrate it into the next release.

**Comment by stevezau** [comment]
Hey @noirbizarre, how are you going with this?

We have a hack/work around at the moment https://github.com/Flexget/Flexget/blob/develop/flexget/api/__init__.py#L71 which allows us to validate json schema and document the input schema (although it does not work very well for complex json schema types anyOf oneOf and Array)..

**Comment by stevezau** [comment]
Hi @noirbizarre,

Any updates on this? Are you planning to support this?

**Comment by stevezau** [comment]
@noirbizarre I can open a PR to support this? Just need to know you'll support it so i'm not wasting my time. please let me know.

**Comment by noirbizarre** [comment]
Hi !
Yes, you can and I'll be glad to merge it to add support for this if it's working.

You'll see I started moving some things to handle these customizations:
https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/resource.py#L67-L72
https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/swagger.py#L240-L274

**Comment by gazpachoking** [comment]
I haven't actually tried it yet, but I'm getting a proper PR ready.
https://github.com/noirbizarre/flask-restplus/compare/master...gazpachoking:schema_models

I redid the class hierarchy so that the `SchemaModel`s don't inherit things they don't support. @noirbizarre any initial thoughts? My inclination would be to rename the old `Model` to `FieldsModel`, and make what I currently have called `ModelBase` into just `Model`, but that wouldn't be backwards compatible.

I'll make a PR once I've actually tested it's working (and added some unit tests.)

**Comment by NateLove** [comment]
Just curious if there was any update to this?

**Comment by brandonfancher** [comment]
I second that. Any updates? Seems like it'd be a really useful feature for flask-restplus.

**Comment by stevezau** [comment]
I opened a PR: https://github.com/noirbizarre/flask-restplus/pull/165

It seems @noirbizarre is MIA tho.. :|
