### ISSUE TITLE
No way to configure .../swagger.json to go over HTTPS?

### ISSUE THREAD

**Issue by Iulian7** [noirbizarre/flask-restplus#54]
Hello,

I have an application deployed using Flask-RESTPlus. Everything works nicely when it goes over http, but soon as I switch to https, it can't load the swagger.json because it is making requests to http://host/swagger.json and not https://host/swagger.json

The endpoints are registered properly with blueprints, because if I manually go to https://host/swagger.json, I get the correct JSON. However, the generated swagger page tries to load the JSON from a http endpoint, instead of the correct https endpoint. 

Is there any way to fix this?

Thanks

**Comment by cdumay** [comment]
hi, i've got the same problem, i wrote this little monkey patch:

from flask.ext.restplus import Api
from flask import url_for

@property
def specs_url(self):
    """Monkey patch for HTTPS"""
    return url_for(self.endpoint('specs'), _external=True, _scheme='https')

Api.specs_url = specs_url

**Comment by noirbizarre** [comment]
Hi !

I have multiple instances working in both http and https without any problem.

I think this is related to Flask/Werkzeug and the way it handles https.

If you want https, you need to make sure your reverse-proxy is setting the `X-Forwarded-Proto` header properly.
If set, Flask/Werkzeug will set the `request.is_secure` to `True` (this is a good way to check this is correctly detected) and `url_for` will return https URLs (in the same request context).

The solution you provide should be working, but you won't be able anymore to work in http.

**Comment by noirbizarre** [comment]
After some research, you need to apply these:
http://flask.pocoo.org/docs/0.10/deploying/wsgi-standalone/#proxy-setups

The ``ProxyFix`` is what you need:
```python
from werkzeug.contrib.fixers import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app)
```

I works well (I don't know why it's not the default).

I modified the todo example to include it.

**Comment by frol** [comment]
@noirbizarre 

> I works well (I don't know why it's not the default).

There is a warning there explaining why it is not the default:

> Please keep in mind that it is a security issue to use such a middleware in a non-proxy setup because it will blindly trust the incoming headers which might be forged by malicious clients.

**Comment by d-kahara** [comment]
For anyone that's encountered this issue lately
This has **changed** 
>from werkzeug.contrib.fixers import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app)

**This is what you need:**
>from werkzeug.middleware.proxy_fix import ProxyFix
app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)

**Comment by j5awry** [comment]
This appears to be a refactor in Werkzeug 0.15.X series. This version is taken by flask >= 1.1.0

We should look at updating everything, along with compatibility notes.

**Comment by giosiragusa** [comment]
This is still not working for me.
I'm not sure what I'm doing wrong. 
How can I check that the ProxyFix is doing its job? Is ther a way to debug it?

**Comment by Angeluz-07** [comment]
> For anyone that's encountered this issue lately
> This has **changed**
> 
> > from werkzeug.contrib.fixers import ProxyFix
> > app.wsgi_app = ProxyFix(app.wsgi_app)
> 
> **This is what you need:**
> 
> > from werkzeug.middleware.proxy_fix import ProxyFix
> > app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)
> 
> @noirbizarre perhaps this could also be rectified in the todo example?

This change worked for me on deploying a flask-restplus app with gunicorn by using a docker image. And using Azure App service deploy.

**Comment by radiaph** [comment]
I don't have a deep understanding of this issue, so I apologize in advance if this question is misguided:

Why is it trying to construct an absolute URL for swagger.json?  Why can't it just use a relative URL  so that the request goes over whichever protocol was used to fetch the rest of the page?

**Comment by polymath1995** [comment]
> > For anyone that's encountered this issue lately
> > This has **changed**
> > > from werkzeug.contrib.fixers import ProxyFix
> > > app.wsgi_app = ProxyFix(app.wsgi_app)
> > 
> > 
> > **This is what you need:**
> > > from werkzeug.middleware.proxy_fix import ProxyFix
> > > app.wsgi_app = ProxyFix(app.wsgi_app, x_proto=1, x_host=1)
> > 
> > 
> > @noirbizarre perhaps this could also be rectified in the todo example?
> 
> This change worked for me on deploying a flask-restplus app with gunicorn by using a docker image. And using Azure App service deploy.

This worked for me.. Thanks..!

**Comment by mumerfarooq000** [comment]
>I don't have a deep understanding of this issue, so I apologize in advance if this question is misguided:

>Why is it trying to construct an absolute URL for swagger.json? Why can't it just use a relative URL so that the request goes >over whichever protocol was used to fetch the rest of the page?

exactly, other URLs are relative then why this one absolute :/
