### ISSUE TITLE
Response marshalling choices for fields.String

### ISSUE THREAD

**Issue by estebancortero** [noirbizarre/flask-restplus#545]
I'm a big fan of flask-restplus and use it to build my backend API. For request parsing, there is a convenient option `choices=()` within `parser.add_argument()`, which allows to specify allowed choices of a given argument. 

Is something similar available for response marshalling within `fields.String()` (within `api.model()`)? `choices` does not seem to work for response marshalling and I couldn't find anything in the docs.

**Comment by z4y4ts** [comment]
@estebancortero `fields.String()` accepts `enum` named argument, which seems to be doing what you want. List of strings works for me. I.e. it ends up in the Swagger documentation.

**Comment by estebancortero** [comment]
Perfect thanks! Shows up in swagger. Do you know what would happen if my server returns a response that doesn't match the `enum`?
