### ISSUE TITLE
Could any help me to figure out how to list all of the api and url?

### ISSUE THREAD

**Issue by hanleilei** [noirbizarre/flask-restplus#547]
Hello, 

I just want to list all of the url of api, just as we can see the swagger webpage on browser, I tried to find out the method and got this: http://flask.pocoo.org/snippets/117/ and https://stackoverflow.com/questions/13317536/get-a-list-of-all-routes-defined-in-the-app, and save all of them into a dict.

Could anyone share some more elegant method about it in flask_restplus package??

Great appreciate
Oliver

**Comment by hygorxaraujo** [comment]
You could achieve this with Flask only:
```
app = Flask(__name__)
endpoints = dict()
for rule in app.url_map.iter_rules():
    methods = rule.methods
    rule_url = str(rule)
    endpoints[rule_url] = methods
```

**Comment by hanleilei** [comment]
> You could achieve this with Flask only:
> 
> ```
> app = Flask(__name__)
> endpoints = dict()
> for rule in app.url_map.iter_rules():
>     endpoints[rule.rule] = rule.methods
> ```

thanks for late reply.
