### ISSUE TITLE
Parsing of a list of lists

### ISSUE THREAD

**Issue by tschm** [noirbizarre/flask-restplus#551]
Here's a little issue I struggle with:
data = {'series': [[1356998400000, 1673.78], [1357084800000, 1686.9], [1357171200000, 1663.95]}
Currently I do this the old-school way:

```
@api.route('/drawdown')
class Drawdown(Resource):
    def post(self):
        data = json.loads(request.data)
        assert isinstance(data, dict)
        assert "series" in data.keys()

        # series is an array [[t1,v1],[t2,v2],...]
        data = HighchartsSeries.parse(data["series"])
```

I thought I could take advantage of the 

```
parser = api.parser()
parser.add_argument('series', type=HighchartsSeries.parse, help='some series', required=True, location="form")
```

parser, but no luck so far...

**Comment by avilaton** [comment]
It looks like the data you are sending is missing a closing bracket `95]}` should be `95]]}`

This looks like a question better suited for stackoverflow. Also include a stack trace or more information about the error you are seeing so you receive help.

**Comment by SteadBytes** [comment]
@tschm are you still having issues with this?

**Comment by tschm** [comment]
Solved, sorry for not closing this. I use the following construction:
I parse incoming request.data via:
`HighchartsSeries.parse(value=json.loads(request.data))`
do my computations and via
`json.dumps(HighchartsSeries.to_json(x))`
and return a Response object.
The class HighchartsSeries looks like:
```
class HighchartsSeries(object):
    @staticmethod
    def to_json(series):
        return [[int(pd.Timestamp(t).value * 1e-6), float(value)] for t, value in series.dropna().items()]

    @staticmethod
    def parse(value):
        return pd.Series({pd.Timestamp(1e6 * int(v[0])): float(v[1]) for v in value})
```

**Comment by SteadBytes** [comment]
Great, glad you got it worked out - im going to close this issue now. If you have any other problems please don't hesitate to open another issue :smile:
