### ISSUE TITLE
No way to set base endpoint?

### ISSUE THREAD

**Issue by andresmrm** [noirbizarre/flask-restplus#56]
Hello! I'm trying to set the base endpoint using what the docs says here (parameter `endpoint`):
https://github.com/noirbizarre/flask-restplus/blob/8593a06474a474ceea4e3702b2582954e0f9c326/flask_restplus/api.py#L61

But I'm getting an error, for this parameter seems not used anymore:
https://github.com/noirbizarre/flask-restplus/blob/8593a06474a474ceea4e3702b2582954e0f9c326/flask_restplus/api.py#L93-L97

Tried using the `default` parameter, but seems to have no effect...

**Comment by noirbizarre** [comment]
Hi !
You're right, I need to udate the API docstring.

Want do you want to do ?

If you want a common prefix, you can simply register the API on a Blueprint:
```python
from flask import Flask, Blueprint
from flask.ext.restplus import Api

app = Flask(__name__)
blueprint = Blueprint('api', __name__, url_prefix='/api') 
api = Api(blueprint)

app.register_blueprint(blueprint)
```
All your endpoints will be prefixed by '``api.``' and all your URLs by ``/api``.

**Comment by andresmrm** [comment]
Thanks for the reply. I already solved it using the `Blueprint(endpoint, ...`, as you say.
And thanks you again for Flask-Restplus. =)

**Comment by noirbizarre** [comment]
You're welcome !

**Comment by pandey-mohit** [comment]
@noirbizarre. After implementing it, I am unable to use api.route method of flask_restful(https://flask-restplus.readthedocs.io/en/stable/quickstart.html), though api.add_resource works fine.

Is it because of Blueprint as it also have a route method or am I missing something??
