### ISSUE TITLE
applying nginx with ssl resulting swagger says No API definition provided.

### ISSUE THREAD

**Issue by bilalbayasut** [noirbizarre/flask-restplus#565]
I have implemented nginx and ssl , but when I run the swagger UI it says No API definition provided

**Comment by bilalbayasut** [comment]
Fixing this by do monkey patching 
```
# monkey patch courtesy of
# https://github.com/noirbizarre/flask-restplus/issues/54
# so that /swagger.json is served over https
if os.environ.get('HTTPS'):
    @property
    def specs_url(self):
        """Monkey patch for HTTPS"""
        return url_for(self.endpoint('specs'), _external=True, _scheme='https')

    Api.specs_url = specs_url

```
hope it helps

**Comment by livecloud** [comment]
Curious, which release will include this fix?

**Comment by ibt23sec5** [comment]
Use ProxyFix:
```
from werkzeug.middleware.proxy_fix import ProxyFix

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
```

**Comment by ibt23sec5** [comment]
Use proxyFix:

```
from werkzeug.contrib.fixers import ProxyFix
app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
```

**Comment by SteadBytes** [comment]
Yep @ibt23sec5 has the answer 👍

**Comment by MartinThoma** [comment]
Is this still an issue in https://github.com/python-restx/flask-restx or was it fixed there?

**Comment by ziirish** [comment]
As discussed several times, I don't think this is an issue with Flask-restplus/restx as the werkzeug's ProxyFix is here to handle such case.

So no, for now it's not "fixed" in flask-restx either.

Now if someone has an actual problem/bug with this, I'm okay to discuss a change in flask-restx.
Feel free to open an issue with as much details as you can.
