### ISSUE TITLE
Model "required=True" is ignored on POST request

### ISSUE THREAD

**Issue by Lomomn** [noirbizarre/flask-restplus#569]
I have a model defined like this:

```python
model = api.model('User', {
    'username': fields.String(required=True, description='Username for the user'),
    'password': fields.String(required=True, description='Password for the user')
})
```

I am using a route defined like this:

```python
@api.route('/users')
class UsersResource(Resource):
    @api.expect(model)
    @api.marshal_with(model)
    def post(self):
        '''Create a new user'''
        data = api.payload
        return {'username': data['username'], 'password': data['password']}    
```

When I use Swagger UI to test my resource with a POST, I was expecting the correct response (400, 422 etc), but instead the method body tries to run and causes an error and then returns 500 to Swagger UI:

```bash
backend_1   |   File "./api/__init__.py", line 19, in post
backend_1   |     return {'username': data['username'], 'password': data['password']}
backend_1   | KeyError: 'password'
```
Is my understanding of the documentation incorrect?

**Comment by Levy96** [comment]
Hi.  :)
`The validation behavior can be customized globally either by setting the RESTPLUS_VALIDATE configuration to True or passing validate=True to the API constructor.`  referred from [doc](https://flask-restplus.readthedocs.io/en/latest/swagger.html#the-api-expect-decorator)
You can modify your code as ``@api.expect(model, validate=True)``.

**Comment by Lomomn** [comment]
Thanks, not sure how I misunderstood that. :)
