### ISSUE TITLE
url_for with blueprints using namespaces

### ISSUE THREAD

**Issue by Lomomn** [noirbizarre/flask-restplus#581]
I'm following this format: https://flask-restplus.readthedocs.io/en/stable/scaling.html?highlight=url_for#multiple-apis-with-reusable-namespaces   

I want to use url_for with this, but it's not clear what I should be importing and using with url_for.

**Comment by SteadBytes** [comment]
`url_for` is imported from Flask:
```python
from flask import url_for
```
The example in the docs [here](https://flask-restplus.readthedocs.io/en/stable/scaling.html?highlight=url_for#use-with-blueprints) creates a blueprint called `'api'`. Thus when using `url_for`, the route name passed to it is prefixed with the blueprint name - `'api'` as shown in the example you linked.

Does that help?
