### ISSUE TITLE
How to set base url for swagger with flask_restplus?

### ISSUE THREAD

**Issue by vivaldus** [noirbizarre/flask-restplus#595]
I posted this question to [SO](https://stackoverflow.com/questions/54837636/how-to-set-base-url-for-swagger-with-flask-restplus) but haven't got any responses yet. In short: is there a way to get `flask_restplus` to serve up the `swaggerui` from other than the root url? (I'm trying to serve a flask api through an apache server using ProxyPass.)

**Comment by SteadBytes** [comment]
Take a look [here](https://flask-restplus.readthedocs.io/en/stable/swagger.html#customization). You can pass a `doc` kwarg when creating the `Api` to specify the Swagger base:
```python
app = Flask(__name__)
api = Api(app, doc='/my_custom_swagger_path/')
```
