### ISSUE TITLE
How to use api.expect with validate=True for own date-time type?

### ISSUE THREAD

**Issue by nobodyman1** [noirbizarre/flask-restplus#603]
I wan´t to check my own date format, for example `'2019-03-07T15:40:01'`.
Here is how to generate it:
```
from datetime import datetime
datetime.now().isoformat(timespec='seconds')
```
I found some useful information in issue #204.

api object:
```
from jsonschema import FormatChecker
api = Api(blueprint,
    title='...',
    format_checker=FormatChecker()
)
```

data model:
```
testdata = api.model('TestData', {
    'timestamp': fields.DateTime(required=True)
})
```

test class:
```
@api.route('/test', methods=["post"])
class Test(Resource):
    @api.expect(testdata, validate=True)
    def post(self):
        '''Test'''
        return
```

If I test it with
```
{
  "timestamp": "2019-03-01T11:22:34"
}
```
it fails, because the `date-time` format requires the letter `Z` at the end.
But I wan´t to use my own format.

- I think I have to extend the FormatChecker with a new method. Any hints how to implement this?
- Where is the mapping between `fields.DateTime` and `date-time` format?

**Comment by SteadBytes** [comment]
This can be achieved by implementing a custom field:
```python
class MyDate(fields.DateTime):
    __schema_format__ = "my_date"
    __schema_example__ = "2019-03-07T15:40:01"

    def parse(self, value):
        if value is None:
            return None
        try:
            return datetime.strptime(value, "%Y-%m-%dT%H:%M:%S")
        except ValueError as e:
            raise ValueError("Unsupported format for MyDate") from e

    def format(self, value: datetime):
        try:
            value = self.parse(value)
            return value.isoformat(timespec="seconds")
        except ValueError as e:
            raise fields.MarshallingError(e)
```

Then use it in your model:
```python
testdata = api.model("TestData", {"timestamp": MyDate(required=True)})
```

**Comment by SteadBytes** [comment]
Sorry, I misunderstood your requirements slightly. The above solution will validate when marshalling data using the custom field. Validation of input data is handled by `jsonschema` as you correctly described in your issue description.

To handle a custom format, a function can be decorated with `FormatChecker.checks` to be used when validating a specific format (in this case `MyDate.__schema_format__` which is `"my_date"`).
```python
from jsonschema import FormatChecker

format_checker = FormatChecker()

# format name is same as MyDate.__schema_format__
@format_checker.checks("my_date", ValueError)
def my_date_check(value):
    datetime.strptime(value, "%Y-%m-%dT%H:%M:%S")
    return True

# register api using custom FormatChecker
api = Api(blueprint, title="...", format_checker=format_checker)
```

Together with the custom `MyDate` model, input validation and marshalling validation should be handled :crossed_fingers:

**Comment by nobodyman1** [comment]
Great work! Everything is working as expected!

**Comment by SteadBytes** [comment]
Awesome! Glad to help 👍
