### ISSUE TITLE
Json encoder not working 

### ISSUE THREAD

**Issue by SmitSheth** [noirbizarre/flask-restplus#608]
Getting this error : TypeError: Object of type 'ObjectId' is not JSON serializable

```
class JSONEncoder(json.JSONEncoder):
    ''' extend json-encoder class'''

    def default(self, o):
        if isinstance(o, ObjectId):
            return str(o)
        if isinstance(o, set):
            return list(o)
        if isinstance(o, datetime.datetime):
            return str(o)
        return json.JSONEncoder.default(self, o)

app = Flask(__name__)
app.config['MONGO_URI'] = config['databaseUrl'] +config['databaseName']
app.json_encoder = JSONEncoder
mongo = PyMongo(app)

api = Api(app=app,version='1.0', title='Drishti API',
    description='Apis description')

@api.route('/data')
class Test(Resource):
def get(self):
        query = {}
        result = list(mongo.db.data.find(query))
        return result, 200
```

**Comment by SteadBytes** [comment]
Flask Restplus doesn't use the JSON encoder from Flask therefore your custom `JSONEncoder` isn't getting called. It would need to use Flask's `jsonify` method to do that.

You could implement a custom field and use response marshalling to format the values to the correct types before serialisation. Just as a small example, I'm assuming your `mongo.db.data.find(query)` returns objects with the format `{"_id": ObjectId, "date": datetime, "items": set}`:
```python
from flask_restplus import fields

class ObjectIdField(fields.Raw):
    def format(self, value):
        if isinstance(value, ObjectId):
            return str(ObjectId)
        else:
            raise MarshallingError()

class SetField(fields.Set):
    def format(self, value):
        if isinstance(value, set):
            return list(value)
        else:
            raise MarshallingError()


model = {
    "_id": ObjectIdField,
    "date": fields.DateTime
    "items": SetField
}

@api.route('/data')
class Test(Resource):
    @api.marshal_with(model, as_list=True)
    def get(self):
        query = {}
        result = list(mongo.db.data.find(query))
        return result, 200
```
Before serialisation, `marshal` will format the values as defined by the fields in the `model`. In this case, they are converted to values which can be JSON serialised by default :smile:

**Comment by SmitSheth** [comment]
Okay thanks for the solution!

**Comment by ozeebee** [comment]
Hi, 
Does it mean there is no way to format a specific type whatever the response structure ?

I have endpoints that return dynamic data structures that contain `datetime` values.
I cannot use a 'model' or 'field' since the structure may change depending on the request.
Is it possible to configure the framework (Flask or Flask RESTPlus) to format a specific data type ??

JSONEncoder looked the best way to do that...

Thanks!

**Comment by ozeebee** [comment]
Ok, answering my own question: solution is to define a custom `JSONEncoder` and configure the Flask application with the `RESTPLUS_JSON` key, example:
```
class Config:
    ...
    RESTPLUS_JSON = {'cls': DateTimeEncoder}
    ...

app = Flask(__name__)
app.config.from_object(Config)
```

**Comment by yankeexe** [comment]
@SteadBytes @SmitSheth You'll also have to call the `ObjectId` to return proper str. 

```py
class ObjectIdField(fields.Raw):
    def format(self, value):
        if isinstance(value, ObjectId):
            return str(ObjectId()) # <- this line
        else:
            raise MarshallingError()
```

**Comment by ghandic** [comment]
For those upgrading to flask_restx just use
```python
app = Flask(__name__)
app.config["RESTX_JSON"] = {"cls": CustomJSONEncoder}
```
