### ISSUE TITLE
Documenting Input Body

### ISSUE THREAD

**Issue by awiddersheim** [noirbizarre/flask-restplus#61]
I'm having trouble getting JSON body inputs documented in swagger and working the way I want.

My end goal is to setup a `POST` request that is JSON that looks like `{"type": "foobar"}`.

I want to be able to validate the input coming in so I first tried doing this using the following parser:

```
parser = api.parser()

packages_post = parser.copy()
packages_post.add_argument(
        "data",
        required=True,
        location="json",
        help="The type of package to create."
)
```

The problem with this method is it doesn't really document what the schema looks like very well:

![image](https://cloud.githubusercontent.com/assets/3237256/9373067/ec663dac-46b3-11e5-9157-b031edb0a2f4.png)

I then went with a model and used the `body` option in `api.doc()` which did document things well but doesn't do validation:

```
package = api.model(
        "Package",
        {
                "type": fields.String(
                        description="The type of package to create.",
                        required=True
                )
        }
)
```

![image](https://cloud.githubusercontent.com/assets/3237256/9373084/2ae2410c-46b4-11e5-87a3-019ebafeb82e.png)

Alright, so I figure I can use a combination of the two to get both the right documentation and validation:

```
package = api.model(
        "Package",
        {
                "type": fields.String(
                        description="The type of package to create.",
                        required=True
                )
        }
)

parser = api.parser()

packages_post = parser.copy()
packages_post.add_argument(
        "package",
        type=package,
        location="json"
)
```

I noticed this pattern in the tests and it almost works however now the input needs to be `{"package": {"type": "foobar"}}` which doesn't get documented very well.

The only way I can see to get things to work the way I want is to define both a parser and a model with the same exact information which is a bit ugly and redundant.

Is there something I might be missing to make this a bit better? Perhaps something I can look at adding to make this possible?

**Comment by awiddersheim** [comment]
After reviewing I think the best solution would be to extend `parser_to_params()`. It would need to turn things coming from `location='json'` into a model and register it instead of treating each argument as it's own individual thing.

**Comment by awiddersheim** [comment]
Actually, it is a bit more complicated than that.Making a model without using `api.model()` would be pretty hard. I also noticed that providing a model as the type to a parser doesn't actually validate it as I would expect. Here is the code currently:

```
package = api.model(
        "Package",
        {
                "type": fields.String(
                        description="The type of package to create.",
                        required=True
                )
        }
)

parser = api.parser()

packages_post = parser.copy()
packages_post.add_argument(
        "data",
        type=package,
        location="json"
)
```

If I provide `{"typ000": "foobar"}` then `type` will just be `None`.

**Comment by noirbizarre** [comment]
Hi !

Sorry for the lack of response.

You have to distinguish between what's provided by the swagger specifications and what's Swagger UI is being able to display.

Right now, Swagger UI only display a single textarea field for JSON input (see: #11).

You're right, there is no JSON input payload validation yet, but I will provide this feature (very) soon.

In the meantime, I advise you to write this:
```python
package = api.model('Package', {
    'type': fields.String(description="The type of package to create.", required=True)
})

class MyResource(Resource):
    @api.doc(expect=package)
    def get(self):
         '''Some doc'''
         data = request.json
         ''' do some validation'''
```
It will ensure documentation is well set.

In my experience, I prefer to keep the parser for querystring parsing.
RequestParser is not very effective on parsing `application/json` payloads.
It is meant to parse the root level of JSON payloads, not to parse an entire model (sadly).

For your alternative to work you need to write it like that:
```python
packages_post = api.parser()
packages_post.add_argument(
     'type',
     type=str,
     description='The type of package to create',
     required=True)

class MyResource(Resource):
    @api.doc(parser=packages_parser)
    def post(self):
         '''Some doc'''
         args = packages_post.parse_args()
         typ = args['type']
```

**Comment by awiddersheim** [comment]
Thanks for the response!

 > You're right, there is no JSON input payload validation yet, but I will provide this feature (very) soon.

That sounds awesome. I'll make due for now but seems like we are on the same page so I anxiously await your improvements. Love this package btw.

**Comment by awiddersheim** [comment]
Sorry, one last question. What does the following do from your example?

`@api.doc(expect=package)`

Doesn't seem like it adds anything to swagger.

**Comment by awiddersheim** [comment]
Looked at docs and found what you were trying to describe:

http://flask-restplus.readthedocs.org/en/stable/documenting.html#documenting-with-the-api-expect-decorator

**Comment by noirbizarre** [comment]
Thanks !

Sorry for the mistake, it was:
```
@api.expect(package)
def get(self):
    ...
```
Expect will set expected input in Swagger.

When validation will be available, it will also perform input validation (optional)

**Comment by awiddersheim** [comment]
Awesome. So excited.

**Comment by noirbizarre** [comment]
I think this is one is fixed
