### ISSUE TITLE
extra_requires[dev] does not exist

### ISSUE THREAD

**Issue by j5awry** [noirbizarre/flask-restplus#617]
Issue: running `pip install -e .[dev]` works, but doesn't install the dev requirements. this is due to the missing extra, dev

```
pip install .[dev]
Processing /Users/jchittum/dev01/flask-restplus
  flask-restplus 0.12.2.dev0 does not provide the extra 'dev'
```

clearly missing in setup.py

```
    extras_require={
        'test': tests_require,
        'doc': doc_require,
    },
```

Also, develop.pip contains an entry that is not compatible with installing in this fashion (even with the very useful parser in setup.py)

```
-e .[test]
invoke==0.21.0
flake8==3.5.0
readme-renderer==17.2
tox==2.9.1
```

**Comment by hygorxaraujo** [comment]
Hi @j5awry, I had already reported this in #560 and created a PR #577. Could you take a look at it?

**Comment by j5awry** [comment]
commented on the PR. just checked the code, and it appears to keep the `-e .[test]` in the list. that would cause an error on attempting to install. 

I'm also a little paranoid about regex -- but that's just me. Your approach maintains the `pip install -r requirements/develop.pip` to work for development purpose which mine does not.

**Comment by j5awry** [comment]
Duplicates 560. Implementation differs from proposal in 577. Closing all.

merged PR 618
