### ISSUE TITLE
@api.doc can't handle docstrings from decorated functions

### ISSUE THREAD

**Issue by thomas-maurice** [noirbizarre/flask-restplus#62]
I think I have spot a bug which operates as follows. If I pass the @api.doc decorator a function that has already been decorated several times, it fails to set its docstring in the swagger summary bar. Exemple : 

```
@ns_groups.route(
    '',
    endpoint='group',
)
class Group(Resource):
    @api.doc(parser=get_parser)
    @auth.login_required
    def get(self):
        """Retrieves a group"""

        args = get_parser.parse_args()
        ... some more code
```

Will give me the correct Swagger documentation, whereas:

```
    @api.doc(parser=delete_parser)
    @auth.login_required
    @admin_required
    def delete(self):
        """Deletes a group
        """

        args = delete_parser.parse_args()
        ... some more code
```

Will not set anything, regardless where in the decorator chain I put @api.doc.

Altough it works if I only use two decorators.

**Comment by noirbizarre** [comment]
Hi! 

In fact, it depends on your previous decorators.
If the decorator only returns the decorated function, it will work.
If not, I have no way of determining the docstring of the original function.

As flask-restful decorators always return the original function, it's safe to us them as first applied decorator (last written).

In your case, it must be the `@admin_required` decorator which does not return the original function and so, your second example should work if written like:
```python
@admin_required
@auth.login_required
@api.doc(parser=delete_parser)
def delete(self):
    """Deletes a group"""
    args = delete_parser.parse_args()
    ... some more code
```
