### ISSUE TITLE
Improve Development and Contribution Docs

### ISSUE THREAD

**Issue by j5awry** [noirbizarre/flask-restplus#624]
- [x] Ensure CONTRIBUTION documentation explains all dev steps fully
- [x] Ensure CONTRIBUTION doc is updated to explain pull request review standards
  - [x] An issue should be created *before* a PR is submitted
  - [x] number of ok's from maintainers (at least 1, preference for 2 on larger features)
  - [x] maintainers should not merge their own requests
  - [ ] Add issue/PR templates
- [x] Update LICENSE doc as required by Akamai so I (and other Akamai employees) can contribute
  - [x] Add Akamai to LICENSE as "Other Contributions Copyright Akamai Technologies"
- [x] Update CONTRIBUTION doc to explain copyright additions, and how to properly add contributions

**Comment by ziirish** [comment]
I think #622 might be a good start. Feel free to update/improve it.

**Comment by j5awry** [comment]
Pushing what I've got now. I didn't add an issue/PR template. Not sure how we want to handle that one...I'll take feedback and add it to the PR

**Comment by j5awry** [comment]
Going to save the last task -- issue/PR templates. We can finalize that later.
