### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_.indexOf') when using oAuth2

### ISSUE THREAD

**Issue by robertofalk** [noirbizarre/flask-restplus#635]
Hi,

I'm getting an error in the javascript console when trying to use oAuth2 as authorization:
TypeError: undefined is not an object (evaluating '_.indexOf')

```python
import os
from flask import Flask
from flask_restplus import Resource, Api

app = Flask(__name__)

authorizations = {'oauth2': {
    'type': 'oauth2',
    'flow': 'accessCode',
    'tokenUrl': 'https://authentication.com/oauth/token',
    'scopes': {
        'read': 'Grant read-only access',
        'write': 'Grant read-write access'}
    }
}

api = Api(app, version='1.0', authorizations=authorizations, security={'oauth2': 'read'})

@api.route('/hello')
class HelloWorld(Resource):
    def get(self):
        return "It works!!"

if __name__ == '__main__':
    app_port = int(os.getenv('PORT', 5000))
    app.run(host='0.0.0.0', port=app_port, debug=True)
```

The popup to enter the clientid and clientsecret is correctly shown, but when I press the "Authorize" button, nothing happens. Checking the javascript console, I see the error above.
Nothing is shown on the flask (server) side, so I assume the application is not even called and this is a pure javascript error.

Thanks,
Roberto Falk

Flask              1.0.2   
flask-restplus     0.12.1
Browser: Safari (macOS)

**Comment by robertofalk** [comment]
Hi, really no comments on this? should I assume this is a bug that won't be solved and that's it?

**Comment by SteadBytes** [comment]
Sorry @robertofalk , we try to address issues as soon as possible however we are only a small team of maintainers - your patience is appreciated. I will look into this now, I suspect it's a configuration issue with Swagger UI JS library

**Comment by SteadBytes** [comment]
I have identified the issue, the `accessCode` authorisation flow requires both the `tokenUrl` and `authorizationUrl` configurations. From the [Swagger docs](https://swagger.io/docs/specification/authentication/oauth2/#examples):
> The authorization flow uses authorizationUrl, tokenUrl and optional refreshUrl.

The `authorizations` dictionary in your example needs to include this:
```python
authorizations = {
    'oauth2': {
        'type': 'oauth2',
        'flow': 'accessCode',
        'tokenUrl': 'https://authentication.com/oauth/token',
        'authorizationUrl': 'https://authentication.com/authorization', # REQUIRED
        'scopes': {
            'read': 'Grant read-only access',
            'write': 'Grant read-write access',
        },
    }
}
```
I can see that our documentation for this is misleading as it only includes the `tokenUrl`, I will make sure it gets updated :+1: 

Please let me know if there are further issues :smile:

**Comment by robertofalk** [comment]
Hi @SteadBytes,
thanks for your response. Glad to hear that it's just a minor thing in the documentation.

Do you understand what's the meaning of the authorizationUrl field? in the oAuth flow, I do a post request to the tokenUrl using the clientId and clientSecret, and I get a token.

I tested, but instead of getting the token, the swagger page forwards me to the authorizationUrl.

**Comment by robertofalk** [comment]
ok, sorry, this is because of the accessCode flow I'm using. I'm checking how to change it for Client Credentials, that applies to my use case. I'll post here my findings.

**Comment by SteadBytes** [comment]
Yes @robertofalk, the Swagger documentation I posted previously is the best place to look. It contains details of each different flow type and the necessary configuration. I have created a PR #646 to include more detail on this in our documentation and to make sure the example is correct. Do you have any comments on the PR?

**Comment by robertofalk** [comment]
I changed for 'flow': 'clientCredentials' and now it's working. 
The PR looks way clearer now, no additional comments from my side. Thanks all the support.

**Comment by SteadBytes** [comment]
Great thank you - you're more than welcome!
