### ISSUE TITLE
How to validate custom field

### ISSUE THREAD

**Issue by daixiang0** [noirbizarre/flask-restplus#641]
I create a custom field:
```
class Duration(fields.String):
    """
    Duration field
    """
    __schema__ = {
        'type': 'string',
        'format': 'duration',
        'example': '1s'
    }
```
Use it in request:
```
test_request.add_argument('metric', type=Duration, required=False, default='1m', help='The range of metric')
```

Add `validate=True` in `api.expect`:
```
@api.expect(test_request, validate=True)
```

Add custom `format_check`:
```
format_checker = FormatChecker()

duration_regex = re.compile(r'[0-9]+[smhd]')


@format_checker.checks("duration", ValueError)
def validate(value):
    if not duration_regex.match(value):
        return False
    return True


api = Api(version='1.0',
          title='test',
          format_checker=format_checker)
```

But test with `http://localhost:5000/api/v1/test/metric=15maa` still pass, i want it raise ValueError since `15maa` do not match regex.

**Comment by daixiang0** [comment]
My env:
```
Flask==1.0.2
flask-restplus==0.12.1
```

**Comment by SteadBytes** [comment]
`15maa` does match your regex - take a look [here for a demo](https://regex101.com/r/MfYVLl/1) - as it'll match the `15m` part. If you're intending to enforce the string end after one of `[smhd]` you could use a `$` to indicate the end of the string- `[0-9]+[smhd]$`

**Comment by daixiang0** [comment]
Thanks, that works.
Is there any other way to do validate?
Put all validate check before api init looks ugly, can i custom field with build-in validate func?

**Comment by daixiang0** [comment]
@SteadBytes changed but not work

**Comment by SteadBytes** [comment]
Sorry @daixiang0, the regex being incorrect was only part of the problem - I didn't quite study your use case close enough. For validating request arguments (using `reqparse.RequestParser`), the classes in `flask_restplus.fields` are not used - these are for validating and formatting `flask_restplus.Model`s. For your use case, you need to define an input type using a function - [here's the docs for this](https://flask-restplus.readthedocs.io/en/stable/parsing.html#advanced-types-handling). You don't need to use a `jsonschema.FormatChecker`, here's a full working example:

```python
import re

import flask

from flask_restplus import Api, reqparse, Resource


DURATION_RE = re.compile(r'[0-9]+[smhd]$')

app = flask.Flask(__name__)

api = Api(app, version='1.0', title='test')


def duration(value):
    if not DURATION_RE.match(value):
        raise ValueError('Invalid duration format')
    return value


duration.__schema__ = {
    "type": "string",
    "format": "duration",
}

parser = reqparse.RequestParser()
parser.add_argument(
    'metric',
    type=duration,
    required=False,
    location="args",
    default='1m',
)


@api.route("/test")
class TestEndpoint(Resource):
    @api.expect(parser, validate=True)
    def get(self):
        args = parser.parse_args()
        return {"metric": args.metric}


if __name__ == '__main__':
    app.run(debug=True)
```

### Example requests

Default metric value:
```bash
$ curl http://localhost:5000/test     
{
    "metric":"1m"
}
```

Valid metric value:
```bash
$ curl http://localhost:5000/test\?metric\=15m
{
    "metric":"15m"
}
```

Invalid metric value:
```python
curl http://localhost:5000/test\?metric\=15maa
{
    "errors":{
        "metric":"Invalid duration format"
    },
    "message":"Input payload validation failed"
}
```

Please let me know if that is your intended usage :)

**Comment by daixiang0** [comment]
oops, i misunderstand how to customize field. Now it works.
The duration type is common in Golang, see as https://golang.org/pkg/time/#ParseDuration.
I want to package prometheus in my app so i need to handle this type.
Thanks!

**Comment by SteadBytes** [comment]
That's fine, glad to get it working! :+1:

**Comment by andilabs** [comment]
@SteadBytes is there any way to define custom field without using RequestParser, which in docs is depreciated, despite the whole project is rather unmaintained anyway?

**Comment by SteadBytes** [comment]
@andilabs No, not that's built in to flask-restx at least.

Apologies for the lack of progress on this project. Personally I have had little time to dedicate to it recently and I think that also goes for the other maintainers.
