### ISSUE TITLE
RequestParser() for complex, nested structure

### ISSUE THREAD

**Issue by dstrigl** [noirbizarre/flask-restplus#642]
Any hint how to formulate/use the `reqparse.RequestParser()` to parse the following complex, nested list-of-list-of-dict "entries" structure?

```
{ "entries": [
    [{'end': '11:15', 'start': '09:45', 'state': 1},
     {'end': '16:15', 'start': '13:45', 'state': 2},
     ...
    ],  # day 0
    [{'end': '01:15', 'start': '00:45', 'state': 2},
     {'end': '06:15', 'start': '05:45', 'state': 3},
     ...
    ],  # day 1
    [{'end': '21:15', 'start': '20:45', 'state': 2},
     {'end': '22:15', 'start': '21:45', 'state': 0},
     ...
    ],  # day 2
    ...
    ]}
```

I would like to use the `reqparse.RequestParser()` to validate the received JSON data, like:
```
time_prog_parser = reqparse.RequestParser()
...
time_prog_parser.add_argument("entries", type=list, location="json")
...
args = time_prog_parser.parse_args(strict=True)
```
but don't know exactly how to formulate the `add_argument(...)` calls to get a valid parser for the upper structure.

Thanks and regards,
Daniel.

**Comment by wowditi** [comment]
Hey Daniel,

There is no need to use a request parser for this purpose. Assuming you are using the @api.expect decorator you can use the validate=True parameter (or have set it to always validate the json input in either the config or the api definition). You can simply call api.payload to get the parsed data.
For example:
```
@api.except(YourModel, validate=True)
def put():
    parsed_input_as_dict = api.payload
```
If you want to disallow additional properties have a look at: https://github.com/noirbizarre/flask-restplus/issues/241.

The requestparser is also going to be delete (source: https://flask-restplus.readthedocs.io/en/stable/parsing.html), therefore it is advisable not to use it.

I hope this helps you,
Niels

**Comment by dstrigl** [comment]
Hi Niels,

thanks for your help!

Regards,
Daniel.

**Comment by aqibgatoo** [comment]
I would like to know then how to validate `Enum` in `api.model`  case as there is no `fields.Enum`

**Comment by wowditi** [comment]
You use `fields.String` and fill the `enum` parameter.
