### ISSUE TITLE
Delete old branches

### ISSUE THREAD

**Issue by RemiDesgrange** [noirbizarre/flask-restplus#664]
I saw in some PR that you don't suppress branches after merging : 

![image](https://user-images.githubusercontent.com/13271765/60866584-fe477c00-a228-11e9-8a91-ad1206ccb40e.png)

What do you think about deleting old branches that have been merged ?

Thanks

**Comment by ziirish** [comment]
I'll do some cleanup, thanks

**Comment by ziirish** [comment]
done
