### ISSUE TITLE
Tests not in tarball

### ISSUE THREAD

**Issue by smarlowucf** [noirbizarre/flask-restplus#674]
It would be helpful to add `tests` dir to manifest. This is mainly for downstream packaging. While the tests can be seen passing in travis it's nice to run the test suite inside each image version that it will be packaged for. This ensures the package runs against the package dependency versions which are provided in each image.

For now pulling the tarball from GitHub does provide the tests dir.

**Comment by j5awry** [comment]
We are discussing this internally, but at this time, we're leaning towards not including tests in the in the package.
