### ISSUE TITLE
How do I do post a batch of resources?

### ISSUE THREAD

**Issue by RAbraham** [noirbizarre/flask-restplus#688]
Hi,
Thanks for this great library. I had a question about batch posts. I have lots of data coming in through our api for a particular resource and it's expensive to send each datum individually. How do I do batch posts in one request while integrating with the restplus architecture? If you could point me to some examples, I would be grateful.

Thanks,
Rajiv

**Comment by SteadBytes** [comment]
Thanks for using Flask-RESTPlus! Just to clarify, do you mean that you currently have an API endpoint which receives data one item at a time and you would like to have users send multiple items at once? For example:
- Current behaviour - users make multiple requests:
```

POST /my-endpoint
{"data": 1234}

POST /my-endpoint
{"data": 5678}

POST /my-endpoint
{"data": 91011}
```
- Desired behaviour - users can send all items in single request
```
POST /my-endpoint
[{"data": 1234}, {"data": 5678}, {"data": 91011}]
```

**Comment by RAbraham** [comment]
Hi @SteadBytes, thanks for replying.

Yes, exactly, how do I do that using REST conventions and within the restplus framework, instead of making a separate flask endpoint which has no reference to restplus?

**Comment by j5awry** [comment]
This is achievable now, if you're talking bulk data that gets rendered as an array. What SteadBytes posted is valid JSON. quick snippet:

```
# namespace
ns = api.namespace('api/v1/test', description='test')
# a model for the dict in the list
LIST_MODEL = {
    "value1": fields.String(),
    "value2": fields.String(),
    "value3": fields.String()}
# make the mode
model_four = ns.model(
    "listversion",
    LIST_MODEL
)

# endpoint
@ns.route("/list")
class ListModel(Resource):
    @ns.expect([model_four])
    @ns.response(201, "Created")
    def post(self):
        for item in api.payload:
            log.error(item)
        return 201
```

you can verify with Try It Now or a curl:

```
curl -X POST "http://127.0.0.1:5000/api/v1/test/list" -H "accept: application/json" -H "Content-Type: application/json" -d "[ { \"value1\": \"1\", \"value2\": \"2\", \"value3\": \"3\" }, { \"value1\": \"4\", \"value2\": \"5\", \"value3\": \"6\" }, { \"value1\": \"7\", \"value2\": \"8\", \"value3\": \"9\" }]"
```

**Comment by j5awry** [comment]
Also, the Swagger documentation rightly shows it as a list of a model. 

<img width="1389" alt="Screen Shot 2019-08-22 at 11 20 21 AM" src="https://user-images.githubusercontent.com/8875872/63531791-e113f780-c4ce-11e9-96af-d54cc23a78c2.png">

**Comment by SteadBytes** [comment]
Thanks @j5awry , you beat me to it! :smile: Does that help @RAbraham ?

**Comment by RAbraham** [comment]
@j5awry @SteadBytes Thanks a ton! That is what I wanted. Another question, the response format still displays as the example value, the model for a single entity in the batch. I could either send `a)` a list of responses each corresponding to a row in the batch request `b)` A response dictionary which is different from the model for the single entity as it is now. For e.g. since it is a batch, to save space, I could return just the ids created for each entity in the bulk request. Are any of the options possible? If not, it's all good, then maybe I can mention it in text somewhere?

<img width="579" alt="image" src="https://user-images.githubusercontent.com/214189/63553470-77b0da80-c508-11e9-81ee-4b444a0869f4.png">

**Comment by SteadBytes** [comment]
@RAbraham If you look closely at the example @j5awry gave, the `expect` decorator is given a `list` argument `@ns.expect([model_four])`, that will show the model within an array in the Swagger model:
![image](https://user-images.githubusercontent.com/14834132/63633397-f9575400-c63f-11e9-8be4-103d58de81b4.png)

If instead you pass the the model to`expect` without wrapping it in the `list` i.e. `@ns.expect(model_four)` the Swagger model will show the single model as in your screenshot:
![image](https://user-images.githubusercontent.com/14834132/63633411-315e9700-c640-11e9-9ba5-c222350d5c6d.png)

Does that help?

**Comment by SteadBytes** [comment]
Changing the request input to take a list will not change the output. If you have a response model defined and want to return a list of those objects, you can use the `@marhsal_list_with()`. Taking @j5awry 's example from before:
```python
# namespace
ns = api.namespace('api/v1/test', description='test')
# a model for the dict in the list
LIST_MODEL = {
    "value1": fields.String(),
    "value2": fields.String(),
    "value3": fields.String()}
# make the mode
model_four = ns.model(
    "listversion",
    LIST_MODEL
)

# endpoint
@ns.route("/list")
class ListModel(Resource):
    @ns.expect([model_four])
    # specifies the response body to be a list of model_four
    @ns.marshal_list_with(model_four)
    def post(self):
        # returning the input payload for simplicity
        return api.payload
```

The example response model should now show a list:

![image](https://user-images.githubusercontent.com/14834132/63967260-ed7eee00-ca94-11e9-8949-0207f2d94687.png)

**Comment by RAbraham** [comment]
@SteadBytes  Yes, that's what I was looking for. Thank you!

**Comment by SteadBytes** [comment]
Great! Glad to help, thanks again for using Flask-RESTPlus 😊

**Comment by ddb95** [comment]
curl -X POST "http://127.0.0.1:5000/todos/createTodo" -H "accept: application/json" -d "{'todoName': 'Build an API',
            'todoDetails':'We need to build the task',
            'status': 'Finished',
            'dueDate': '2021-10-23'}"
I am trying to send a post request, but  

def post(self):
        # returning the input payload for simplicity
        return api.payload
returns me nothing. I have tried everything. Any leads will be much helpful!

**Comment by ddb95** [comment]
Thanks this worked
