### ISSUE TITLE
Latest 0.13.0 release breaks errorhandler()

### ISSUE THREAD

**Issue by dmulter** [noirbizarre/flask-restplus#693]
My code that overrides an exception via errorhandler() that has worked forever broke with the latest 0.13.0 release. Falling back to 0.12.1 fixes the problem. Since it has been so long since there's been a release and the changelog is very hard to read, I have not been able to track down the code change that produced this problem yet.

```python
@api.errorhandler(SomeExistingError)
def handle_existing_exception(error):
    """Some Existing failure"""
    return dict(message=f"{error.error}: {error.description}"), error.status_code
```

**Comment by j5awry** [comment]
We'll have to take a look at this. there haven't been any changes to errorhandler in several years. Is there a stacktrace from your specific failure that might help while we work on reproducing the issue?

**Comment by dmulter** [comment]
Surprised me too based on the commits. No stack trace as the error was handled. I spotted because a test checks for `response.json['message']` for specific exceptions and got a key not found. I verified that the `handle_existing_exception` handler is never called and the raw exception comes through.

My other flask packages are always kept up to the latest. Don't know if it matters, but my errorhandler is declared in my `__init__.py` file. I'll work on a small reproducible example when I get a moment.

**Comment by dmulter** [comment]
Ok, here's the reproducible case. Note that maybe I have a misunderstanding about how errorhandler() should work.

Here's the code for a file `flask_min.py`:

```python
from flask import Flask
from flask_restplus import Resource, Api

app = Flask(__name__)
api = Api(app)

@api.errorhandler(Exception)
def handle_exception(error):
    print("handled exception!")

@api.route('/hello')
class HelloWorld(Resource):
    def get(self):
        raise Exception('Bad API parameter!')

if __name__ == '__main__':
    app.run(debug=True)
```

The first will print "handled exception!", while the second will not:

1. `pip install flask-restplus==0.12.1; python flask_min.py`
2. `pip install flask-restplus==0.13.0; python flask_min.py`

**Comment by Colin-b** [comment]
I think the issue is coming from the fact that you use debug=True, flask consider propagate_exception as True in this case, and due to this change, the exception is reraised

https://github.com/noirbizarre/flask-restplus/commit/0d95bcacdc5d347d003c1c4d8a613cd087ac6785

**Comment by dmulter** [comment]
Very interesting especially since the commit comment talks about Flask-JWT, and what I'm actually doing is overriding `JWTError` error handling so I can customize the 401 response. I of course need debug on while running my tests.

**Comment by Colin-b** [comment]
You should be able to override the default behavior by explicitly saying in your test application that you don't want exceptions to be propagated thanks to

    application.config["PROPAGATE_EXCEPTIONS"] = False

where application is your flask app :)

**Comment by dmulter** [comment]
I tried a test with just Flask using `debug=True` and `debug=False`. Both versions call my error handler.

```python
from flask import Flask

app = Flask(__name__)

@app.errorhandler(Exception)
def handle_exception(error):
    print("handled exception!")

@app.route('/hello')
def get():
    raise Exception('Bad API parameter!')

if __name__ == '__main__':
    app.run(debug=True)
```

**Comment by brmzkw** [comment]
Indeed, the problem comes from flask-restplus.

To reproduce:

```python
from flask import Flask
from flask_restplus import Resource, Api

app = Flask(__name__)
api = Api(app)


@api.errorhandler(KeyError)
def handler(exc):
    return {'error': 'exception'}


@api.route('/hello')
class HelloWorld(Resource):
    def get(self):
        raise KeyError

if __name__ == '__main__':
    app.run(debug=True)
```

The problem comes from this commit https://github.com/noirbizarre/flask-restplus/commit/0d95bcacdc5d347d003c1c4d8a613cd087ac6785?diff=unified


To fix, we could check if the exception raised is not registered by a handler error:

```python
        if (
            not isinstance(e, HTTPException) and
            current_app.propagate_exceptions and
            not isinstance(e, tuple(self.error_handlers.keys()))
        ):
            exc_type, exc_value, tb = sys.exc_info()
            if exc_value is e:
                raise
            else:
                raise e
```

I'll try to make a pull request soon.

**Comment by nerdvegas** [comment]
I've just hit this also

**Comment by brmzkw** [comment]
FYI flask-restplus is apparently no longer maintained and you should use flask-restx instead. I don't know if flask-restplus backported the fix, I haven't migrated yet.

If you create an issue on flask-restx, please highlight me :-)
