### ISSUE TITLE
swagger configs not working (i am a newbie, so i might be wrong)

### ISSUE THREAD

**Issue by iahim** [noirbizarre/flask-restplus#696]
First of all apologies, but i do not know any other place to ask for help... 
I am using flask-restplus with namespaces and blueprints - so i have /api/v1/  and /api/v2
That's fine so far, but it seems i can not modify the swagger ui:
`app.config['SWAGGER_UI_LANGUAGES'] = ['en', 'fr']
app.config.SWAGGER_SUPPORTED_SUBMIT_METHODS = ["get"]
`

The code where i put them all together looks like this:

## API v1

from api.api_v1 import blueprint as blueprint_api_v1
from api.api_v1 import api as api_v1
app.register_blueprint(blueprint_api_v1)
jwt._set_error_handler_callbacks(api_v1)

## API v2

from api.api_v2 import blueprint as blueprint_api_v2
from api.api_v1 import api as api_v2
app.register_blueprint(blueprint_api_v2)
jwt._set_error_handler_callbacks(api_v2)

## this stuff does not work:
app.config['SWAGGER_UI_LANGUAGES'] = ['en', 'fr']
app.config.SWAGGER_SUPPORTED_SUBMIT_METHODS = ["get"]

Any help is much appreciated ... again apologies in advance...

**Comment by SteadBytes** [comment]
Thanks for using Flask-RESTPlus, we will certainly try to help! Could you perhaps provide a slightly more complete code example, along with the version of Flask-RESTPlus you're using please?

`SWAGGER_SUPPORTED_SUBMIT_METHODS` disables the 'Try it out' button within the Swagger UI for a specific request method:
- Default:
![image](https://user-images.githubusercontent.com/14834132/63490499-badd6000-c4ac-11e9-813c-21443e20dfdb.png)
- With `app.config.SWAGGER_SUPPORTED_SUBMIT_METHODS = ["post"]` (disable the `get` method for try it out): 
![image](https://user-images.githubusercontent.com/14834132/63490535-d47ea780-c4ac-11e9-943b-7408800c0fa6.png)

As far as I'm aware, `app.config['SWAGGER_UI_LANGUAGES']` is not a supported configuration option for Flask-RESTPlus - may I ask where you found reference to that?

**Comment by iahim** [comment]
Hi @SteadBytes  - first of all thanks a lot for your response.
I will try to show... you what i have.
So i have a run.py where i import my api_v1 and api_v2 ... and in each api_vX i import the namespaces:
As you can see below... i tried adding the  `app.config.SWAGGER_SUPPORTED_SUBMIT_METHODS = ["get"]`  before and after the api blueprints registration:
Maybe i am doing something wrong with the blueprints... etc - but it all works :) I test my API using Insomnia (which by the way is a great tool - fyi)
Again - thanks in advance for all your time !!


## run.py
![run1](https://user-images.githubusercontent.com/1051201/63495420-19600980-c4c0-11e9-8ac7-6ac5bbc41235.png)
![run2](https://user-images.githubusercontent.com/1051201/63495442-27158f00-c4c0-11e9-90e9-e47643ade036.png)

## api_v2 (this is imported into run.py)
![apiv2](https://user-images.githubusercontent.com/1051201/63495473-3b598c00-c4c0-11e9-9c3f-cec6ec398536.png)

## ns1 (this is imported into api_v2
![ns](https://user-images.githubusercontent.com/1051201/63495514-50361f80-c4c0-11e9-860c-d29329e3343e.png)


## swagger:
![swagger](https://user-images.githubusercontent.com/1051201/63495924-26312d00-c4c1-11e9-84e6-f54cf9b9b977.png)

**Comment by iahim** [comment]
@SteadBytes IT WORKED - after upgrading to latest flask-restplus it does wooork !!
Sorry for wasting your time. 
But since i have done it already - is there a place where the flask-restplus community gets together? 
I have created a slack channel :   flask-restplus.slack.com   not sure ... if it makes sense to build there a community, but the communication can be faster on a chat app like slack.

**Comment by SteadBytes** [comment]
@iahim that was going to be my suggestion 😁 Glad it's working now, we already have a Gitter channel - feel free to hop on over there!
