### ISSUE TITLE
SLACK channel   flask-restplus.slack.com   

### ISSUE THREAD

**Issue by iahim** [noirbizarre/flask-restplus#699]
Hi guys,
I am very new to py/flask/ flask-restplus, BUT i see the huge benefits behind this project.
Maybe it's interesting to get together on a chat channel... like slack... and communicate faster.
What do you think?

**Comment by j5awry** [comment]
We have a gitter channel. feel free to join

https://gitter.im/noirbizarre/flask-restplus

**Comment by isaac-philip** [comment]
Gitter is good, as long as communication exists.
Can this issue be closed ?

**Comment by ziirish** [comment]
Sure
