### ISSUE TITLE
Ui url is fixed and cannot be changed

### ISSUE THREAD

**Issue by m-zajac** [noirbizarre/flask-restplus#7]
In api.py:136:

    self.blueprint.add_url_rule('/', 'root', self.render_root)

I think this url should be customizable. We not always want to expose ui on known uri.

**Comment by m-zajac** [comment]
Hi, this works with few modifications:

    from flask import Flask, Blueprint
    from flask.ext.restplus import API, apidoc, url_for

    app = Flask(__name__)
    blueprint = Blueprint('api', __name__, url_prefix='/api')
    api = Api(blueprint, ui=False)

    @blueprint.route('/doc/', endpoint='doc')
    def swagger_ui():
        return apidoc.ui_for(api)

    app.register_blueprint(blueprint)
    app.register_blueprint(apidoc.apidoc)  # only needed for assets and templates

I think its really useful to control ui in this way. This should be in docs. I'll fork and update.

**Comment by hnjoshi** [comment]
I am getting error: No module named flask.ext.restplus.url_for

**Comment by noirbizarre** [comment]
Yes, this is because `url_for` come from Flask not Flask-restplus.
In this exemple you can simply remove because it's not used:
```python
from flask import Flask, Blueprint
from flask.ext.restplus import API, apidoc

app = Flask(__name__)
blueprint = Blueprint('api', __name__, url_prefix='/api')
api = Api(blueprint, ui=False)

@blueprint.route('/doc/', endpoint='doc')
def swagger_ui():
    return apidoc.ui_for(api)

app.register_blueprint(blueprint)
app.register_blueprint(apidoc.apidoc)  # only needed for assets and templates
```

**Comment by hnjoshi** [comment]
@noirbizarre It worked. Much appreciate. Thank you for quick response!! :+1:

**Comment by qdog** [comment]
curl http://localhost:5000/api/doc/ hits this exception:
```
   return self.view_functions[rule.endpoint](**req.view_args)
TypeError: swagger_ui() takes exactly 1 argument (0 given)
```
With version:
```
>>> import flask.ext.restplus
>>> print flask.ext.restplus.__version__
0.7.2
```

**Comment by hnjoshi** [comment]
@qdog can you please post your mini program that you are trying to run, so I can try to repro the issue and solve it if I can't figure out simply by looking at the code.

**Comment by qdog** [comment]
You're too fast. I was about to update and say I had a cut-n-paste typo from another example. Sorry for the false alarm!

Anyway, thanks for flask-restplus, I love it :-)

**Comment by noirbizarre** [comment]
You're welcome.

By the way, this will evolve in 0.8.1: http://flask-restplus.readthedocs.org/en/latest/swaggerui.html
