### ISSUE TITLE
"Can't read swagger JSON" with url_prefix='/' in a blueprint 

### ISSUE THREAD

**Issue by ebourgeois** [noirbizarre/flask-restplus#70]
Hi,

I have a current flask-restful server that we want to upgrade and add blueprints so that we can root different versions with "v2", "v3", etc.To be backward compatible, we would like do the following:

```
FLASK_APP = flask.Flask(__name__)
blueprint = flask.Blueprint('v1', __name__, url_prefix='/')
API = restplus.Api(blueprint, version='1.0', ui=False,
                   title='DynDNS REST Server',
                   description='DynDNS\'s multiple endpoint REST server')

@blueprint.route('docs/', endpoint='docs')
def swagger_ui():
    return restplus.apidoc.ui_for(API)

FLASK_APP.register_blueprint(blueprint)
FLASK_APP.register_blueprint(restplus.apidoc.apidoc)
```

The old urls work fine, e.g. `/foo`, however, when I navigate to `/docs/`, I get "Can't read swagger JSON from..." in the browser; it doesn't seem to recognize where to find `sawgger.json`

**Comment by noirbizarre** [comment]
Hi !

I don't think '/' is a valid url prefix. It should be, in your case:
```python
blueprint = flask.Blueprint('v1', __name__, url_prefix='/v1')
```

If you want your API on the root (which is the default), just remove the URL prefix.

**Comment by ebourgeois** [comment]
The problem is I can't change '/', we already have V1 of our current API there, we want to start going towards versioned URLs now, That is, we already have `/foo` or `/bar` as endpoints, so we can't prefix with `v1`; but we can do `v2`. So, we are looking for a way to  leverage blueprints with `/` and `/docs`

**Comment by noirbizarre** [comment]
OK I will take a closer look at this case.
I don't think the solution can make it for the 0.8.0, probably in a 0.8.1.

**Comment by noirbizarre** [comment]
dead5d3 should fix that.
You should be able to write:
```python
app = flask.Flask(__name__)
blueprint = flask.Blueprint('v1', __name__) # No need for an url_prefix if its '/'
API = restplus.Api(blueprint, version='1.0', doc='/docs/,
                              title='DynDNS REST Server',
                              description='DynDNS\'s multiple endpoint REST server')
app.register_blueprint(blueprint)
```

Can you try it on the master?

**Comment by ebourgeois** [comment]
This works great, thanks!
