### ISSUE TITLE
Exceptions (including programming blunders) raised in api.errorhandler or namespace.errorhandler decorated functions are wrongly suppressed

### ISSUE THREAD

**Issue by rob-smallshire** [noirbizarre/flask-restplus#705]
If an exception is raised within an error handling function other than the exception that was passed as the argument to the handler (*i.e.* other than the original exception which caused the handler to be invoked), this new exception is suppressed by the implementation of `Api.error_router'. The original exception is propagated instead, hiding the programming blunder.

Code similar to the following will reproduce:

```python
api = restplus.Api(app)

class CustomException(RuntimeError):
    pass

class ProgrammingBlunder(Exception):
    pass

@api.route('/test/', endpoint="test")
class TestResource(restplus.Resource):
    def get(self):
        raise CustomException('error')

@api.errorhandler(CustomException)
def handle_custom_exception(error):
    raise ProgrammingBlunder("This exception needs to be logged, not suppressed, then cause 500")
```

In this case, there will be no mention of `ProgrammingBlunder` in the log output, and `CustomException` will be passed to the original Flask handler. It's as if `ProgrammingBlunder` never happened!

The problem lies in `Api.error_router`, an annotated version of which is shown below:

```python
    def error_router(self, original_handler, e):
        if self._has_fr_route():
            try:
                return self.handle_error(e)
            except Exception:  # <== programming errors in the handler not captured here
                pass  # Fall through to original handler
        return original_handler(e)  # <== original exception propagated and reported instead
        # Any information about buggy error handlers is lost and not reported 
```

This behaviour makes it *very* difficult to work with error handlers. Faulty error handlers just appear not to work at all – the effect is similar to the handler not having been properly registered or invoked, as there is no mention of the mistakes in the error handler in log output from Flask, and no guarantee that a 500 Internal Server error will be returned.

As a programmer, if an error handler is faulty, we want to know about that so the handler can be fixed. The current behaviour is pretty effective at concealing implementation errors.

**Comment by j5awry** [comment]
Merged #706 this should address the issue. Thank you for the contribution!
