### ISSUE TITLE
differential swagger documentation of get and post?

### ISSUE THREAD

**Issue by j-christ** [noirbizarre/flask-restplus#717]
I'm using the latest flask_restplus, and I can't quite figure something out.  Apologies if this isn't the correct forum for help, but I can't find any other place to ask.

I have a simple resource foo with a compound key (node_type and node_key).  To retrieve the resource you need both, but neither is in the URL to create a new foo resource:

```
@foo.route("/foo/<int:node_type>/<int:node_key>",
           "/foo")
class Foo(Resource):    
    def get(self, node_type, node_key):
        return {}

    def post(self):
        return {}
```

Users should only call POST on `/foo` and GET on `/foo/<node_type>/<node_key>`.

However, the auto-generated swagger documentation shows four routes for this

```
GET /foo
GET /foo/<node_type>/<node_key>
POST /foo
POST /foo/<node_type>/<node_key>
```

How should I structure this so that only

```
GET /foo/<node_type>/<node_key>
POST /foo
```

is shown in the documentation?

**Comment by J4YF7O** [comment]
Hello @j-christ , 

Does this solution solve your problem ? 

```
@foo.route('/foo')
class FooPost(Resource):
    def post(self):
        pass


@foo.route('/foo/<uuid>')
class FooGet(Resource):
    def get(self, uuid: str):
        pass
```

**Comment by j5awry** [comment]
@J4YF7O thank you, this is the correct approach.

the standard, simple way, is to have a separate `Resource` per path. Offering difference paths as part of the `route` spec is if you're doing the same functions in multiple paths. In this case, you've got 2 paths, doing 2 different functions, so have separate `Resources` makes the most sense.
