### ISSUE TITLE
Make a field required if another field's enum is chosen

### ISSUE THREAD

**Issue by Lomomn** [noirbizarre/flask-restplus#718]
I would like to make a field required only if a prior field has a certain value sent from the client.

Please check the snippet below to get a clear idea of what I'm asking:

```python
conditional_model = api.model('ConditionalModel', {
    'itemType': fields.String(required=True, enum=['box', 'notBox']),
    'contents': fields.List(fields.Nested(contents_model), 
        required=True if itemType=='box' else False)
})
```
I only want the contents field to be required if itemType is specified as 'box' from the client.

Is there an obvious solution to this that I'm missing?
Am I approaching this from the wrong angle?

**Comment by Lomomn** [comment]
Thinking about it, even if this field was required or not, it is still receiving the wrong type, null, instead of a list (in my project, not in this example). 

I feel like I need another model which doesn't have the optional field, but this would get pretty messy if I have multiple conditional fields.

**Comment by Colin-b** [comment]
To my knowledge you cannot describe a field as conditionally required in OpenAPI V2, so your client cannot have this kind of information 'automatically'.

A workaround would be to mark the field as optional and implement the check in a subclass of fields.List (and document this behaviour for your API users) or after the Flask Restplus parsing, inside your code. 

Also note that the ternary expression is overkill in your case, your condition can be the truth value of itemType == 'box'

**Comment by Lomomn** [comment]
Ah, that's a shame. 
I was hoping there was an easy solution without having to write much more additional code around the model.

Ye, I'm tired and wrote that ternary expression without really thinking about it haha.

Thank you for the help.
