### ISSUE TITLE
New version to pip?

### ISSUE THREAD

**Issue by jroyal** [noirbizarre/flask-restplus#72]
Just curious if you are planning on releasing a new version soon? There are a couple of things that are in the code base that I would like to use but they are newer than the version out on pip.

I left a comment on an old closed item and I'm not sure if you get notified about that so I'm creating this issue.

Thanks for creating this project. It's been a big help for me!

**Comment by awiddersheim** [comment]
:+1:

**Comment by noirbizarre** [comment]
You're welcome !

A new release is planned soon. I just want to fix some bug, do a little bit more testing on the new features.
There are also some pull-request I need to merge before.

Soon, very soon ! ;)
