### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by Colin-b** [noirbizarre/flask-restplus#727]
Using latest flask-restplus version with Python 3.7.4, I have the following warning:

```
flask_restplus/model.py:8: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

    from collections import OrderedDict, MutableMapping
```

It is not fixed on master branch and I cannot find any open item with "DeprecationWarning" matching this.

I can submit a PR to solve this if that's ok?

**Comment by andreykurilin** [comment]
Looks reasonable for me

**Comment by MajidHeydari** [comment]
I think that flask support python3.8 but I understand that doesn't currently support Python3.8 I'm upset .Flask have to base write with rust-cpython because If it wants to have high performance

**Comment by MajidHeydari** [comment]
Can use flask with dgraph?
