### ISSUE TITLE
Defining varaible keys in case of nested field model

### ISSUE THREAD

**Issue by knowBalpreet** [noirbizarre/flask-restplus#728]
```
	"preview": {
		"9:16": {
			"thumbnail": "",
			"video": ""
		}, "16:9": {
			"thumbnail": "",
			"video": ""
		}, "1:1": {
			"thumbnail": "",
			"video": ""
		}
	}
```

I have the above data coming in the request for which I want to create a model. I tried implementing wildcard fields but didn't get any success. In the above case, the aspect ratio is dynamic and can be anything but will always be in `*:*` format. In case that is coming, thumbnail and video are in nested modal with `required= true`. 

Any leads would be appreciated. Thanks in advance!

**Comment by andreykurilin** [comment]
Hi!

I guess, the easiest way will be using jsonschema directly:)

```python
SOME_MODEL = NAMESPACE.schema_model(
    "SomeModel", 
    {
        "type": "object",
        "properties": {
            "preview": {
                "type": "object",
                "patternProperties": {
                    r"^\d+=d+$": {
                        "type": "object",
                        "properties": {
                            "thubnail": ...
                            "video": ...
                        },
                       "required": ["thubnail", "video"],
                       "additionalProperties": False
                    }
                },
                "additionalProperties": False
            }
        },
        "required": ["preview"],
        "additionalProperties": False
    }
)

```

To descrese the depth of schema you can wrap it with custom FieldType

```python

import flask_restplus.fields


class SchemaField(flask_restplus.fields):
      def __init__(self, schema, *args)
          super(SchemaField, self).__init__(*args, **kwargs)
          self.the_right_schema = schema
     
     def schema(self):
          return self.the_right_schema

SOME_MODEL = NAMESPACE.model(
    "SomeModel",
    {
        "preview" : SchemaField(
             required=True,
             schema={
                 "type": "object",
                 "patternProperties": {
                     r"^\d+=d+$": {
                         "type": "object",
                         "properties": {
                             "thubnail": ...
                             "video": ...
                         },
                        "required": ["thubnail", "video"],
                        "additionalProperties": False
                     }
                 },
                 "additionalProperties": False
             }
         )
    }
)

```

**Comment by j5awry** [comment]
Just know that there are going to be issues in registering and rendering jsonschema in swagger if you use references. 

There are also wildcard fields:

https://flask-restplus.readthedocs.io/en/stable/marshalling.html#wildcard-field

The syntax is a bit tricky, and you need to define the wildcards **outside** your model. Furthermore, I'm not seeing an example of using models.Nested with Wildcards. I'll try and mock something up and see about Nested models and Wildcards

jsonschema definitely provides the most flexibility here, using either way @andreykurilin showed.

**Comment by knowBalpreet** [comment]
Thank you @andreykurilin and @j5awry  for the prompt response.
@j5awry I prefer doing it the wildcard way because then my model gets registered properly and marshal also works for filtering out noise data. But I am not able to make it work with Nested. If you can look into it, that would be great.

@andreykurilin I tried the json-schema way, it works but models don't get registered on swagger the way other models are. Also, marshal doesn't work on it. or maybe I am doing something wrong. Also, the second code example you shared didn't work. I am unable to debug what's the issue with it. Can you please help me with that?

Thanks again!

**Comment by andreykurilin** [comment]
@knowBalpreet, something like works me:
```
class SchemaField(flask_restplus.fields.Raw):
    def __init__(self, schema, *args, **kwargs):
        super(SchemaField, self).__init__(*args, **kwargs)
        self.the_right_schema = schema

    def schema(self):
        schema = super(SchemaField, self).schema()
        schema.update(self.the_right_schema)
        return schema
```

**Comment by knowBalpreet** [comment]
Thank you @andreykurilin for reverting back so quick. this works fine and validates the payload as expected. The only thing missing is `flask_restplus.marshal` does not work with it. My use case is that I want to create data JSON from `request.json` with default values. Not sure on how to achieve that.

**Comment by j5awry** [comment]
the quick and dirty is to merge two dicts, a default and the updated:

```
def post():
    req = copy.copy(request.json)  # not really needed, i copy too much
    default = {
        "key1": "default1",
        "key2": "default2"
     }
     merged = copy.deepcopy(default)
     merged.update(req)
```

**Comment by knowBalpreet** [comment]
For that I need to have default JSON and JSON schema for each model, So for any change I will need to change at multiple places. Is there a way to create a default JSON right from the JSON schema, based on the example or default attribute?

**Comment by ziirish** [comment]
Hi,

I'm having a look at the Wildcard code in order to make it work with Nested fields.
This seems like a legitimate use-case.

**Comment by knowBalpreet** [comment]
@ziirish , Can you also handle the marshal case with JSON schema.
Please refer to [this](https://github.com/noirbizarre/flask-restplus/issues/614#issuecomment-542499569)

> Hi,
> 
> I'm having a look at the Wildcard code in order to make it work with Nested fields.
> This seems like a legitimate use-case.

**Comment by ziirish** [comment]
I'm afraid I won't be your best asset for the JsonSchema thing as I never touched this piece of code.

**Comment by knowBalpreet** [comment]
I spent 3 days bringing all models to JSON schema from native models. Now I need to go back? JSON schema serves the use case. only problem I have is that marshal does not work with JSON schema. If you can look into it, it would be great.

**Comment by andreykurilin** [comment]
@knowBalpreet as for default values, it is almost "simple". JSONSchema supports "default" keyword and here is a documented hack to apply these values - https://python-jsonschema.readthedocs.io/en/stable/faq/ . you can apply it globally, like:

```
import jsonschema

jsonschema.Draft4Validator = MyCustomValidator
```

**Comment by ziirish** [comment]
@knowBalpreet yeah sorry, I'm not superman.
I have 0 knowledge on JSONSchema for now (and I only have limited spare time to work on Flask-RESTPlus).
But as I initially implemented the Wildcard fields I can offer to make it work with Nested fields.

**Comment by knowBalpreet** [comment]
Sorry, I forgot to respect your time and effort. Please make it work with nested. And thank you in advance

**Comment by ziirish** [comment]
Okay, so here is what I have been able to achieve:

```python
In [1]: from flask_restplus import fields, marshal

In [2]: d = {'preview': {'9:16': {'thumbnail': 24, 'video': 12},
   ...:   '16:9': {'thumbnail': 25, 'video': 11},
   ...:   '1:1': {'thumbnail': 26, 'video': 10}}}

In [3]: res_fields = {'thumbnail': fields.String(), 'video': fields.String()}

In [4]: nest = fields.Nested(res_fields)

In [5]: wild = fields.Wildcard(nest)

In [6]: wildcard_fields = {'*': wild}

In [7]: all_fields = {'preview': fields.Nested(wildcard_fields)}

In [8]: marshal(d, all_fields)
Out[8]: 
{'preview': {'1:1': {'thumbnail': '26', 'video': '10'},
  '16:9': {'thumbnail': '25', 'video': '11'},
  '9:16': {'thumbnail': '24', 'video': '12'}}}

In [9]: e = {'preview': {'1:1': [1, 2, 3], '16:9': [4, 5, 6], '9:16': [7, 8, 9]}}

In [10]: wild2 = fields.Wildcard(fields.List(fields.String))

In [11]: wildcard_fields2 = {'*': wild2}

In [12]: all_fields2 = {'preview': fields.Nested(wildcard_fields2)}

In [13]: marshal(e, all_fields2)
Out[13]: 
{'preview': {'9:16': ['7', '8', '9'],
  '16:9': ['4', '5', '6'],
  '1:1': ['1', '2', '3']}}
```

Does this look good for you?
