### ISSUE TITLE
Describing nested dictionaries followed by dynamic keys for marshal_with

### ISSUE THREAD

**Issue by KietnaQuTak** [noirbizarre/flask-restplus#737]
Hello. I may not understand examples I have found regarding describing model of dictionary with different names as keys cause I have no idea how to describe bellow model properly:
```python
{
	"number": 123,
	"docs": {
		"number_1": {
			"creator": "some@email.pl",
			"subject": "document subject",
			"filename": "document filename",
			"date": "2019-10-16 07:04:50.371130",
			"author": "author name",
			"r1": "recipient 1 name",
			"r2": "recipient 2 name",
			"r3": "recipient 3 name",
			"sent": true
		}
		"number_2": {
			"creator": "some@email.pl",
			"subject": "document subject",
			"filename": "document filename",
			"date": "2019-10-15 07:04:50.371130",
			"author": "author name",
			"r1": "recipient 1 name",
			"r2": "recipient 2 name",
			"r3": "recipient 3 name",
			"sent": true
		}
	}
}
```

In "docs" I'm planning to change into simple list of objects but for the moment I would like to describe model in which "docs" is a dictionary of smaller dictionaries indicated by keys {"number_1": MODEL_DOC, "number_2": MODEL_DOC}. I was trying to achieve it as bellow but I have now idea how to describe "(document_number)" to indicate that there could be many different document dictionaries followed by document numbers as key (strings).

```python
MODEL_DOC = api.model('Document', {
	CREATOR: fields.String(description='Creator e-mail.'),
	SUBJECT: fields.String(description='Subject.'),
	FILENAME: fields.String(description='Filename.'),
	DATE: fields.DateTime(description='Generation date.'),
	AUTHOR: fields.String(description='Author name.'),
	R1: fields.String(description='1st recipient name.'),
	R2: fields.String(description='2nd recipient name.'),
	R3: fields.String(description='3rd recipient name.'),
	SENT: fields.Boolean(description='Sent status.')
})
MODEL_DOCS = api.model('Documents', {
	'(document number)': fields.Nested(MODEL_DOC)
})

MODEL_DOWNLOAD_RESPONSE = api.model('Document Download Response', {
	NUMBER: fields.Integer(description='Document number.'),
	DOCS: fields.Nested(MODEL_DOCS, description='Dictionary with documents number as key and document data as value.')
})
```

Best regards
Kietna Qu'Tak

**Comment by ziirish** [comment]
Hello,

What you are looking for is [Wildcard](https://flask-restplus.readthedocs.io/en/stable/marshalling.html#wildcard-field) fields.
Unfortunately, it does not support `Nested` inner fields yet (although the PR is actually ready #739).

Details may be found here: https://github.com/noirbizarre/flask-restplus/issues/728#issuecomment-542772324

**Comment by ziirish** [comment]
So, in the end, your model will look like:

```python
MODEL_DOC = api.model('Document', {
	CREATOR: fields.String(description='Creator e-mail.'),
	SUBJECT: fields.String(description='Subject.'),
	FILENAME: fields.String(description='Filename.'),
	DATE: fields.DateTime(description='Generation date.'),
	AUTHOR: fields.String(description='Author name.'),
	R1: fields.String(description='1st recipient name.'),
	R2: fields.String(description='2nd recipient name.'),
	R3: fields.String(description='3rd recipient name.'),
	SENT: fields.Boolean(description='Sent status.')
})
MODEL_NEST = fields.Nested(MODEL_DOC)
MODEL_WILD = fields.Wildcard(MODEL_NEST)
MODEL_DOCS = api.model('Documents', {
	'*': MODEL_WILD
})
MODEL_DOWNLOAD_RESPONSE = api.model('Document Download Response', {
	'number': fields.Integer(description='Document number.'),
	'docs': fields.Nested(MODEL_DOCS, description='Dictionary with documents number as key and document data as value.')
})
```

Note: it's important to define your `MODEL_WILD` **outside** your `MODEL_DOCS` because we need to keep a track of what objects have already been parsed by the `Wildcard` field and the best way to do this is to have the `Wildcard` object registered separately.

**Comment by ziirish** [comment]
Now closing as the patch has been merged

**Comment by gabrielbazan** [comment]
Hi all! When will this be released in a new version? It has been merged in November last year, but it's not available in PyPI.
Thanks!

**Comment by j5awry** [comment]
speaking as a maintainer -- flask-restplus has been declared dead. The only person with keys to release has left the project, and didn't hand anything over. There is an official fork at 

https://github.com/python-restx/flask-restx

https://pypi.org/project/flask-restx/

it's a drop in replacement, just change your import names

This commit is in the first release of flask-restx (as it was slated for the 0.14 release that never occurred)

**Comment by gabrielbazan** [comment]
Thank you very much @j5awry !
