### ISSUE TITLE
Update pip

### ISSUE THREAD

**Issue by stevezau** [noirbizarre/flask-restplus#79]
Hi,

My projects 2.6 tests are failing due to the api.validate conflict bug. It's already fixed but the package on pip has not been updated.

Any chance we can get the package on pip built/updated?

**Comment by noirbizarre** [comment]
I will perform a 0.8.1 release this week. Until then you can install the master from github:
```shell
$ pip install https://github.com/noirbizarre/flask-restplus/zipball/master
```

**Comment by frol** [comment]
@noirbizarre 1.5 month went by...

**Comment by noirbizarre** [comment]
@frol you're right. I will perform a release this afternoon.

Remaining issues for 0.8.1 will be in 0.8.2.

Starting from now, I will try to release more often.

**Comment by noirbizarre** [comment]
The 0.8.1 has been published ;)
