### ISSUE TITLE
Latest Release is older than current master by 2.5 years.

### ISSUE THREAD

**Issue by mittal-umang** [noirbizarre/flask-restplus#807]
@SteadBytes 
Please send out a new release.

**Comment by SteadBytes** [comment]
Please see the notice in the project README:

> IMPORTANT NOTICE:
> 
> This project has been forked to Flask-RESTX and will be maintained by by the python-restx organization. Flask-RESTPlus should be considered unmaintained.

I personally no longer work on Flask-RESTX but there are other active maintainers over there 👍
