### ISSUE TITLE
Flask-Login

### ISSUE THREAD

**Issue by leiserfg** [noirbizarre/flask-restplus#83]
There is a non magic way to use login with that lib??

**Comment by noirbizarre** [comment]
It depends on what you expect.
I'm using Flask-Login (via Flask-Principal) in my own projects without any problem.

Can you give me more details on your use case ?

**Comment by leiserfg** [comment]
Sorry I'm new with this lib. I saw I can use it the same way I did with flask-restful.

**Comment by frol** [comment]
@leiserfg I have built a real-world example RESTful API server based on Flask-RESTplus with some patches (I hope we will merge those to the upstream once @noirbizarre removes Flask-RESTful dependency): https://github.com/frol/flask-restplus-server-example

Here is the exact place where I bind `current_user` to the real user instance: https://github.com/frol/flask-restplus-server-example/blob/master/app/modules/auth/__init__.py (`login_manager` is [an instance of `Flask-Login.LoginManager`](https://github.com/frol/flask-restplus-server-example/blob/master/app/extensions/__init__.py#L7))

**Comment by noirbizarre** [comment]
Hi !

Can I close this issue ?

**Comment by leiserfg** [comment]
Yes close it.
