### ISSUE TITLE
POST adding extra header

### ISSUE THREAD

**Issue by dohjoe** [noirbizarre/flask-restplus#84]
Using the 0.8.0 version I discovered an issue today when trying to use the swagger UI to test a POST.  An extra header (--header "Content-Type: application/json") is being added to the curl command, and this is causing the my FLASK server to error out and return 400 error code.  If I manually execute the curl command without the extra header it completes successfully.

This seems to be a similar issue to this one, that is in reference to a GET.  https://github.com/noirbizarre/flask-restplus/issues/15

**Comment by cdumay** [comment]
+1
Updated to 0.8.0 and now I cannot use swagger UI to test a POST, got 400 "The browser (or proxy) sent a request that this server could not understand." It works using the curl generated without the extra header "Content-Type: application/json".

**Comment by gddk** [comment]
Same here:

This does not work, and its what the swagger UI does:
```
curl -v -X POST --header "Content-Type: application/json" --header "Accept: application/json" "http://192.168.101.81:8000/api/v1/vms/1/destroy”
```

If I do this manually, it works:
```
curl -v -X POST --header "Accept: application/json" "http://192.168.101.81:8000/api/v1/vms/1/destroy”
```

Thanks for adding it the 0.8.1 milestone :)

**Comment by noirbizarre** [comment]
Hi !

I need some inputs on this one. I can't manage to reproduce it.
Can you provide a sample API (a single resource with a single method) to reproduce it ?
What decoators do you use ?

**Comment by noirbizarre** [comment]
Hi !

Can someone test with the 0.8.1 release and tell me if it still occurs ?
If this is stil the case, can someone give me a sample case (I need the resource declaration with its decorators, the API parameters and the app configuration (ie. `RESTPLUS_VALIDATE`...)

**Comment by PradeepJaiswar** [comment]
Any update on this , I am facing the same issue.

Here is my json file

{
    "basePath": "/v1/api", 
    "definitions": {
        "EmailModel": {
            "format": "email", 
            "type": "string"
        }, 
        "KeysModel": {
            "properties": {
                "name": {
                    "type": "string"
                }
            }, 
            "type": "object"
        }, 
        "UserModel": {
            "properties": {
                "id": {
                    "format": "int64", 
                    "type": "integer"
                }, 
                "keys": {
                    "items": {
                        "$ref": "#/definitions/KeysModel"
                    }, 
                    "type": "array"
                }, 
                "mail": {
                    "$ref": "#/definitions/EmailModel"
                }, 
                "name": {
                    "type": "string"
                }
            }, 
            "required": [
                "name"
            ], 
            "type": "object"
        }
    }, 
    "host": "localhost:5000", 
    "info": {
        "description": "This is the version 1 of API", 
        "termsOfService": "", 
        "title": "API v2", 
        "version": "0.1"
    }, 
    "paths": {
        "/logs": {
            "get": {
                "description": "Returns a user", 
                "parameters": [
                    {
                        "description": "User identifier", 
                        "in": "path", 
                        "name": "user_id", 
                        "type": "integer"
                    }
                ], 
                "responses": {
                    "200": {
                        "description": "User", 
                        "examples": {
                            "application/json": {
                                "id": 1, 
                                "name": "somebody"
                            }
                        }, 
                        "schema": {
                            "$ref": "#/definitions/UserModel"
                        }
                    }
                }, 
                "tags": [
                    "user"
                ]
            }
        }, 
        "/urls": {
            "post": {
                "description": "Returns a user", 
                "parameters": [
                    {
                        "description": "User identifier", 
                        "in": "path", 
                        "name": "user_id", 
                        "type": "integer"
                    }
                ], 
                "responses": {
                    "200": {
                        "description": "User", 
                        "examples": {
                            "application/json": {
                                "id": 1, 
                                "name": "somebody"
                            }
                        }
                    }
                }, 
                "tags": [
                    "user"
                ]
            }
        }
    }, 
    "produces": [
        "application/json", 
        "text/html"
    ], 
    "swagger": "2.0"
}

**Comment by PradeepJaiswar** [comment]
Any update on this  ??  I am facing the same issue

**Comment by gangefors** [comment]
I've run into this bug. It happens when you add request param arguments to RequestParam.

Here's how to replicate it.

```
parser = RequestParser()
parser.add_argument(
    required=True,
    name='foo',
    default='bar',
)
@api.route('/atoms')
class Test(Resource):
    @api.expect(parser)
    def patch(self):
        args = parser.parse_args(strict=True)
        return {}, 200
```

`curl -X PATCH --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://127.0.0.1:5000/api/v2/atoms?foo=bar'`

This will throw and exception and return the following.
```
{
  "message": "Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)"
}
```

The stacktrace:
```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.5/site-packages/flask/wrappers.py", line 157, in get_json
     rv = json.loads(data)
   File "/usr/local/lib/python3.5/site-packages/flask/json.py", line 146, in loads
     return _json.loads(s, **kwargs)
   File "/usr/local/lib/python3.5/json/__init__.py", line 332, in loads
     return cls(**kw).decode(s)
   File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/tmp/foo.py", line 30, in patch
     args = parser.parse_args(strict=True)
   File "/usr/local/lib/python3.5/site-packages/flask_restplus/reqparse.py", line 347, in parse_args
     req.unparsed_arguments = dict(self.argument_class('').source(req)) if strict else {}
   File "/usr/local/lib/python3.5/site-packages/flask_restplus/reqparse.py", line 128, in source
     value = getattr(request, l, None)
   File "/usr/local/lib/python3.5/site-packages/werkzeug/local.py", line 347, in __getattr__
     return getattr(self._get_current_object(), name)
   File "/usr/local/lib/python3.5/site-packages/flask/wrappers.py", line 108, in json
     return self.get_json()
   File "/usr/local/lib/python3.5/site-packages/flask/wrappers.py", line 162, in get_json
     rv = self.on_json_loading_failed(e)
   File "/usr/local/lib/python3.5/site-packages/flask/wrappers.py", line 181, in on_json_loading_failed
     raise BadRequest('Failed to decode JSON object: {0}'.format(e))
```

The bottom line is that when the 'Content-Type: application/json' header is added, the request will return True for req.is_json() and then when flask/wrappers.py tries to do json.loads(data) it will do that with data=b'' which will fail.

I think it should either be possible to use 'Content-Type: application/json' header while not sending any data (only params) or the swagger UI should not add the 'Content-Type: application/json' header if there is no data to be sent.

Please reopen this issue since it's not fixed.

**Comment by Jeevan-bhandari-git** [comment]
Remove the old one Request in POSTMAN Collection and create new one.
