### ISSUE TITLE
Documenting with @api.expect() decorator using a JSON schema

### ISSUE THREAD

**Issue by postrational** [noirbizarre/flask-restplus#88]
I would like to use the `@api.expect()` decorator or similar with a model build around a custom JSON schema.

I was able to achieve what I need using the following code, which overrides the model's `__schema__` property:

```python
resource_fields = api.model('Resource', {
    'name': fields.String,
})

resource_fields.__schema__ = {
    'type': 'object',
    'properties': {
        'name': {'type': 'string', 'minLength': 5, 'maxLength': 50},
    }
}

@api.route('/my-resource/<id>')
class MyResource(Resource):
    @api.expect(resource_fields)
    def get(self):
        pass
```

Is there a method in the API which allows for this without using the private `__schema__` property?
If there is and you provide an example, I can test it and add it to the documentation.

**Comment by noirbizarre** [comment]
Right now, using raw JSON schemas is not supported.

But, every attribute supported by Swagger specifications should be available as a field parameter.
You're right, right now it's missing the `min` and `max` for `String` field.
I will fix that and then you could write::
```python
resource_fields = api.model('Resource', {
    'name': fields.String(min=5, max=50),
})

@api.route('/my-resource/<id>')
class MyResource(Resource):
    @api.expect(resource_fields)
    def get(self):
        pass
```

**Comment by postrational** [comment]
`minLength` and `maxLength` are not the only properties defined by JSON Schema Draft 4.

Other fields include `pattern` for regex matching, `required` to specify which fields within an object are necessary to pass validation, and `multipleOf` for numeric values.

Take a look at this part of the spec for more info:
https://github.com/json-schema/json-schema/blob/master/draft-04/schema#L45-L69

It would be great if Flask-RestPlus models could implement also these properties for input validation.

In the meantime I'm using custom JSON schema validation like this:

```python
validate_api_key_request = api.json_schema_model('Validate key request', {
    'type': 'object',
    'properties': {
        'user': {'type': 'string', 'minLength': 3, 'maxLength': 32},
        'key': {'type': 'string', 'pattern': '[0-9A-F]{64}'},
    },
    'required': ['user', 'key']
})
```

This is made possible by adding an additional method onto the RestPlus Api class.
This is a bit of a hack, as it will only work for a json schema of an `object`, which defines `properties` and it can only be used for input validation, not for marshalling output.

```python
from flask.ext.restplus import fields
from flask.ext.restplus import Api

class MyApi(Api):
    def json_schema_model(self, name=None, json_schema=None, **kwargs):
        fields_dict = dict([(key, fields.BaseField) for key in json_schema.get('properties', {}).keys()])
        model = self.model(name, fields_dict, **kwargs)
        model.__schema__ = json_schema
        return model
```

If you wanted to allow custom validation by JSON schema, I'm sure you could make this solution more robust.

**Comment by gazpachoking** [comment]
Some more discussion on this in #53
