### ISSUE TITLE
Strange critical error with version 0.8.0

### ISSUE THREAD

**Issue by andresmrm** [noirbizarre/flask-restplus#89]
Hello! I'm having an strange error in production:
https://gist.github.com/andresmrm/b4336dcc735b40fb1852
(I tried, but I'm not sure I could isolate it correctly, for it repeats the same message a lot...)
The error appears only after ~700 requests have been served and no more request can be served after it, making it dangerous and tricky...

Cut my app to a bare minimum code, and still got the same error.
Changed from Python-Restplus to Python-Restful, and the error disappeared.

I had a microservice with Restplus that was working well, and so I tried to compare the differences.
This microservice was using older libs, restplus==0.7.2 and its older deps.
So I downgraded the problematic microservice from 0.8.0 to 0.7.2, but still got the same error.
Then I downgraded also the deps, and the error disappeared.
So I would say the error is caused by an incompatibility between Restplus with one of the new version deps.

But then... trying to figure out the incompatible dep, I tried to keep restplus==0.7.2 and upgrade the deps. But I was unable to reproduce the error until upgraded Restplus to 0.8.0.
So I'm not sure if it is an error in Restplus itself, or in one dep, but it sure happens for me when using Restplus 0.8.0.

If needed, I can try to make an example project to reproduce the error.

**Comment by awiddersheim** [comment]
See https://github.com/noirbizarre/flask-restplus/pull/81

**Comment by andresmrm** [comment]
Great! Thanks!
Closing this issue.
