### ISSUE TITLE
Unable to generate POST form parameters

### ISSUE THREAD

**Issue by drewdogg** [noirbizarre/flask-restplus#92]
I am trying to generate the Swagger documentation for a POST endpoint which accepts x-www-form-urlencoded parameters, but I do not see a way how to do this.  Is this supported?

Right now I have something like:
```
@api.route(BASE_URL+'/update_resource_attribute')
class UpdateResourceAttributeResource(Resource):
    
    @api.doc(params={'resource_name': 'Resource name',
                     'attribute_name': 'Attribute name',
                     'attribute_value': 'Attribute value',
                     'config_name': 'Config name'})
    def post(self):
        resource_name = request.form['resource_name']
        attribute_name = request.form['attribute_name']
        attribute_value = request.form['attribute_value']
        config_name = request.form['config_name']
```
My problem is api.doc 'params' keyword is only used for URL string parameters, not form parameters.  I need something like 'formData' from the Swagger spec.

**Comment by noirbizarre** [comment]
Hi !

This is because you're doing it wrong.

Given your case, you have two choices:
- Use the request parser to declare form parameters and give it as argument to your decorator: http://flask-restplus.readthedocs.org/en/stable/documenting.html#input-and-output-models.

  This is the recommended way because it performs validation (and expose Swagger documentation)
  ```python
# First choice: RequestParser
parser = api.parser()
parser.add_argument('resource_name', type=str, help='Resource name', location='form')
parser.add_argument('attribute_name', type=str, help='Attribute name', location='form')
parser.add_argument('resource_value', type=str, help='Attribute value', location='form')
parser.add_argument('config_name', type=str, help='Config name', location='form')

@api.route(BASE_URL+'/update_resource_attribute')
class UpdateResourceAttributeResource(Resource):
    @api.doc(parser=parser)
    def post(self):
        args = parser.parse_args()
        # Do whatever you want with parsed/validated arguments
        resource_name = args['resource_name']
        # ...
```

- Use the right syntax for declaring parameters
  ```python
# Second choice: simple parameters declaration
@api.route(BASE_URL+'/update_resource_attribute')
class UpdateResourceAttributeResource(Resource):

    @api.doc(params={
        'resource_name': {'in': 'form', description': 'Resource name'},
        'attribute_name': {'in': 'form', description': 'Attribu}te name'},
        'attribute_value': {'in': 'form', description': 'Attribute value'},
        'config_name': {'in': 'form', description': 'Config name'})
    def post(self):
        resource_name = request.form['resource_name']
        attribute_name = request.form['attribute_name']
        attribute_value = request.form['attribute_value']
        config_name = request.form['config_name']
```

**Comment by noirbizarre** [comment]
Hi !
Did this solved your problem ? Can I close this issue ?

**Comment by drewdogg** [comment]
Hi @noirbizarre thank you for the help.  I tried it the second way using simple parameters, and now I see the correct input fields.  However sending the request using the generated Swagger doc sets the content type to application/json, when it should be x-www-form-urlencoded.

**Comment by drewdogg** [comment]
I changed the 'in' value from 'form' to 'formData', and now the content type is the correct "application/x-www-form-urlencoded".  I suggest adding this example to the documentation.

**Comment by BobDenny** [comment]
BOOYAH!!!! This is what I needed! THANK YOU BOTH!

**Comment by aadityachapagain** [comment]
Thanks this issue is so much helpful.
