### ISSUE TITLE
Method restrictions aren't honoured in the Swagger UI

### ISSUE THREAD

**Issue by bodgit** [noirbizarre/flask-restplus#93]
I have an example class declared like so:

```python
@api.route('/foo/bar', endpoint='foo')
@api.route('/bar', methods=['GET'], endpoint='bar')
class Bar(Resource):
    @api.doc(...)
    def get(self):
        ...

    @api.doc(...)
    def post(self):
        ...
```

The method restriction works in that I can not `POST` to `/bar` however in the Swagger UI, the `/bar` endpoint will still have documentation for both `GET` & `POST`, the same as for `/foo/bar` when it should only have the `GET` documentation. I'm using version 0.8.0.

**Comment by frol** [comment]
@bodgit Could you please tell me why do you write `def post()` in the first place if you are not going to handle it anyway?

**Comment by bodgit** [comment]
I am handling it, but only for the first route.

**Comment by frol** [comment]
@bodgit I see now. Thank you.

**Comment by frol** [comment]
@bodgit I was thinking about your usecase and I can suggest you just split your class into two with inheritance:

```Python
@api.route('/bar', endpoint='bar')
class Bar(Resource):
    @api.doc(...)
    def get(self):
        ...

@api.route('/foo/bar', endpoint='foo')
class PostableBar(Bar):
    @api.doc(...)
    def post(self):
        ...
```

This seems to be an even cleaner solution and you don't need `methods=['GET']` at all.

**Comment by noirbizarre** [comment]
Thansk @frol for the response.

@bodgit request is legit so I will handle method restrictions in flask-restplus

**Comment by noirbizarre** [comment]
After taking a quick look at it, it seems to be not so trivial right now.

The main issue is that flask-restplus does not handle multiple/different documentation on a single class.
It needs refactoring so I suggest you use @frol workaround until flask-restplus is able to do it properly.
