### ISSUE TITLE
Namespaces should be lazy registerable

### ISSUE THREAD

**Issue by noirbizarre** [noirbizarre/flask-restplus#95]
As @frol suggested, for big APIs splitted on multiple files, Namespace should be the only class to import.
As Blueprints for Flask, it should provide all necessary methods to not require the API instance in the file and to be lazy registerable.

The target is being able to write:

```python
# feature.py
from flask_restplus import Namespace, Resource

ns = Namespace('feature', 'Some namespace')

model = ns.model('Model', {})

@ns.route('/')
class MyFeature(Resource):
    @ns.marshal_with(model)
    def get(self):
        pass      
```

```python
# api.py
from flask_restplus import Api
from feature import ns

api = Api()
api.register_namespace(ns)
```

**Comment by frol** [comment]
Thank you for considering this!

By the way, there would be another obstacle. It is the fact that all decorators are available from `api` instance now.

**Comment by noirbizarre** [comment]
Yes, I know, but it shouldn't be hard to keep references to call them on registeration.

As I started integrating code from flask-restful, it should be easier.

**Comment by frol** [comment]
Reading Flask-RESTful code (dealing with some issues), I was so surprised that you had made a choice to base Flask-RESTplus on it... I'm still puzzled why it is made simple things so complex.

BTW, digging into Flask-RESTplus while I was patching it to use marshmallow, webargs, and apispec, I caught myself on the thought that Flask-RESTplus may only provide a thin wrappers around components (resources (e.g. just make it a separate project), parameters (`webargs`), definitions (`marshmallow`+`marshmallow-sqlalchemy`+`flask-marhsmallow`), classes-to-swagger-specs (`apispec`)).

**Comment by noirbizarre** [comment]
I agree but it was a very base to start, allowing to focus on the swagger part.
Then I started to add more features and started to realize that what helped me on the start was becoming a technical debt.

This is the target goal for 1.0:

- being a standalone extension 
- provide a base making API quickly (marshalling, swagger...)
- being pluggable: let contributors provide implementations for their favorite request parser...

I have some frustrations toward Swagger 2.0. I like it but a point bother me: I want full JSON Schema v4. Maybe OADF wil change it: http://apievangelist.com/2015/11/05/the-swagger-spec-is-reborn-as-open-api-definition-format-oadf-after-being-put-into-open-api-initiative-oai/

**Comment by frol** [comment]
@noirbizarre May I ask you what exactly bothers you in the current Swagger Spec? I haven't hit any limitations of the spec yet. I really like its flexibility level.

**Comment by noirbizarre** [comment]
To make it short:

- no full JSON Schema v4 support (very problematic) so:
  - no possibilities to reuse existing schemas like geojson
  - no oneOf, anyOf...
  - no `null` type
- no global parameters (like lang/language or x-fields header)

Most of my griefs are tagged for next propposal but there is no will to start working on it right now:
https://github.com/swagger-api/swagger-spec/labels/Swagger.Next%20Proposal

**Comment by frol** [comment]
Wow! I will definitely try this once I have some free time. Thank you @noirbizarre!

**Comment by noirbizarre** [comment]
You're welcome !!!

See http://flask-restplus.readthedocs.org/en/latest/scaling.html for the documentation.
