### ISSUE TITLE
Parser arguments from fields

### ISSUE THREAD

**Issue by mekanix** [noirbizarre/flask-restplus#98]
Currently I'm using fields for `api.expect()` and almost the same set of fields for `parser.add_argument()`. Is there a way to generate arguments from fields or vice versa? If not, what is the recommended way to deal with fields and arguments? Thanx!

**Comment by noirbizarre** [comment]
Hi !

I'm not sure about what you asking. A code sample would be more easier to understand.

If my guess is right, you already can use model fields with the parser:
```python
Todo = api.model('Todo', {
   'title': fields.String(required=True)
 })

parser.add_argument('todo', type=Todo)
```

Is this what you are looking for ?

**Comment by mekanix** [comment]
Well, it's closer to what I'm looking for, but I didn't understand how to combine api.model with peewee or mongoengine. Is there a way to do that?

**Comment by noirbizarre** [comment]
It's not meant to be combined.
The API model describe how you serialize an object whatever it is, a mongoengine object or a peewee one. You simply return it in your API method.
```python
todo_fields = api.model('Todo', {
   'id': fields.Integer(readonly=True),
   'title': fields.String(required=True),
 })

class TodoResource(Resource):
    @api.expect(todo_fields)
    @api.marshal_with(todo_fields)
    def get(self):
        # Using MongoEngine, I can write:
        todo = Todo.objects.get(id=1)
        return todo
```

It's tempting to have the same models between your ORM and your API but sometime:
- you won't return all the fields
- you won't return a DB model
- you will apply some transformation
- documentations will differs or be insufficient
- ...

If you need to have exactly the same fields, you can write a piece of code transforming a peewee or a mongoengine model into an API model.

**Comment by mekanix** [comment]
Ah, the model part got me confused. What you said makes sense now. Thank you!
